apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
metadata:
  name: {{ .Values.global.namespace }}
{{- if .Values.global.metadata }}
{{- if .Values.global.metadata.labels }}
  labels:
{{ toYaml .Values.global.metadata.labels | indent 4 }}
{{- end }}
{{- if .Values.global.metadata.annotations }}
  annotations:
{{ toYaml .Values.global.metadata.annotations | indent 4 }}
{{- end }}
{{- end }}