global:
  namespace: dev
  springProfilesActive: dev
  replicaCount: 1
  metadata:
    name: dev
    labels:
      environment: ci
      managed-by: helm
      pod-security.kubernetes.io/enforce: "baseline"
      pod-security.kubernetes.io/enforce-version: "latest"
      pod-security.kubernetes.io/audit: "baseline"
      pod-security.kubernetes.io/warn: "baseline"
    annotations:
      description: "CI environment for ecommerce microservices testing"

# Deshabilitar HPA globalmente para todos los servicios
service-discovery:
  autoscaling:
    enabled: false
  resources: null

cloud-config:
  autoscaling:
    enabled: false
  resources: null

api-gateway:
  autoscaling:
    enabled: false
  resources: null

product-service:
  autoscaling:
    enabled: false
  resources: null

user-service:
  autoscaling:
    enabled: false
  resources: null

payment-service:
  autoscaling:
    enabled: false
  resources: null

shipping-service:
  autoscaling:
    enabled: false
  resources: null

favourite-service:
  autoscaling:
    enabled: false
  resources: null

order-service:
  autoscaling:
    enabled: false
  resources: null

proxy-client:
  autoscaling:
    enabled: false
  resources: null