global:
  namespace: dev
  springProfilesActive: dev
  replicaCount: 1
  metadata:
    name: dev
    labels:
      environment: ci
      managed-by: helm
      pod-security.kubernetes.io/enforce: "baseline"
      pod-security.kubernetes.io/enforce-version: "latest"
      pod-security.kubernetes.io/audit: "baseline"
      pod-security.kubernetes.io/warn: "baseline"
    annotations:
      description: "CI environment for ecommerce microservices testing"

# Deshabilitar HPA globalmente para todos los servicios
service-discovery:
  autoscaling:
    enabled: false
  resources: {}

cloud-config:
  autoscaling:
    enabled: false
  resources: {}

api-gateway:
  autoscaling:
    enabled: false
  resources: {}

product-service:
  autoscaling:
    enabled: false
  resources: {}

user-service:
  autoscaling:
    enabled: false
  resources: {}

payment-service:
  autoscaling:
    enabled: false
  resources: {}

shipping-service:
  autoscaling:
    enabled: false
  resources: {}

favourite-service:
  autoscaling:
    enabled: false
  resources: {}

order-service:
  autoscaling:
    enabled: false
  resources: {}

proxy-client:
  autoscaling:
    enabled: false
  resources: {}