
global:
  namespace: prod
  springProfilesActive: prod
  replicaCount: 1
  database:
    url: "jdbc:mysql://db:3306/ecommerce_db"
    username: "user"
    password: "12345"
  metadata:
    name: prod
    labels:
      environment: prod
      managed-by: helm
      pod-security.kubernetes.io/enforce: "restricted"
      pod-security.kubernetes.io/enforce-version: "latest"
      pod-security.kubernetes.io/audit: "restricted"
      pod-security.kubernetes.io/warn: "restricted"
    annotations:
      description: "Production environment for ecommerce microservices"
