apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.config.globalScrapeInterval }}
      evaluation_interval: {{ .Values.config.globalEvaluationInterval }}
      scrape_timeout: {{ .Values.config.scrapeTimeout }}
      external_labels:
        cluster: 'ecommerce-k8s'
        environment: '{{ .Values.global.springProfilesActive }}'

    scrape_configs:
      # Scrape Prometheus mismo
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'kubernetes-cadvisor'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: false
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        kubernetes_sd_configs:
          - role: node

        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

          - target_label: __address__
            replacement: kubernetes.default.svc:443

          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor

          - source_labels: [__meta_kubernetes_node_name]
            target_label: node


      - job_name: 'kubernetes-kubelet'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: false
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        kubernetes_sd_configs:
          - role: node

        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

          - target_label: __address__
            replacement: kubernetes.default.svc:443

          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/$1/proxy/metrics

          - source_labels: [__meta_kubernetes_node_name]
            target_label: node

      
      - job_name: 'kubernetes-kubelet-resource'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: false
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        kubernetes_sd_configs:
          - role: node

        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

          - target_label: __address__
            replacement: kubernetes.default.svc:443

          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/$1/proxy/metrics/resource

          - source_labels: [__meta_kubernetes_node_name]
            target_label: node

    
      - job_name: 'spring-boot-actuator'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                {{- if .Values.config.targetNamespaces }}
                {{- range .Values.config.targetNamespaces }}
                - {{ . }}
                {{- end }}
                {{- else }}
                - dev
                - qa
                - prod
                {{- end }}
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            action: keep
            regex: (api-gateway|user-service|product-service|order-service|payment-service|shipping-service|favourite-service|proxy-client)

          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http

          - source_labels: [__meta_kubernetes_service_name]
            target_label: service

          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace

          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

          - target_label: __metrics_path__
            replacement: /actuator/prometheus

     
      - job_name: 'zipkin'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                {{- if .Values.config.targetNamespaces }}
                {{- range .Values.config.targetNamespaces }}
                - {{ . }}
                {{- end }}
                {{- else }}
                - dev
                - qa
                - prod
                {{- end }}
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            action: keep
            regex: zipkin

          - source_labels: [__meta_kubernetes_service_name]
            target_label: service

          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace

          - target_label: __metrics_path__
            replacement: /prometheus

      # ============================================
      # Scrape de Eureka CROSS-NAMESPACE
      # ============================================
      - job_name: 'eureka'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - dev
                - qa
                - prod
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            action: keep
            regex: service-discovery

          - source_labels: [__meta_kubernetes_service_name]
            target_label: service

          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace

          - target_label: __metrics_path__
            replacement: /actuator/prometheus

