{{- $active := .Values.deploymentStrategy.active}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-blue
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
    color: blue
spec:
  replicas: {{ if eq $active "blue" }}{{ .Values.global.replicaCount }}{{ else }}0{{ end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      color: blue
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        color: blue
    spec:
      serviceAccountName: {{ .Release.Name }}-{{ .Chart.Name }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        runAsNonRoot: {{ .Values.podSecurityContext.runAsNonRoot }}
        runAsUser: {{ .Values.podSecurityContext.runAsUser }}
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
        seccompProfile:
          type: {{ .Values.podSecurityContext.seccompProfile.type }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.blue.image.repository }}:{{ .Values.blue.image.tag }}"
          securityContext:
            {{- if .Values.containerSecurityContext.enabled }}
            allowPrivilegeEscalation: {{ .Values.containerSecurityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.containerSecurityContext.readOnlyRootFilesystem }}

            capabilities:
              drop:
              {{- range .Values.containerSecurityContext.capabilities.drop }}
                - {{ . }}
              {{- end }}

            seccompProfile:
              type: {{ .Values.containerSecurityContext.seccompProfile.type }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if or .Values.config .Values.secrets }}
          envFrom:
            {{- if .Values.config }}
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-config
            {{- end }}
            {{- if .Values.secrets }}
            - secretRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
            {{- end }}
          {{- end }}