apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{.Values.global.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-{{ .Chart.Name }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        runAsNonRoot: {{ .Values.podSecurityContext.runAsNonRoot }}
        runAsUser: {{ .Values.podSecurityContext.runAsUser }}
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
        seccompProfile:
          type: {{ .Values.podSecurityContext.seccompProfile.type }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          securityContext:
            {{- if .Values.containerSecurityContext.enabled }}
            allowPrivilegeEscalation: {{ .Values.containerSecurityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.containerSecurityContext.readOnlyRootFilesystem }}

            capabilities:
              drop:
              {{- range .Values.containerSecurityContext.capabilities.drop }}
                - {{ . }}
              {{- end }}

            seccompProfile:
              type: {{ .Values.containerSecurityContext.seccompProfile.type }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if .Values.config }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-config
          {{- end }}