apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-stable
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
    version: stable
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.stable.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      version: stable
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: stable
        release: {{ .Release.Name }}
      annotations:
          {{- if .Values.prometheus.enabled }}
          prometheus.io/scrape: "{{ .Values.prometheus.scrape }}"
          prometheus.io/port: "{{ .Values.prometheus.port }}"
          prometheus.io/path: "{{ .Values.prometheus.path }}"
          {{- end }}
    spec:
      serviceAccountName: {{ .Release.Name }}-{{ .Chart.Name }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        runAsNonRoot: {{ .Values.podSecurityContext.runAsNonRoot }}
        runAsUser: {{ .Values.podSecurityContext.runAsUser }}
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
        seccompProfile:
          type: {{ .Values.podSecurityContext.seccompProfile.type }}
      {{- end }}
      initContainers:
        - name: wait-for-dependencies
          image: busybox:1.36
          securityContext:
            {{- if .Values.containerSecurityContext.enabled }}
            allowPrivilegeEscalation: {{ .Values.containerSecurityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.containerSecurityContext.readOnlyRootFilesystem }}

            capabilities:
              drop:
              {{- range .Values.containerSecurityContext.capabilities.drop }}
                - {{ . }}
              {{- end }}

            seccompProfile:
              type: {{ .Values.containerSecurityContext.seccompProfile.type }}
            {{- end }}
          command:
            - sh
            - -c
            - |
              echo "⏳ Waiting for Cloud Config..."
              until wget --spider -q http://{{ .Release.Name }}-cloud-config:9296/actuator/health 2>/dev/null; do
                echo "Cloud Config not ready yet..."
                sleep 5
              done
              echo "✔ Cloud Config is UP!"

              echo "⏳ Waiting for Service Discovery..."
              until wget --spider -q http://{{ .Release.Name }}-service-discovery:8761/actuator/health 2>/dev/null; do
                echo "Service Discovery not ready yet..."
                sleep 5
              done
              echo "✔ Service Discovery is UP!"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.stable.image.repository }}:{{ .Values.stable.image.tag }}"
          imagePullPolicy: {{ .Values.stable.image.imagePullPolicy | default "IfNotPresent" }}
          {{- if .Values.resources }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          securityContext:
            {{- if .Values.containerSecurityContext.enabled }}
            allowPrivilegeEscalation: {{ .Values.containerSecurityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.containerSecurityContext.readOnlyRootFilesystem }}

            capabilities:
              drop:
              {{- range .Values.containerSecurityContext.capabilities.drop }}
                - {{ . }}
              {{- end }}

            seccompProfile:
              type: {{ .Values.containerSecurityContext.seccompProfile.type }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-config