apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-tls
  namespace: {{ .Values.global.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "files/gateway.crt" | b64enc }}
  tls.key: {{ .Files.Get "files/gateway.key" | b64enc }}