{{- if or (eq .Values.global.namespace "stage") (eq .Values.global.namespace "prod") }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db-deployment
  namespace: {{ .Values.global.namespace }}
  labels:
    app: payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "payment_db"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials-payment
              key: DB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials-payment
              key: DB_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials-payment
              key: DB_PASSWORD
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/mysql
          subPath: payment
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: payment-db-pvc
{{- end }}