{{- if eq .Values.global.namespace "qa" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favourite-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgAyuU9LkSJZQ38vnRQqFPA3VRHVJ3dyVEeYAWc0KKJkkXEUg1TIGD9j2FFUYAIWX6DPARmUEG++35mzeVItQvHSxKLAibeA7TTFKmRV1PFpT/ZTlha0IrjDHtackwAHBpdi93iKnATtxelplfxE9HvIKS1QbXNK9L9+Fqd8I2R1AUSGELycfpSaDqsHAv1LGKGAKnObOV+fpIJdaVvfX8n00q69os27ljIKXgjgNXJ6tXgWvnPlldTeCU+08utJVqmCuTMoqr+qqzw7UsxZqT0Vf82xlbFOpFcHuAzJhzSpYSwbnocjQqUgloY32Jz7VD0/sRarRsbJAXfwsj93XBafixfz2xyVF6cxzjmQIBftvtetll6V44zduzyPBJvhamfnzGtGiPY01X+XmUWoFCp2AAeHnZNjbwrx9hENqRsmSmO+jo1mEyb0kF2r1bY7bpSS+EnDf156H6xV2oYpaQMLYjBAyVfMB7QDjtM+/nLrttmueum2idhdnxW0g6GOq/EcqINmXeZ7mr0KyjMn/76Fjj4l8df5Y+bcwLPN0dF0s5vl7ISFeOuNWQEr7jlxABqRBYTt30M/C+JwHzBBKTfozf0IntWHwJYoFi5nAw9g2HgNXcNOmBKdRZbK9X6B++BIrwAW7oXhxAaKu/t7z8b0m92RrywXhogt4NWcuDiBNNv2yMZ2FKTA33e8DE1bu7/7Q7WWBg==
    DB_USER: AgBkth/M+W3WMiEYOLoZMkmc6yztn2Kkn5+R92maLBJHui2zz/0IkBDSwcVw8qxfPPxXHF4Z4pZixIfeV+Vx/dQUX8u0wKknt5gVUH1ee95Rk35zRT7JE0tHhgK1r0I1CMSNsXmMLpqdTtJj2tTs+rtQZliKHqjLRfm0QOaeLgmAnj1RovpCZwsnoOV6GHvILwb7lKNB/6yU1RMeoCsy+XjOziZ7V/2E4sSzZluFa48D+3ocQQmnuyjrpRoc/gUqhG8pKwypUJIauADG0/hdDVWa4+o4A+jcU1nthvQ9SRSGsG94EaLm/VVHohgPmlCgvRaFQNRyif0acKPgB9sJ6PchNRe1/ix6Mg3YopM9rgyG+ixvAWmPDMDIYrpF9akKYkod1biB+Rpzgh6IgPBeLZAsPxcuEoDJDGzVSf5WblBJLM8pDBMitwN8vB+5eNvi8zIoH+ci/mGc/pplGytCGKluewE0EINhOQHrkfd9rJOPaegnFHp94nnZCbU+vVjoXl20r1Vl4EbmZT+NOW8ZlUDqyrf1sc3T9zitMnIuzJP67skpC5X9t3XO6GFRvbp66M0pvxNfxGUZtkt2hIyZcb0Vgy3vELc4T+lmOOufDwUxEkMpbeOLlDz4MKI1SWVbfVCvBfCRHNTt089hqLrFMWq6eFDA8sIUMH7Z8Rn7pDfEAGCIoOtumBAt9T3ut4TrB6eUnlAe
  template:
    metadata:
      creationTimestamp: null
      name: favourite-service-db-credentials
      namespace: qa
    type: Opaque
{{- end }}

