{{- if eq .Values.global.namespace "qa" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgBtK/BCChlqPX3E0Dc3FnXLimJwCFoYPT1vJpAXNEDZNA6NTlu3NQp/iHnvnOse85n97BqqkGRHY/E5RkWtlDXOlWz5rHBwxHf660nXS9TGoOnCVbKBadaNlP60JWI/UDeHUFPShHRbGlmqdT7ip/KPdltaoGkFIoxVcHSyUB7Mbbp9ERHY55ezZKmxjGm3u+1JmP6pB1RRJOemwodbFOiUfo/Qb1XMuENB0jP3lSaL4U1KPCN/ZbDCtzpOjDTpU6Flpr5cXkzVLCLekL88yEo7p2389bJr54OpBIdTM7eKWhr4G/AaOyv+QdVg1Si1Dagd+Ulgo3FSbWRdl+dumG3SjwCO8AYGc/nQfuxskmGUIuzFQgClcNZvlccjz9eFIoqgvHpUG9bJ5NUPwZySvHE1gHbnaNi5QVNB/+JZ8plYplANKsoCnWePZpZu07Km8IZ6+i7FFkLoA5kMkO6n9yDbW4A4zO1OtnhcCPWkEinBnLEKR9yPPNG4gPjhKP7fmEAq1PudXlMyv4DIhrOEPi5AaIFxXIgtFDjpKkVVQAyahrcR2iJIAXg4qykeZS8zWEC0syTeAeZBt6nURkP1f/h7vHvvVV9DHoC9eq6pZts91pcFRo5RwjmCewsQnrFyQfxLJMYayc1xZNOlBMNdyPwTGBXR1jsfnB+dAm9qowNYEfro026Rm3ztnHLB1Vfj2nRNUCIVvw==
    DB_USER: AgCuSDohjNtULOgvLXdAuw7gDxjM5je5+mdof/joyE+kFuFvQeuKmVDIM9ZH4FsfNrVgYtbFMByxgSdWnA0pOyGwY+GbBlj6xvwVYkUQRoCate3WsJ/+rrxNc/NX3lgdn1ns578FicpJTJL4gUsS465f2eP7j2EMmo6XkND6T5c6+d+RjHIPlZUP9rypwmXHEBJv/w2U4O0+YxO54iYaOyWI7UYwB5eHG0ZquAaMJokr+wTeB2ifS1Tko+AzVFJvyYIb8Ph6MXH2sExfHwAjZRYJGfuFei16ceFvdvE2ywY3ckoPJMjH1VS/3XJj83hs6XylO2bXNSR3POD0U0AQ3+1ZDNddhyvXqeB5tzHDMuTmDE4lm7oSvNzuUJQqkTGdHorqkxS5w7mmmTwQhoZDZyWEwqoZ7BqfOSkr/9XF8rVxALGbFH0gx7t/yRRrk8h1HGYnO6DXdk52DOQorhH3wuf2w0mBSWbMQ5VSY5diN+9eNQFpdYqlYZorPIvBFS2QAnrwQWqa/q9J71QZ19XCuDjAC24ANKsF9jjRK/NP7+1qyIw3mY3mQgPSvDnAGPdpo5fynqKew8sgxJBf+6WUCxQmBbSfu36UMmxXD6lajYUl7QC37FDbGtPQ3fK39SHogXMJy2OKY9tf9cOTgoOeQeSaHLfrtmifgc0w357NMwICNG6j/7uPKVTFdisgwwhVjGXurWVa
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: qa
    type: Opaque
{{- end }}

