service:
  type: ClusterIP
  port: 8080
# Configuraci√≥n no sensible
config:
  springZipkinBaseUrl: "http://my-ecommerce-zipkin:9411"
  springConfigImport: "configserver:http://my-ecommerce-cloud-config:9296/"
  eurekaClientRegion: default
  eurekaClientAvailabilityZonesDefault: myzone
  eurekaClientServiceUrlMyZone: "http://my-ecommerce-service-discovery:8761/eureka"
  eurekaClientServiceUrlDefaultZone: "http://my-ecommerce-service-discovery:8761/eureka"
  eurekaInstancePreferIpAddress: "true"

# Ingress
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: gateway.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true

stable:
  image:
    repository: "barcino/api-gateway"
    tag: "feature-deploystrategies"
  replicaCount: 1
  
canary:
  image:
    repository: "barcino/api-gateway"
    tag: "feature-deploystrategies"
  replicaCount: 0

