serviceAccount:
  create: true
  automount: false
  annotations: {}
service:
  type: ClusterIP
  port: 8080
# Configuraci√≥n no sensible
config:
  springZipkinBaseUrl: "http://my-ecommerce-zipkin:9411"
  springConfigImport: "optional:configserver:http://my-ecommerce-cloud-config:9296/"
  eurekaClientRegion: default
  eurekaClientAvailabilityZonesDefault: myzone
  eurekaClientServiceUrlMyZone: "http://my-ecommerce-service-discovery:8761/eureka"
  eurekaClientServiceUrlDefaultZone: "http://my-ecommerce-service-discovery:8761/eureka"
  eurekaInstancePreferIpAddress: "true"

# Ingress
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: gateway.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true

podSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
stable:
  image:
    repository: "barcino/api-gateway"
    tag: "feature-hpa"
  replicaCount: 1
  
canary:
  image:
    repository: "barcino/api-gateway"
    tag: "feature-hpa"
  replicaCount: 0

resources:
  requests:
    cpu: "700m"
    memory: "1500Mi"
  limits:
    cpu: "1000m"
    memory: "1800Mi"

hpa:
  stable:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    cpuAverage: 60
    memoryAverage: 80

  canary:
    enabled: false
prometheus:
  enabled: true
  scrape: "true"
  port: 8080
  path: "/actuator/prometheus"
