replicaCount: 1
image:
  repository: "selimhorri/user-service-ecommerce-boot"
  tag: "0.1.0"
  imagePullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8700

# Configuraci√≥n no sensible
config:
  springProfilesActive: dev
  springZipkinBaseUrl: "http://my-ecommerce-zipkin:9411"
  springConfigImport: "optional:configserver:http://my-ecommerce-cloud-config:9296/"
  eurekaClientServiceUrlDefaultZone: "http://my-ecommerce-service-discovery:8761/eureka/"
  eurekaInstancePreferIpAddress: "true"

database:
  url: jdbc:h2:file:/data/users;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  username: sa
  password: ""
  driverClassName: org.h2.Driver 
  ddlAuto: validate
  flywayEnabled: "true"

persistence:
  enabled: true
  size: 5Gi
  mountPath: /data
  storageClassName: standard
