apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favourite-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgCJeuZvQ1HSV3bfSbP6pZ00TqbSP+lyLr2rTiEMPe2QIG8FUvKJUyXsKiRbe/ItCB5cPaDBvgigEQvKfq9ixIQvffigt94nUs9jVUFKHp0BWJpZmgAkXVY2nEWl8r16nvEcbFcfB4KqGe3PD27E91c5zw2V9YBW5C3l5ZGub2gFqrZa5jg+9wx5tKz4eXq9Qy9ZtvvxL5ssPFYu6d0Ic490RkMbVAgZ7B5uGB+6ljMKF2vvGEsCuxP5+2W1hRh+0iJW9AC0Wf87jODJrbViR1F1k5DSBLDGbNof2/pjclTnW9nUiLM8P0wNR6LZS9EI7vO7YVp1y4vTgJCtdnW7WKkX9TVu/QRba3KBT3QbJhxhfgIRULH9y+byv5hSIkEh6IhjhpmuTQBB27tH9AZviCwAzxcy9HgFgvRTNDOz1Q0usxTCQm4CFmrSDAxSJ+pc4iSH6xCSDuphcrSDoPpWKeh42pyd62VPMJxvpRQOXZ3C7ocptXo1RP2WHvQ5rAvOQsAg9klyXP8aYfCqWmi1Ikf2NdQDwKsu27tlzYQDgAiXUd3hlpD4ilMozf+/1oRHKSfrUaDWw1NdgR+8JoWDY/gWXxRGL/uIstQpC/v1S6CESXA824TKQ3xaTp62U2E0WqFYQTlaIUtL3r478E8F1Jqpn/wUt+N6juT2g6X9GdsYpzO7JCZ9o750x20SbVnUI9sZ7Fg/Pw==
    DB_USER: AgCOyM1KABomPJLgxpGVjNncSRQM/J38mk6+6S9PJZTEL5cSTLyRGh3rAEvWEqiTCoIpmCcElqsjY4y02dfSWrHXJZNIt4J75B+bN0BE6U78vUw58kJ8HMXRBlOuJAf5zj1mtM3C8+2cgv3AOxggPY4x1XxwkK0BYVK9uHRYN6obDeZNhH7rixAIBBtBnkvAPUA06VOoB2RniwyHFWLO6mA7q/H7e9LCm8TMhpnOXVAbY215sEY8qQ4ho+eUKth889BOBE1OPSfKvbAnPCVCcyvzg8Qudlp2WfqEsiHv7her1Q3Svoe5JfvBXwpxCwK6u5/86E0umJRuikQt6QRkc2DgAXE+Rf5HKl35YAAkq+V4T9Sjr7eGhh6BYMMzlmzf6BMgEFoEyNLKYt7/gMOsDSJ+UaoZHCGNaCT1x7AcRm4sDN5/3fdjODskRTXICMoEHhuQ4TpOuA4D9UFh8v5wccZXDJ9CnSm+ber1O0DJm8o5EkhYLiwGNf3fHr4h2etrFE0iVEkvJ13ogFkD1iccfTTykLh7Qlcq76E2os2d6PukYRqYsBJQsO/u45YWgiQNP/HpGBjbbiLc2AKXZBarLmTmD5bfNZRAJ+oTcTaFTJZrI6A2BEifbnOFfl4pgk5eVVP/I5/URJIgg4pffNDIQqOLyph+cKrGXegpyFYe8FEPauHhYWtZwSjsjB41hCxjoOdtbs5N
  template:
    metadata:
      creationTimestamp: null
      name: favourite-service-db-credentials
      namespace: qa
    type: Opaque

