apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favourite-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgBwG3hf9qkQlcgoJ5LOheXu1NN86lr4U79xmC4k2Vw9Fpzgw+btIOHYAxA5MPnrXJJB8vd6kG28xCld+SOHwEYaW6MXlENtUsPZuSoTM9zDiB0srQIqnOXEEwnJWkrRc0EK4F0+vukM0n9gNQfsR5K4tL80bOi2V6snnGfnQQvC9G45yCKiyIOIH/qGeJTrrjiB5s+zV0VEXwho9/nvKwYb26brz1bVgHfrbuuoVFYvMRK/NjwEbdOuzJuUE2mO2RAHVIE0ZqFOdhjAFXqaubrUJ8QMOWxkEzU3YehddD3wI4oxzVKzpxCCUw1j0Ln3JjshCUE8K3FsZywtJSS52dPqxuQNE0Qu1mJMxEeqprezd1iCyAnnfcX79dTL9BwxOVvmoocBFHO+KMWsbn7wotZCSoPLEsUdOePInA3eb2cg6x44qJ0wVROVvXKBrazfipeyJM83V99fiHqiS35gyKeyQOeQ+uCLZ5A2tJyA1/3Q7077XebOvIbo0QztsNgGgIucDmOEG5t2Q7YiSYfTCsqYcPA+ch6kdkf/Ersgm7nQtdzwy3hWk5JL+aQ0nktsYEEzKvfF8Cy7v93ep6wga1TwNOCwvLJBUCBzbpXxFbyc5N264WUZcEqZCW0XCH3GXCXSpYpdq2GqSedO28BJQtegXGuizi70JzPJodGBCnbuKA1SDJhiYBilY8wkuaufsfrkiwWNjg==
    DB_USER: AgB/YNbuHCh9jpjowZXOpzZ6JaftC3Db+Gb1oCl3o4ChiMLoGhssu7ADUNHQrkhVQmocLMOcVUiwdAZ3tXiUHW37DMWA8gQh54EUI5+6OOnHnBjK/ePS4TOweX0di+/M+bibphbklZ9k06r1/ciOqC32FG4Lr5cSl2uYPhRrWFbVhBie4fi5MQS3PXKkZ0G9sSlEeCIX7mbhh0++PiIhpmL/rqh+tfqpcyVhHcMPeJQkkqSN0a19AkQ/RZoae3lAU6nW3b/ZIo7W0xdpPNxuEYjmWH95AfLz8HY8AmZubGM3pINpJ2+IrYPZJcw6gLkVcBc568V1YXRjE4/95eMw85pegAFhcBkVJDIxVK9ctkvR+God+B5KWORZp9m7VfeRPx+zYlqar3mb+sggXpxQu9qWMbVULd202OzumkuQm7VxbkcZZvNKY4CSvGU0iaN2e5WouvsYeFHKj9yrfpXQrbvMKLByihwcNOZaZ0HgNn3D81aayrvFnJB6p3KntarsImm1yh42BvbCUg+GjcHsmj2riexlwf6O8HOm3fYMST0957K0b0x1Uf04pCICG9Z80/Xq6bJOnx306K81KJSRcI+IiMPEXRkgdDjcY4b2MLQ924kj2FxpZ+gSCNdMyWXGZm0Y2aJkcIkCj3LyvbHyCVEhWZC0OtMOmXe7lKjdCkqLVpxwX+xMAkxBJSjCBK06rx7XCRBy
  template:
    metadata:
      creationTimestamp: null
      name: favourite-service-db-credentials
      namespace: qa
    type: Opaque

