apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favourite-service-db-credentials
  namespace: qa
spec:
  encryptedData:

    DB_PASSWORD: AgBjIfXOtN/uBbVU1l1/u3vEGN+XtxXU28tQ+aTlfMH2pv3aphKHW1hLJTWWaORN13DFB614t3sKIx79Hk24PwQi+vQrZCuNCS4xWUxQne9A81bXnpyrIYZjh/aYqKbbyFa/pu5nMc+J8HN9Y4RkhTa68QadqeLyUgqwtMuX8BDxojJ89ptphyXk+5L9veugvisBgqnXzq9vt7P4okClGTXPd7+zQC18NY30bqANCA+p16sTIuLdbpTk65xF149c28F/eFDcvvt8dztjdGK8qu71hVgmHKeENYv4qcwyhrUh5thS4zT8yOCIdSYv64ESdTnBzk4Kn2Fqi7mZjfnIB4o/6ne8arIHaNNg5tz+nIsSGMR1ZJ9/1IznqnhdDhGV6d2Sx5uPwFPPpV957Hm9UDP9V5GVcjlKnvKjOHGYLklRMF+7MVSz+QLpqndFtM3qFlKzvxT3xQcztgUXnm+QPKzkwChHyqBdncL9uq0J5Ulgs3idjnXASoleh0ewLlLzqqAJF0DexU0hs2L9jpy5Ffr8ssZW2eFKGvDtDUQZvLSYjHfHtMRzc252E5K2olT7j9Yb4UTeCGXJJPLnS7X5kKbM+f/+P8uSBXj5w/OoANJ3KWXxxiGfU/s92Zw++hEUfNZXO3ArWvmTmchsE2Hy9n0U+YcEbt/DO+665Jodk0oHHg/l4LD+Aw7r211w1IOAp09+pklVIQ==
    DB_USER: AgAkl2+L7p8X9k5KDOoZ+ItlmS1WR+omECq+Jds0FX8+Gyx3wf3O2tp5jnqa0JjkJsV9d3bAtB7ve4YKTRD95uRAOICA+XMyZR51g36wlZ59i+6nwlyfTqinF/yRr8WHS0PmybD8PHUrc7rlDKDgizLMt21ZaiOQ0R5+Lu7xpv6v0nGbIuhTolNZDNdXKhfi3vNxXcTWihNTokvycyZWy42nrY9CscjSUt6RLPlYRNyuFaZlQOrQLv4O1vUU7rNpmB+JCwLoQU1UD2eghANbxuyGIDxu4nXYiVb+4fCqXswFd+kStnazh83FD/MTtHo/q5sU/rU73hhT9/1VHfHwP0SlFSwnwqcQEbr4xPPe5e/QlnQMwG5Y9/CCFqiXnry1jXH0Bl57r8gLrukcFHNdbOF7etxaSMsAaah0B8oZsECR+jtR741itFZMFMeydsJwhPpjqR5jHW5ySoldyMKYHtuiV68DeFcQioTb9PXjv1nFXU1NksDMypqweWFqvoqs6RV+Idl7f7g8VWueELSKklrsQpTnFUQlZ5czqx/p3bhL6IylsMx2gGPLbCDxgQqGiioSWOl2VPlhKvPFS203Kt2Q2OUrvGDImL1Yp75QmxOsCsxCuMy1alFqgwS0S+qG0yhnh5DWhQHcqTJdv9Qa3dGf6zsnbS5cwt4LXyEnFA2LOsMCFXXLoyfz6xveWPTe2djHmx9o

  template:
    metadata:
      creationTimestamp: null
      name: favourite-service-db-credentials
      namespace: qa
    type: Opaque

