apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favourite-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgAMyzpHPilaFWLrKdKlWIeVOvMOVZz2At8O4jCAbr95I8Cm7IUZym0kfHbY7Qyh4reUh7FVfO1/QBOKkow6OeOlJo/5rmGmW2XJbn77hJgd0j/SWQBEDPpMkxA+0RdzdnZ45MgMVRXoxuLAyBQd4PFs18SGVlt7tEz69p806dZniQ2TtnStlXqK//+9zb8iIKwrO6b7BLtV7wfRuiEmad+QaADtUzlw0jc9EmOv5TIPosYOv1LeLlFcpuSN17SSbtKwyMuVkYGd85xu8Udz+8qRSXl3ZUbCDfPdjiUcnWzix5CV0H0NA9kSIlx1UrXGkr/iSnEyYqs+IQJv+BgaCkuWB9zdEjwMnize0MJoST47uA7xZlD6Xqy5rIu6pOO3MGs1nPnAiEiacNAehDNgYfm0MBeyo/2Uc9uvH47iA+CuCLE3QS99Fgh/HqoyvhoPW2eNBoAxttecfrxCe52GgyEjAURm8fx5lpRxUGIWlE5eD6DcAb64ryWmZiCRpIWOzdKjUppK/yXqecXExBnYhJE2i9vV1OEhFFg/qC9Idb7qKtVuZS05Ku8UmI+bEZkoU+tSI5JdOlz7O2H63kqQvWOpwFe3RvsY146N20RUCpAKwJzJkgJ+vR3xfPCdxl98m4voWo63fvOwMZubDEZA1bfuZCXsxXwIDHlsHUsMfbAOmT4qf3SmE70pV+cFO/C5qpdUlZdi4w==
    DB_USER: AgAj3jBq6/oHxBLghQQcGiqw9RpiahZXLyoDYo5Ebqi2B3h+47DJOoO852lbdvlIrn2xVWMrynPhVfX/GvN4NvqXjBcKa6/9PwaGdM+NiDBO4dIeupiq3rGxKKBkm+LbR4Bku5acai+lMhXIBRTZqC1CSyzFIWF8g9DGcOPlE1VGE4/NJQq5lDs2AotTcGELyDXAhDLgC2Vp6mwQIVlvzyVzb82Dp8x255CSW8LmHLOpBx0XNwAuq8FLvcIbrQG66mDeFyb6Ygkx+S1YihWBceg9O4ox/Nx/4Fx+yIaDYUFTz/eQnx4f3TtO1B4xyodJPwC1HKYydIq7T1atoz7UBwjLibkct9ohPBfBtTbUr5VWA1wrhnda9tlhVb043BCW/q6ze0lJIoawDX3SZU880IWIZuLVJQUViYLbzm4jTr1Cmp8ONMfQPOLOsyLlW4Ft7tfM12RF2rxPFuOQ1suK778lI7mCtONBaE9J/6dvyNw7y+yhnwv9hH/MJIVP6BH7QQ8izNIMWkxxKHB0BhU5AdFg4fzLLMDOFgSGyaBYuzJj9Gfgt45amJavsBlsQZUJ6KqWKK35jJTVuksjC4568f4Hl5Scbr/SifWc4VX7iDMHXUZ6wsOxfT8En6pX2ldijKKTASpCufaXlgzf090mDLhbnjggd8g53H67oSyHbQA4nSbti2CDsS9hlQAFyUOAPrPj714y
  template:
    metadata:
      creationTimestamp: null
      name: favourite-service-db-credentials
      namespace: qa
    type: Opaque

