apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favourite-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgCVJOJw0b+G1wEmwwFEAxxCd+ITx7/6A3Fl+ZT86IQ49OkFsQJzE4AIetEsNRydIppCxLSijUO+Mg1KaJaq2iEnI3OH3OpAoA2+OdhR5jT3Zr3qDon+hu8zSK4b703S/UlXGCvho4V+Ix6lPI2yCbvne8O660jwioaKxmrxIRgW/LpSEbvrwbCK0Yh3VRufi+yo+WymojmsmtFupEpOSvdV1fgd8LuRIRYPePtbfDiwnKnF69RDiFBHvIulAgdO5ow52VjrXtUjB+Fy/MOlys7TogPmz1TnlUWuaxkFcjJa/Ge9VrfpjHDn3Vr3zKR3JLVl0P6k0Y/a6MEiwc1j/1GlS0lEAfKLYoYXUW+A9wlLD/UVDJqSXGR3Mj2FOyKxovDFzqTrIWhepQPpPIhKIb4ZDgdYQFGAWD4LMxQ0dAEG+M/ccX1m+CG2WdU+sAZc0lE9uS8WQ/s+j2Cev/lIA9/4uAbRq8laNi+zyIqAH1Xh4JWKRuEhi67d6EInnRxPNvaeI4ET4+DlnHPeXMdWgflpXcZU/MoFruQOVWuCwLwDkrRXh3nY9jf1UeGM+BvWrfd/hlhyQ+t7WZ0CzzLvwSJwmPEHlzA8+SvOx5IlPHtLljeh4h+wsQYEJYUZBpFPZjzIW//o8LvuNQaYyob73aN/IYwyDMdqRCaFTHzOjaKyejEiD0gmdL3b5lwr5o31HHQ+ayjWpQ==
    DB_USER: AgB+V0q/zTFxljTAKR72AoEkDb9FwIj0Hl0ZZe0QsO6bI6+0paJ5zN7B8xb4cn5DKoWqbaULgNaDzr18794nBrxkrSADwYdL4kWz+YgYnGvJ9kLbQPvO4Vxi/7pabDLfCqgIb1J7DNuAE4VjnKPNKoVJEo+AsJPktl0WTyvxsw9YEa2ewzcLPYs2K0VQ5syRnFfoeJ+lsZrmG+ZJZCdJSxsxKyExxDd5vFZ96EVyqwiBwDXfG5jbr99S4AAQrQsM3mCG2TFC6SMpp12M4mIfqf0GoxF607LUn5n+yRwXuLaSaElkQYDHasVjDdU2Q/8z4QZ7QfYb2XxY9Lmhf4a2CqP36d125iWz+ZwQ/CzeUT+RHMc+PA/Iy+wlPEwE9N6Pjw7e4gZGmqDAUIpAAb/iiJHqknC0i8nuuVLhQlyb5osOmr47iO4DP4OLaCUFAV7JaZ7hv66cUdiBOWtjLJ6biXudaVtzDc5yj+o6Q8tCGB4lkTADA7UkMwBQ3uc0I3Mz1RccpzoW05K9bDOJHpt1jHERbD/OObLa97cxmIRyaBHZKlyehQojZ4ga/aGk6Jg+5XU6W8EOeMS7L15YqXBifPQAsShPbQwJqPL0quLI3VH/i64FVZuTestz47bHSxqlJ8yhjQEW+v8AqZbT7cnXXhrPrjMUb9bF02DZwiQtX6QKQB6dWIicf6OYYFrq+eRksT0abXU5
  template:
    metadata:
      creationTimestamp: null
      name: favourite-service-db-credentials
      namespace: qa
    type: Opaque

