apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favourite-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgBjc3JGmakbeqad3qGvh51T+Cg1b6HnU26oK/eCEIi+2FRkiWBBtt0MBnLLKXVFZ1fHrL0QdxatCHOEEVOFdlHYa9WR7l81ScyUo0WT3gk/zKF4sK+5buXyaQtuysQG7BzNr7QamiHu5PxCg4PqEAoW3VN37LkAzVoHzQBPu0qja7hhU7ttf2i10/MGTk6M6/dkKZ2KlTbAG1rUzIN4S7mFCKl2rAZgkErDVvsJ/s4eBnw98uxD5LWQU6HSJc24i/Ds1XhOffBVvWBkkZ7/JupFfkKlwRzE0SSrd0xd/tkAx3BaI/V9BmqFC30XjDgpkfBzhXp37969VLYVTWs1Eg6bJpNZ0p0HYBMRS5/J6na4GFi3xKAw0Irz3tevIce9DT+/8cjPltCMy0ZIpinIQzbpnCGNZbn0f4eFKHS54bXrxr/OO+9d1Ezfx7bEQDJK8eHP8aMUovnCKHcxMtSe5eTxNRBMLYqV0W5K35AH0W/pi75lsH7Fw98tCouckeuN/nK/bC27u3rFGNQIvfcjHJurVnQuHs0q7JN9q0S7nhdo7enalgFkvUYysDwgNHeDy71G2RFbsuesE+tEISLL4j7DPe4y9HQY8unmO+EyTmLgrtrO3maDl5rOguP+I4SBkwnyFiH4DBSm/TGKxsEmVTCP83BqK2RAkSdHp0+mRcDVi9vsU4ia/ycA6K8J7a6iQGTOQVU10g==
    DB_USER: AgCT9FDL3YHD0pUyk2cjWVZh3fIprdNM7qrvNfxczyS3vSuvdiXIA60WTl56pmw8H4WK2erDNAfAtSL9X3F+bvkJkihydTrD30d1H3JteG71RQfzNIZg+TglemMjGhXw1uhs3EJt4DinxTTHDTeaGvhZ0dL1/MKiHPAZ6dgnVq5yKt5eHc1JYFA5fgAac2/oIj6meaSntigrUFsDTUaUsDpEHrhZ/ipMNvHN17F3jQ/ghlPPR1keNjyLa1ZZLGM0hzKpf6r5oOcQiP1DBcxDqKNQw8Kg77/zns9ZIaNGB6qhqtZzsjEf/O/Huyi3GA3g4FIT4bRCZj5WnKgl4obsDCqfw3xjo4byjIER7A2Prv2kolDPBjxHx0lFOt6l1YhN7VkdhfZdNFFn5bcH6M1ChISItDyyDNXvr7VFTRwV/Bb1e2CE71uBEEcD1gZaIQt9ruk+emnzHNLt7b42F/cTuQucwoE3mNChrzYfz5mxxP3SX7hv6kBmWRJlscSDqEUb1vhzxp6Pfjv8Z5bBtMIAr/LyXB+f4wIoUBpa2RLxdXQ4JHPwd51Fg1vcIHPK3Fo/+Tn+JfbgWadtYZuTuBT5JP3Da7HWdw63D72zvuWR+nHWWPZ5uNzfe4qsvQx2qIemGnvJyVkCK8izzXbmSCbH+BJPFKvIMZwGC7CnEcdTHAbiXzPKEyiq4TQ7UYAfyKCKuGDSp1X2
  template:
    metadata:
      creationTimestamp: null
      name: favourite-service-db-credentials
      namespace: qa
    type: Opaque

