apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favourite-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgDD+Tj7MbwXbDnA3+5TH6RliXdkftmZZV0zhd1VunU/WfmpyXTPgpd1oBbXyGEafzV85uRBDeZyqMm2tPlRBrmyoaMzbt9jh6rCX0FYk+4FAOz9R48mqdEzhRJpx49N1GNIkU3WGXei612tRnTtQlGv/XViV38NANeVq6f227skc1hCAMQ8a8sCwqW+sL8SlC6feIKkOy+YLTi9I7qmrHBpIZO7TbuEXkhvFvXPAzOqxakBNWsnZb5//JrXqqwVfV0Cxd6BCkyNhNwE6AfEPXABvxDkIDf/a9YA5z0f4L3sGNGIIm/CU7aoFD4ZkXodd79WKDFYdwgXNjyS8dVYUHde/NXQMP+E+c1pdIt0G4QzymQJVSk3thGssG62l1LwLm7oThQV0BOUdfaPZUa3V9Trm+rGszPWQDH5ofgmxc5lQyGRLQMhyRGajM9UdJ4Kiby+5xAYUEU+xfAr+qQCJmB2yTDlUDQKUPTfVLJtyLbPT2idgCPVcParuk0pzut4g5Kp5jFTm67+MZLZyyV3S//vr3/nVpL+dNGhyfxCD8Cy1L8tJm78loBTt1W9BJ3S4f8Vq6N37TadAS80nNuSv1qrgcx9XN21YTFfibgTW0e0suK/iZOxlXoUnMZ/41kNIq1qBK0ci2PDhhqH3m1CwcYd71dJvtII8I2Mlid2BpIk1u3pqpCe03XCRhl8FWwf5PEhhP6dKg==
    DB_USER: AgCp2zGxVB0OdArvf/36aeBExne9VCjrZFz/nkCb7Hi4C1Fd0s3qjPRMXa+JqKBqkgUv1Z4lXeECc9btJ9Cbkc6wJdr/tjl+fWYOmNO7+W0MJb1aSG2uxoKWIMh2+ha+YLM7rCcUIeGR/TEQE2KFuylwqaGrIO71dX79tyjI3cEZWSj6X2JOhBIon+dgCmZZiHnfpg4js3XHMF9C/uI9UmMvLyqN+LeHKfnDZ7at0TVQPqGjjeqqVowN8VNePb2dNL+620t0A2WzG++qP0zClMimkN3Tqw3tp7K1qWYsPlX1ZW3SvvTqRwxhQj5/buSWYuzra8phF6i9BFcAGXK5dWqD6BC76gLJEHPoDgZXiSo1B3w9mOYYnT7qnGw3aJt9JnWGXHwZPB/GtRTn1J5op61hnudi6WtHDxHMF5Xol2zBXNH0IYGo6hm7N6FFdz5djEsaZjinN1fCvW7JBCwlX88ez7rkfhwjf8IjKIY28DRR6wuUJinp2PKPQhLwyhN8JPLqmfR0T1/WmTpCACyrMob3+fkAxOj2BHI2b03HIN6VRR6NdIaYan7DSxalitaMtT92/5OYCI+pmtYsmHRXMOvMppQHxJICanBuy5/aVgavbR8rxzdirtLrA95dPa+hUzY/JtuHu7VkfBQm0KHDfTD9VQPJu6OViCEFxCizZqBj9mCRqQwz24O8fYAfyTkIRoOEV5sQ
  template:
    metadata:
      creationTimestamp: null
      name: favourite-service-db-credentials
      namespace: qa
    type: Opaque

