apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgBK9mVS8XFRapb7VoaL3SjW1hxlR3OFwShPL7NPM4WcqPptQTj3rFq5anRtW6KzH2KhU5ACFKW1TCDVmspMcUOGmaP4DYiYY1+METSPy6ObGGnBjW/cQV/uXWOqcU6UC+9hM4cQOLJL0MIk/B6Z+tIpMA9OE0nxWBKca76iRUA8lt+us/ss54t03tEAo9z/rn4GObI96Zth595LwhZSn6YurzBhG/hDu3kgxjcouhPXQ14XqYfYjHMurKi/sOUSAnIrt9X1BgM6EHFRX4sve51VrVcMJnEQZY3tBj+o/xesWK8Esl+NWsurGI5KdmFjlyR1aiAOaK8aPe+XjQ3QcDyhni7f2K0AWmmRPKm6JdVQ/+vIQsIB2p6f66HaDzRVcxNiLVzqwyj86nAsJWmzLkuAut3+lJ2pFAEWxfF99AMRyzwX7nhACZ2JPQ6Dbuvlh4E2xkaREPiewPNbIAw+fDdDNqDaFijS/hXxVOoqI4hjP1ofYBubeNQfshFr2jnALjFy6YeJuW9bu7bl4IgpuYIQvwVvrt3yEI5QxTeU3VykvhAZi4sI7r1qBP/bK9xRsb8M2pyI3Qa4kgdoK0jNKIjVOF6WzDyY1K7IhNboEZhFbMMJXqtkaICNomN9JegkVDqd996ZAynZxc+xp7KmsHwh1B5g5dZ4e9noupJ/huN8dhTqHRNsljcrdXAZh48dZBe3RT8tMA==
    DB_USER: AgBi+QZf6sk+gMR71Hc/yuB2Vu86ZNrj8vHPPA801VWcIl+ogPcV9wSq0JF4J8Yd6NGavj6v28Vtq5zupHl3cgLg06Xn+r++mRPUUsc/Enomouk9/mfhd2b7+0mnlDAaxl8/cW8rdRJcLU3qoB1vmHqtlmVI9HDeaxijq2qIHDBcChZS+dSQcAhAzvmziWkjDWIaRzLeCv4aCzn6+Kw/pOrSsbAs729KtvIP2Z29VJSPBJo8HsDSbgLivEov8L8NMwqJd6IgHUzwc8UAt/eod+Yv2x2KewJHy6xvYQYwsUxy3dk3f4uHFmIny+u45x8gdujpN1oIZRV+R5kAawARQ/aGHDugvpzJlXqr/ci+JTxNSGAsSp7sO9GmrKb8tDguTRC79XeW53dc0aeEa/afus/K2eNUxbz7gvlImKtuk/lldLf0AD5VBuUbe70MkuvRMTWA+sof9aLJ8x3MNeMowB/onYwuvr11NHMTwLLkWl/XJEytYkOAW8UvyW+dmZdBZEV3C58IuHKoZCJPM/aw7aQe76P+btprqBapI0hZrhvneSezh8l/ICpu31CYC0OK6AnHAucl3kFquP4xmbbPwE+VTZVz/mdLdHC4QL8K/7Oda8fV3XO+/kYTtDCj/qxsomHqr0sdCtV3jVeHmmUaBMlJhnYaX7aKnk4RS/a5DKfRBbYYCpXBXMCk65Mjo+VG6fGjxau9
  template:
    metadata:
      creationTimestamp: null
      name: order-service-db-credentials
      namespace: qa
    type: Opaque

