apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgA6bm9zOku0J5rjzVMXlgjJhFrWRWdwwLJJiUVxyTomQEl3J3/qCHd2aiNxs80ZDancF0i+Bn1JdFKhHX+WlQbebR8+gusi5LqfXihoEY7r1fbCGc6fgT9QXdJSwPQbL0N/G6tVhJFq8Yb/YU0t9QvYqXlhTpTZKYslWbHJ+0Bcp+oowd1YzF1SmAgvzVn01jQ+53fDLykHSJJaCX54W71FYHvxxXh1CicwcmRU+2huEUMzCOQIg0Eh6gej37A8GZKboXK5DvKOdmz9v+hPeZgousUoZFecXC5dLOngjOzl8D3a7tV3vkpEu5dP50WGRvL8C9UTN5jSv+zc7cuBdOE/0Ba4kFSFtpsqHpJrNxwdM06hIhU6v/Km5jfVUqL3p59+dI+XiVrRKhXTJeXZY05MQG3lBddK0MeFvs7UelKAgfrk+nX+3FjIAh/dXWPLH2LhDPYBAve4/VWh3hCtwAlK4I7814FQC9MJxB77IuSUvhYtlkJMpgQ/U4P1NTsad+LBk5mtB9ItVY1OCCwnc7eovzhwkruk+vcU1lZ5Qbn8Fun3n7nDSOKIv8/mf9TwjRUN+7J5v4D1QSbyfRStXfrXWp+KYtNdnGtpczkJecOZrVaBcFgEB9fHD12JQw80NpnlPUTCWgazer+Re1ne4bUjr4Q4lpbL/1ttg0onBbG7ZXWRXDOmEm6cGyosb93/z9UJWykL7Q==
    DB_USER: AgAE7hJSIykIXPdI5QuPWQtTb/2T1yndQP4g/5bM3uXuurUif8Eyn0kCz2OuvOyWSaus7FT87SwBC/DaMow+0DImEJem0cAE7VAyjk2qwLDDfuYBQ+xUdpmkpqJcDULT89Z4m3dY5x7DQhdjIAx8JQ9/j0VcMN/Za1718OsezHtSL0kBC1Tcj1iEsdW7uLEGVomGokR08HnE81vfq+c/jXIBN5bQjdbZnx7fh7mAEbQjbNPaKe7jknomwKkmLgEVJzBVTsnz9rNCqXflHc/vwRu3tYqQSRC/0rhTCUD7oA3NUF/+jcTosfPiRigGxV6NEX8s/5ozkpM/uzY7SldqSycIOPJEYTqpfPwlrPkzTtcOCPt/FHN+lUnOFDmrHF6ENz8BX+6WPEAcxyF0btGy+zizZiajDnR2shKDRnHg8+bE813vpoyUrM4lmW6GWgBkvHUvT99jCJaNnlj+Z+dxgvATyyGO8TAjItYbfkDVKsw7e3f4rNWccDovWEtPE9KMu8HgYQdxrG1yygXNY868mFj4I25J2eKc7qAlmgHYdrpjiyiL696/AesfaAZlX+OJtqWfCfK9hlIhmPgCt8V6b/u8T65qOUzpJYEaAxGmFTTQoKRB1RbJ3Cdy9dTIOjNg7o2673CNY4AUTuzzf68KljAObuXKJIUb6+cBqzTNVZjH5W/kwac3Z/5qqtPSpOq0QwRMUj4y
  template:
    metadata:
      creationTimestamp: null
      name: order-service-db-credentials
      namespace: qa
    type: Opaque

