apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgDGuZEI3ThmUKhV7WIE8ziSJ7FfUgkudmbQt8DDhVhKwK3LKRz58ioeUx4RJLlzf1DpJ7Au28bVYKsniT+Ga5muVyM/KCz2KK6FfP7Uy9r3NBd1sAD2Ne2CXetcaAnnEIyo62ZXQXsKylDAMfPAReZbU1cx9gsTTrVNdHRfXM6hIkXit/9tD/f6uqP+2dFXTgbDUiRUsSsViLHDFj4U38vQdmAQFAHvJh+YB35s3wj3f9+fRCKokmNKKZu/D504SBAs8/gKLmRpJj2VPL1WxZl8/4SuJ39hB5liN2EnPZgm8JHZj+P27VDsbsWg8gzLLEf75jUohwbCrhvz96DecP+n+IZvCT2fblI+e8msiwb1hNXRslcrjySzik+LoaqxDmFv8WThTyF/YLfGT14qvX1318fAABUJ75Wlemhwpr7SUDXdW5IWJ297IfC7NvkW8c6vdMHpndt/i1D4J4HSvdkVdw0f+zk2XVDP4cTHRgnPwd7YjjIaIe5JOdvTXFtX2+Nyrw3V/zvLv3/l65Rfk2V67nV726RbotwYdZHmCi5ZAilLCB+KF2uB6y9dJG+4nCnebu0RYkQAOBVqE5AgQtRdHzB4sjg4O8VO+zZF080Lj9omVn6OrUwTiy2+fQziUJ1OX4gJNlybTJBO3aarn3zpYMLpWuLuuxMLPlrPjqdexBEC8qnvZFnAEadM6rbGGD8bj8MZyw==
    DB_USER: AgCen6eeB3ZzPJbIri00IIRiEb1rLokvsH0pz6OEkDKaxtAXZyZ2PN/KtZHtbHYlkSuhM38wo0ZxVNtu64UnShNi6WQuNqOHznCWwLjc/tMKSGXrhen80EokA0OP+pTSW39a3Ekz8JDGFy7Ep2GPcQwniWI7tpo6wWs1FlFlcHxJZhJsKE1YuQUxJkrveiMAB+aulF9eAE+0OIi6lBp1q0krcESt2Qj3OhXiqcW+0RdmfYwrgVrQF6HgTjyovCSUC3fknCr0g9kh09YtGvygnhyOi5MiI5c1LXBWFraykWkpSPDyb590BhmUuDRKwMljpmK29kHx8bsa9vk8cptk7bIe6QFBhpR3nhIuyI8JqINtn+sXmx31sXq1SToMC7X10fDVLuaO2ypmchvwj3Wy0nY5A5NW3vrybCiRZ436nR7ypbxe9lxH5CLL+FoOstkOh5ExR1ANbJG2cvAQqbr21Iyu229QR3Z7nH9kwMrAJtliaiiVQZxYgc4a25KAFkcO6V2RsGTbz+awH7G5a0FoDj+lo/2JLVYanUIdLKBuS5vds9b3HY6Jl5US+P6E/H0/+EFU2q+yf2651eti5mk9gu4lMSIA3DQyfMQFRFzFRdjaGkyKyS4GJ4UvvlZr1dfXYeDCFsu4CNlcPT4hnwefnG6/wxoUnzxZC5dDLLeJ99kBx4v2HcwhF5SMBJIidXOxza6hjoju
  template:
    metadata:
      creationTimestamp: null
      name: order-service-db-credentials
      namespace: qa
    type: Opaque

