apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgCqp4IBCvrnSTgHAbQgH+Hh1bQHMn0B6pUZW2vZwmZbtgJ0emY/nmeCuKu0pjhnu6lvf0p0zpgi//+OLQUGswiPBLRIzwlpT0G+6nLFc05XVlZoOxcZ54Zzu2sc3opfsU1hBFE78w0vInxcQ23S63pRXuC9cr/DxNvhD5uhYytL5GexOmUhETtGTytkoo8Rre97xAFgIaUrF+UA9UejzFTLxHfv6Jacj8ZaHMpdtY8+L78D0hMMiW39rnfElRkYfNpe/5WVwqNNWS2/kP4IhUawjXldBNXf1NOyi6TcZx2INtasTihZM7eYFMTsB7nVcHk9hHqmnBEAUj4ltEB58VDCfMnIuGlRtSwclFww9+TvVJAs91h6h9h/wgPG8OgXibxrAB7QlizuTNmfyivwfxCtNW0OAwaAYOFz4WbKJG5Y7pOu4cQl2zOhM0GiCoeEj1t+johprhj26BFqnQ/FcKjV42zDB8whRC/m21T9XRUi2ffB/96tSSJIyxfKwBg86g0ZtFyFv3fdbyn41rGPQ9fSdjxx+hSVokNxBRyKnd2TTyV79Zh7D469M5buRc4vzegQpIi8+LY9/qM1zDRhGoEflawDHu7sVbSYaAUz2AJsA0ae0LKZ1cEXWncsEh4dJ8QRHCc6g7GEWFArU+iHWhjoLNBrT+lE5jE4rGQouy2au1eHhwBYOCm5PVb4Efd6VpUXg1IDsQ==
    DB_USER: AgBctdeLFkoEp6jGfLUMNJB1aoJ0KgDt4a4+rZpQpCUL5iid+QZWcXeoCN2ixGJqFyO2P+UFfTb1NgWjcOk8ObPKVMEcBm3jKr+kkzVWnloim9F1ThJ0BUOIsOiXJsSb9V2d8KAvkYTjYqflaB7zuetK0CcqxdtCikAyFH0ofTd+MRabSbqTM4d66NN3/YrVfVJqQPrsOSVLATcSjFkoAvbanAM22cEkRJLj1xHAP6ZQuopnr7x94ZUY+NOquUBtXGYAqz+c6eMNVgAF4Z3ImmKaS+C/NFhwJcaxmSe0A1r6EcqGW0aPfH7y8S1c6EBc6IVPP/ULuGla53l+t2gcU56btwnoq+qZJd0X5U7Ux0ajt3EHd7cOB2uBPUXicDUHDXnby1zsJIb7g6qrOHee16xNirEfutiOhkptGMdJ1uxwHJIzN0rsoPdGlmMADbPPJ6YIpj7uk1cRALK3VeoQpn3BdQdC9d6M5KLsGVZPCj0VDIePkW1NRb9qq6AsdC6onYDkHE8gcYAMuTivH900TVccLnXPrmsBnBgLnexlrM/jTOA3XBl9TOH/lwxqpIg0WgEsNzI1cas4GPSQOApW348UG7Ul17Uy/rk8fxif3B1ckJ/uV8kUzhxgEysP7wqtFyfsN3MQwSyMUBpsPovtWOwXDoBiipBIDcZlRL/+Z5DkOgBAB662cgnxiCqamcjuGXywlIPS
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: qa
    type: Opaque

