apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgB2is9CwyaOFJ5FZTsMy65m+31XjERa9O8XVmuio66+zgleWyxC8rnfpdoVhWDHSKYLgFvIbwMpg8G9IMuZtzHWq/L3v4wjM1lIsUfsIKRe1TTh/Jw7vToCYyVsOHZILICKM1PIzG0jCIbyODHXNeIs4YLY9IxvkE6oMumRgMDYjdxXdPtTkRnDYYkN1UkaC84C/duNPAp6H2uE/J7jJ1xVCDYjXmOaw3athH6QJPSiIxiHnEh0I8BWuIKwOGFMm3g7hpC5jKWnTNm5HMJqGXxM7MkcXVGDV4PLItbLQNWnGuGPZxc7KenePKq+v3RCABzTiU+n53e+1A7Wr9ijWWgMer0Dm4UhkRVVImb/x4PGgOhtyLEQl8HJZMNplLhjhBJpkyJ95+dPXfoio3K9oRTHZZAl7ONdrKif+WYROHAzh+lHuXZuEwvvsQIQSHFQelIZbxWvd4FsQmh5Kjk8PM0xmFwvmJVZJ+Z/WCwYZ74+IEAbCux2yhLYdYR/4v6THtJlnx+WM/ZuSH8YkY9VyJxtnuMB2ge2SWfRJ7ikSoSYGtoTk5SX3SpWYMg/p8Cp1tg9Va1oA95W+S26jS2JOQYnu99Jhq5c6MQqgCqZDIz5hwxTHHLUCgWtxVIeMPrbImELtOOT2SGz+bZaSQ8sT2JeRAMErIgNzHRfpPWK8QBZ2YXkfIHQbH1Wd6vBpfxkOtBL7JILwg==
    DB_USER: AgCHGa8gQxry8kgmLGt31BY1bg5x+KmGrLkQy9MwhtAq+KPTmrMLG3RblPMGHKPd0aPonSmhYrHZS0EwhufUsGFreaj224uOxa/3Y13PccwJX6aqiRcnV4KW4f4nIWR9ilYha4Vu0PYSII5yOXh/UUCIWT5cCAavFE31ku9AgLFy3RdgPRdkwK68XZ68T9yXfE8hFe/HpdUArFfjRfGybEYGpKkGy5U7ew5UV265rZ/gn3obwB33E/lUJNH3aiP6DwuYyNYK2UBkL2z+1hmEqz2WWYXgqXsFynGTty/k4YyxWv+2vla3T2QaMhIodUakjMTmjUTXZ4jBla0W050/QCoiaFKPSNWm0Z4dimwom7wIbEW4FyIWb82uyH51Z96N5Ff5xSVvuDvEkfXproXHixOtg57L6pXmCYvUOEyDQclCZvz7GzXqGYfOfBz2kbRKMvDz65iitu2zsYINelCJvEILwboGsZZ5OUZ4bv7b0AKHcaHJjLq7T/BnHVhUOkx00K+ku54GkKgexUIlnussXyaEJrG+s1YLp0c/D4djFWlAhntbsrwtzw/Vt/3QDnEolwssY1vtSYWJwEfJbHMXZk7N8nzblHgWloBFvk8yRWcBrvJ9jTAAOXqrzNI6o6++KbRz3oeYTw4KAVpcQu42FZHoP3b9E8er3QFUPrn/WK0tHSyL56x3+WeoTUD61A4WpXm14E9z
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: qa
    type: Opaque

