apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgBePl/43A0Nt0nBhAbYHGOtgq8BTsSl/zpgyP2roiJgMdWu3FconCoUBKGbCUgh6LOuWwHkRlk19TVx43DNT6KXW+BxSYpzFKYd7ymRmC2OGaKvUPf0PVSQ37mB5azfu9DB3rucfktjv0EvnfVX8BvJ9ou/YluqaIN10swYb7Zqvy0XawKGE453FtV/WJJSC0IJfGn53faUxG7oDSbC0tyFv7gh/9jBYekhTm2ItF37/7XwaXUvqmk56vQAgVaPZEKxi9zSLZiQvybBDHTpmmPEEO3RWZXo5cdBAAb2EwrbWm3jGBVxWRws8Lcjprrdd1Pg2oi9Pqxq0U6adGDxXQ86lbD/xvPxD9hWEFiB4FITIDB/nbupWF0Pf+WQlMH4XQeQsufu3ZlHwLWDRij2VT+QTg58qepm0JlGsl9jtufqnWld98uchtCiFPM7XcYEOMhG9v4aO+A4+C5zQZw4m0MWiet0nFPVKM1uLd7m7RA+JAklk24FaC+MFEm8ForC1YwQUmJyLYSpYw6fQ8cXaX0tM2S9UziH7+0vzuSPyb9/UCz2apdSkP6dzXCOif5cqAfliewoermErqdxO8OoBPOdirZtJqdakR987B43I7Vwnn451bt5Z6zpAwAwjHf7ZP5rC9fh/nID9xQ+XzHbjHjXnYmUntYLoirXzdPB8doz7eDqWIl2FDDHYoUKkv6aE4bsIAJ1ig==
    DB_USER: AgB7TQGeo0EteBRJ0rFlaMoVh99KwQIfbvG1OpW5oqeV/h08Hf1RB59HkmeEi98EQdCAQVN+Alz2fkDWNQBPCuoWNH/lCcW1cInVkRcC+mETuSJFElzbqA9R81wTfRftFPqt3nlzgiH+y/Au5yBvsMTQvSl6Op8OSv5dSasDvzRE3V/vb+rxyFqx83rBujrHc7XXgqRGiwSAJHpygOJPWFuHSetCJ0FNB3US42xqhU5Ljtqu7ZgiIOSANG4atPfFql2WQs+U4XTL6NnKZ66uYlhbq/2d5Y3h8ralVb3k6BLMJDEuKvonAJ8/Lkv7gs2zZhUDHSUp5DwTJmKc/LL2ZykSWhS+aOJl0DAFHVhLPArbSFxtZJX/+IsI7C647SsqJkIOLKAk/jdUeMHbUbXUfh+FO0drDGdcocxzFk65XVAPLxQtGlyZdDlslRtbX8CMXfymeOn7LikEMYm/UagQpnN6vPaxwYdb5bi3ZFhcTLw5ztwHCE+qaOXIR1X8ld4a6nCrefv77oquUN2InZ9N7X44VEqMPjyWXP6TFaN/UjS/CoKFy0Tp0/C8PPFauRp88pUnn8EWCnfHwhgSaYnL0fuX94FJmzAHENQ/C5XFkfM6USC64tR5AC+BSpmNj2FK2xeFfbHFw9KY9Q7CMFJiZz9SxTxPF9zukx9WdkRrxMaXJ5FKm4ncjUoccU3zRFQBMbF8cK50
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: qa
    type: Opaque

