apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgCCBW2FeuTizyyx2fZGatVDwdhZKHQBxAfuivmMA3IF+EXUemN630w50SoJPMQQBqiKijivpgyla/lAPyKhSMJPVrM/WVFhizUgQz6b28hCrqrdNfgj2TU7y+4VIkoc5/wIAFJxRiWWEn13DtaemJp5VgofwRKr3wY+4Lo0PLwdULMvaycD1M+44JUnu8K30nurWt4yq/8fZprvGwCSKzhh711DPh+RT9XHF7NU8YUK4jUmI99rV47mgka4aSFRIFGThpYFoqUN6w2n12gkz2i0nFvWiEzXUqF1yy6E3iwQx1lEPRY8bgwTHNTk5o5bid77QQQ0GXSB4bti98uePM27Ce2J+L9k29ieZq7HS0GBLUoaRYfgxKDvI1FgTSmXFifxYN7lGkBPPwWPeD61bUB6TCBb15bg9OIQeM60M/4DBdEOC7yPdFFq7N6RQWmI/9dMTzKmoi+IN3wWsuHWm8fo5g864q/otih4OJ55jQTqruzsBp/N6YrS9SkAX45QXPDXZlAHGVtVas5S3C/EQvUSPyDzhdee+QJc9Pgzh9CXg5jeVTc9N5GTdlBN+lixq1ZlMYC/jaBfi7b5E2s1LkU3vaqQLN+pbqjwsxvuJYkI/4VYz7gUBKX3WqZytlkemd+10CuWmKfzrhk8Fi/hyL1UsamE56OX2c7vdXtUyjr8A9QSOW5FK8VzRiwU4OjBg0G0tZjzLA==
    DB_USER: AgBiZfYuIC5NnG2WZlzK7MIcKU6yGoBkSosJbqsD+RA+eKeLB8YDRJWUEaV34ub/UdUq1rmnguQ2rbpfQquMIcaidNeqF8wrJF0CFxzCKgSupwMj3sv6fGjhbaf+xuNIW4slYFux5Kcg0mBi+HFmRpKFYgNNztgjgtsQVomEZu/NsYUKs4/cRIqc5iC/zdCUINiQe5IXNC2fN+iNRBgkmlrPCsrD1Oh24ILucp6zsraSA+Bpka3JSnhjsam/xV+pCEt4eewjbs19V0O/iaXd1VyXRfxr0GKhJFzu+RFvEj1Je3kLT42qbXrw/VyvtBt5UIyuo3NZHdTqW9T2oP6MG6vbvfPXWkbYMCbF5tzdQvfBQnEDpoV+bvSO1HWCzdoliFbVZ1rfAIOImHCvzzFMgDebTHey4mi+qmzbDa25EqLCL8GEDVlnYJWsug5nrPOp2WBowAv8G98SLJEI/bNF/eYrvzh2MOn1QJMXsITiywrcXiaYgJCs4pGH68HORQi1j5NIzHVuUu+hdY+/qt2bkrcBJLvA4t9UOdC4NUTyO/xyxhNQe8ThN9RcjsGG3t8ckIoey1d605YVvafU5oGnmCvgQcH8nA/8VOJSUaGy1Ai8gPLmhzy7PlsxUF6W5FZgaOjJB+C7DasmeOnDYwxK9FACPyluOOlsEWjcrb99R5cUFHtEMlMSc1ldjVimVGVU6tiS+pMp
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: qa
    type: Opaque

