apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgB5alW0MsquC4/b6KLJluY6bfsy3k+ID1vTeKvWR0anSoXVEvXN1R3eclT8t/wJR0FB9z9pooQQvN4jvcBPFD1XTki3z3I2LOOw/Z5zOY0D/yOSph6oamm29ul6FCBKvn+09VNISy5KzTZ4U/z7GdKXbk9F7GDSOH5M2lReTZUASD3AaTgokFUPJysRG7r4DBbwzxcEyqjZotoSUzgwMxcRwg+Df4oU91ZYPsywCwElLaeclS39MWnyEY3lD53Yn4TXf4sCmLR2/NjKSieuwPFKwpHBLHUc4bWSvTGSyuha7fbazVWhRi570SAzNGntQhAtfyZLhc7/rNSQMzS5lWB5D0Qn/vbCzBdfjATS+yMcQYg+9zElpxclLwIG+tZK35PUyIYcs2zkTh+N/p2U3+/dD9zKp6Efvx6jfZyM4oErenBLPuYEPkExbmh2oQiaf9Z5k/UlY8JTpYIdfogW6Wf7Xulyup6KP2U8vxupYw9k3ZCCQH8f0quPRheQemBEK3fvNuJNcoVik37Trh3yRaespXHXK+XYDrmliM+UvupwN2GiOfZLnS/U+oazLR7H6Sh96OiNk75ewQF50t573HqoDXgZOWFZNrQGlCh3Z6jkNyCE3XhrmrjvAR9pOjj8KdKYypJIAXZTBO/TlfpPEhvd2SMVfZ2Gv9oJBPgSmpfBr4uVolMLgCmek6DYsXi7wCRhbQIeDg==
    DB_USER: AgBf7HY0tfQJO6JqJru4aJ8vzXD93BOknSE3tLA6WoyzR0feArjiy7sAZ6RuRH9Oelmmr9AO+/aGVOUeT1/CsGUh5jgK50/TMbPaK+C7+3nC9R2Fdg50e3rAqalhQMWWyi3MAGWt9k2WaBbIHJxHuojN2AY7E1SaR6YGjBiXIZ4/cWz/nrxlC340GvAkpfglU7OpNHemVlPIEeFaccdhk9Au+a8jRrfxdcQlSa/xXIuSV+fchlAK24wr7hDp9PsRznq0P2QVPWldccHgc/z2xCG+9WPLaMWGCftIUsvI9TTobqcIoYNiGSU6P3Dgv12C6dKKluVKbA/sxZuCrPI2lELu6ujx8OsQ4t5edmAhqsRAdYlUsN0BRGFKWPG8krKjOQPBzGXn/S5C6I5EA4pXRdkgY7159WmQMWPoi6rQpxXLvEWNa8w6+Cw5wVsmbiOCujZztmiow4iKCP/F9aaHTqklXDDLmyo2HCjjL+XYWEWx5jxrOCq1vVGOYtWasUDkTF3OhFQBj7mQcrXTYvblaVHhEBUC5EB9pOfd4/DC/rkxyM2TIDJaXszM69vzCxLfrGfcexPxiBr0F5zqpkQg0q+8pRjyliniajk2z6CSLN/0epm8PaBKOzZZdQN+rth5i0ij7LwwVPRZtaO9wTP0a2U5C7Zox1tf5t/RE133wzA0p0ywmwExK1jU7AmvTB/qdPgY8mp/
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: qa
    type: Opaque

