apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgANgzfa3V10LUSyGZ7Ldw2N102SpXRxCKpOUsufD46XzpRmSb424InY98PeE+RCiric2NVxn5c2C5KQCTKKPmGCHTJjh3dK8nTlj78nXtxt/V1nJ9WrT2Tlvn86vaPb9QLJzo2KXYFPdpLIeo8lteUbUjsUwrT8p/RD+fSq8GHzzTIFVjOcOeEjcfG7JuCnckYc+lsLW7mc1UvaC/G0Ce7TOQ2KZp8fQWFqSa3NZghbO9qgeoWYnj73pOnrC6U4vcUBk+m9TBSyFgRqNeErG/NNNGLbMBGuD5L5TGIBykd04NzMnXdiAuGCYHojRykyJJpjbk2NIwdTnuiFxBCqGvlLwmwFx2xkDGMI8PUm+oIITqx8I2/ZffCNWIYiFpf2k7yvLdAvg8GO+GS524iTgX/GYjTAXjhgc6uvH/4CIurTkQ7y5SbIvuczbmQllCfMsXX+aFs3J6ydHduUK9MDzPHdKhsPRmDu+kZs9/6XWUUG+Fkfn+rAdBA6qXGbIrsKSx0mrqsQhL6NRN9yqigTFad4ZhzLfubRtBGSHMtFF5V9m6SEjr8cKq02bVuMiAowK74eJsnJI93hfjqToTpNOcJ3D+AEMtflCNk7I2b5eLEubxa0KQ6iKUWPDkJ48hBpPYDrmxRpGxt5VJa58/DkO9dTruU09z0FalMA+cRSxLzKVbvRFwte3iQVKi4ZlLnRwCYg7a/XGA==
    DB_USER: AgAWVDKTmyR5NgToDLvZ+lF0OAyw0iUFpVi+Q6qYRx/9wkN4hVRBAld7CA7Ist0RaeGg5YwMVyDTUoLlitSLf6AG7g5JzGFo/4Ni/FmhBQN7gjoYO35CcUTip+Mj+PfxZqK7rZPMvdS32GVrbtEpQxhV42Wio+pQHg9eTCTTgrpzOewyRcbTe8sJtlcWCrKfm0bweAj/YPWENrcdchf9zMAYx7LKaO1xbDSgPFpKMRVg2ni+lXV850Fht0AJt2WnilmrFR9vKy3MCWHE9wecsEJ0At9EL+h/AReOeaPLZ04YpKKsyf8jUo6p4qCfjxF7fsA+uej6HD6yIirKXPrnyvfB6J6tFSyRwtcFD9US1sut0bz91vFrGMn617z1dwPuhpAsgCzhB0suL0q7pHuvgqcWAqdG7pcJQDmMABwvLMe3xgM561LDVhp0ZiR6t0qwYouZdLal75DAemNdDbbn9zI1lybIbxhOVbA7lr4es2cQvYgd2BZXWBMN+/r8jYnFm7th+BL6McKaje2OUdEToRQxu5Yor3ROCPOFaTOUkXf/hHU4JRftP2wtcml12G34AmzTBK+juCOkq1kspQsikX3M1IZArMX39jyWA8TLbggO87RlLjY8L6cpgGti1G1go67NaQJJftXDcRg5HlYV6J4kY76YpzrMXjmHy9biDbCxZEFAxFHniNaOK0doddz4boH5/mu4
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: qa
    type: Opaque

