apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgBoN+QeXKDjDPyXZ7lsPMWLXmU2uqvdK+xiz9BmMGzdNlrznMExCEUuL9uN2MkZSOH1K7bbFnNSHz66q2GWnQAkYUqY7+MqyR34LuKxoZ0PYLkv/Tv5GtOLLUGAZ8guGQ27le5QRghnGnjePxJAkBcyAjK0sElk1MnS6IGCMZS1TjgY/hJ89oV7oeep2I31vd7f7b8wg394tGf8aPNCy/XkucskB5zhj6UaY5it6Wl35got+/IUWpytEiQq7EGa0RaNq9Whfgk71oSKb0L9Q2GGI4xT5yFkrfx1LFu+DgLKWibYMq/nXWhzZPj6zq6mYX16hga8R0gpa+NntGQ4a7gVhQAQKGoO1A++Xz3YuScrF6yHfA32UZOJz0yMuJaUIjqWb5q8i4UIk70zwA0tt9yxr3yFpIJMhMPsAaAHK9yKQIMZV9Qd8+a/bu+GIou3DXCtIsD1kID39u7Z5efFqtLqZLYT2UmafA1vwmkh0vObsSAz/VMlhGVsdRH1dmljTLLHNO+dynEVcHUwCgi/hHDzxA0vg9n77CTvXP3/i9UtQgGA+9O1x7VRib0xcGcpK2TrMbxyMm/oxWc4vHB67da9T9Sm7W7n8CPzCB8O28Lre/Bw8bNNACAkQilbTiQoKSoWOsxDm24QRXSOyIKWF6wuyamHx8z1kLpzPDsdzarx5+TmMBZAd7o6igZRW8nreOlbSel1BQ==
    DB_USER: AgBr7nwtrbK0uXa82N7t80PRSvrMnoKphLjf1l4e2mTOOXhItRZTTz9MVr/7OqK7L5WzE8Bz3DlO4eIBOvbTY0waRMBDDMBplY9i7Le7L3H18V3XCMF2MkGuWKHmh4A8+UDh8gOv2nh01bawhAF5fUTwSsbA/98xDpUEg8H5jhbyfPZmC4zvuLNihFFGCel+32Tv5JS8YpcOpF88LMXPDBwl1b0Bx1+lavOSRPsBvLcdaNceoVw9BSkyH//7VbZ9TGg3Dw3rhJezepF8UVsBdSW6VvuREDKdBbOprIrZ1iJftctcXokACZ2YMgSFnRFf2EjkZdWDLn8vRvLHMb58XBcYBn3GPP7VEaa4/qcgA08F/pf+Jo+c5diaWkjcMjBOpryu0lWVPdFMGt/4chM46Vricydx7YUIpGSwgacgml0g/VZROhZkmq0XDlK3TBlUnqf55Tu6pynuC6n3QLG95vfeLKXYn+GE/D2vIfxrcGM2+m53YDIZ/Tb3T0YEIfybNZyqqEKpIHbHVTllZHVlB1cglvYQUaYbyAr1qnREVvL+4x7MOH6tB985gt1QaMxYzFxN7f0ZP60ONn+NzgxplwNQYbHCTiy248lm+DwzTF3mOZDFIeOjoVM9fJAkA8VlP4Jqdtk5MI23GKG/BXmAcz44+KgsJXTcqOwlAsIqZg+sUPrY9xRPuAj5cDBBa0cYaymwOJ6O
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: qa
    type: Opaque

