apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgCH1qljUyNSYVwfEEXHomgFb3DsbGeplp5WMKIHvQ+HIFDUtekEHnJbuYIqjDCbhCgEeO546bcGJGGU7e+TPR0+SnrKg1Grll6P6Wfc674wi5G6wDzUfzhOOwqIRDPhHIlxkM/laoURL0gwQlqSSpZ+Gyr7L2qZ+bqJxlgtcjTRWIWDWbH8Vh0Sn41nXKSDlvet1JGi4AWwaQoVobkgEHtMAE3ALB/GP9tHkTo2+d1J6r6ZeufO6xy8QjBwyHFkAe/1jcZ2xcfqp7qTfo/9/raM2LVgAfJ0NNDw+LXCf+1UGtSSl6SgwDT+ab91oNDq4mp2bPAj98jHFb5Rpynqoe9bOOYc87FEtmTHs4O1GAonW/nS36442nW3oejcY3DE1gp5td69ZUr+VPiPH5wkM8MXCFq8mx2q9Gf6JAdA64ylh0Glexu8PnkaAlG0+QSJ4As0g2MmeyJhEMtY+suX09R/DbTtr5sMTdghwXChlWHoKKIs8C9ackrRrYwGuNzao8KAdgTITOMTjGLlzkGLiBHgNitjr6G5RuUQ4cBlNymQ5NZDWSitcbkL6Y8kXjxtc+wvgOfdgAH35RBN32FsTkQ14mG1idjF9FuYmuMAYC3uXKLTvlP5DlWvJwjRpc+5EfLY4UiApcXjam9Uf1jvkZVemOWed48jTPrwxvpmwRlEIw6gvz0A3kAAElWYRXvZGmOx1XSbEQ==
    DB_USER: AgAsf4l0vp02LzPfu1tMlnoLDR9jGLcSVbhyzugBOe+uYN52bZGvHSvlotLvbmtEMcDZ5pJwHhuHZeevJNX5eJLzbp4KfZPzhmL6Px8pGYr97pDHUz3SYngRedB07zclgZQ4FYsqqzAu0Fk1YcTPeb3bt/CeKgtxrj/30TX47OsGP+Yfbl+SKoVc6QxfutgogteLv8xDDqPg4/y9H0lcOf9NsbYp3lVMZZEVQvH2WIir9gMfc19XHp44oL+5UZT6aJuzENMVxslo7A0okQ9tmVjKCN6Ho72U//yg5QogTB8jxvYtZ1vNbEY6zhqzb55E8QQRxi+qm6uNh6v8KkKMMuF2BPqx+6chQnHCK2AHvFZgI4JV+ync3gNoZ2vkOrgSOiTUqvScUbR4mZr4aXCq+LkW1AdXbB+H/KP5ncfq7T3ICN7GfgkO8ghob6XksubGyudAv6uW5dz4+Cfwg4ygz+ZcWMHO3Me3cIgNAZQAhxswWkIXUcuQwRlRqMXrPgqgZxSOXJw3oJcE4T+n0786vKE9J3JLupFkPBYUD3vBtgomsEgDDCmAjQ+Zug9kKqinQWLolAyjemHxNHWNqj8mv1ceYnZFSzwFRHumKQHMPJ1RTEjx4o/BjQ/TFaSgYFEtAzWYF5zxkqNqcEH61fSCyfg7qCUxOzpuHFz+GhQce8VDFj4dRC8WFffWvrUwiI+LZtenRwRd
  template:
    metadata:
      creationTimestamp: null
      name: product-service-db-credentials
      namespace: qa
    type: Opaque

