apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgAxQEVVAniMhIggoqToafE+PiSJ2qAj5sr5kxR6k+KTryAiBg4CwOZRek6HWPjzwi0Svf66RMyxEUl/VYTQt1yRJkdDU3JlttdpKt+20HL9UQpwaGk4aQthMmmFSG6erN5U8UC1Q30MQ5ajMHBHXIrsXnGNAvK1VoQBR8nZpAvPVVbWl8RKYnviFN1lUjamljqyUmpkpc30Q7zbh8RPchqETp22yyFrBFmKyUKRcoEFQKdw4GAdKj7jVyVu0P2GPPZrgpadAsrr5wfMZkAg8azFp2s2Qu3r1GESMErV9Bs9C9sxy0lnSV2IdGTBOiVFHcte1fwX1A9FWKEl0bctmy+BnzgttfOQgyFF/U2WRbMDpwHvUg79o2TaaE2o95hWWJe221t7bpQ0+5D26ed/dQFP4EdrpdsuNa0Gmhk7dfOx+xx9sP7BF5SoMt3J/qlZOroh5rBvOhDbdopDqkggWgMz6c9w7Xd/YFxm0Vucnv8PbwLSmYEJsPv2PPX9DahlYOp9HApr8rIxPU1T6t3DceK21Vor1PBYGZBogjwZ2K4i9ryMYmr1mHFW51YshYDgGh1PA/q/5mv7nDEFWiQpnPvKuk7QqMqfQ7R5acR7Pphd1iVF5RuHJN0PQhUmfFMMDnx5RFa0oSj8V0S6D/L4lnfLRl0FBwiUCmPqkG2GK0OXj5n+3JTHqL2abPqao3t1mnP2X1f4dQ==
    DB_USER: AgAAPPz/EzD3ez5Y0TZMkn2eodzIbPzHukftdM1f8c7P9n91RgLYRYixM/k8l8ZjYQVmmUhxHfF/C8GcHOgeVPcHDJUgtjnEYrLn9HOHBEqa+ib3Tiv0g71TaRRU3+kIgvRF3btMH2WEjonYKxlYDlGhjQh7yCudG+xuwcFYQrA5mxefyyrFTP1iaY3vh1zn7YRFvuiSqeswyxV4TPOgH1OJt/ZIowJdTObMtUq81zHoDW9ZFtyvfd51Aoh1C7F6PvyaI2YzyeqpIchYWVCNqxDEm8+e+XkTmilgP/UUq8ixHbiVpmgoxeetbIan1iyY6dP5iISCssAvolUmFq6IEUlKomqIW78QK3+SP0nAQcdFFR40eNMGlITmHYbcUWGFAAjbVA3cJWJhKLTsiYw76vHOTE8wVvVCcrS2nigDTAeYym1J7yEAFT9/se6G7MhGLpZcKGfxcBgzwmd8VL7rS06Y/G2hxh4k+Ymu96Yy+UsGHJ5JPxRmkD5VluahJgZ0VEVkKouPpa/7ZK4BfpZntoqcS7aUVmCrIYs/96SEKJAHOIwZYC5doPRrowz5aV8D7MT/4YPa5GGZHzrZba8CkztMpTOF4cc2c+xs2PWgCjvy5yCDYnvEvFO3hEvUP50hsF9Bq17BwXiFGSC96bwgl1kmKxN9UIpZbl8EAbzta8qHZnQ2vp8S5I/UzIoJ6EAXJVhgK426
  template:
    metadata:
      creationTimestamp: null
      name: product-service-db-credentials
      namespace: qa
    type: Opaque

