apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgAAzodxXUgXY2BSBkHVVFPyccSlAJ7sXqJLh6IT2Y1wP/gkzlqm4VEg6migA8z6n7McJCcwJpGYkcRWrEecAuunhptOQ+Z5Hnm/pJwjawcwZoBACngaIyMamoYbavYFkaAiAlyyFwKOBYWSEPLRUX9SsvReweginFYXPd++wUFbOUjgdEkmSsaDbXoS9LkMIFFF76VzVEmKMcjzrqb6F+AxoJU0069ApoWBiG2msKuNHG9VU4VJ30Q0wBaLvpxMenqylIicrsue8cxmOSfj1RmU0VHcNxa6KBwbKq2MIywgLN1kISVr5n+/Zkwh1Xo0YdSJOlq49G7BgeAX7j1Vp8oh3NKSvBN4vSHpcXptNfRveH4L1mZ1BoQMaeZRamaEFIT4LYRi3PTF4El5Wt/rBPsJ55rFz6DFo844khe8ciGahxp7vmAbiFM4Oq908tfboAULfOVadwUuwgUTUkarQWM9713T67sWmPiy2mt2Nt1ZjqEzsKyD8e0kjO0zmq/i9x7jaiEEpXgE1+eEZLIl0Q4xv64oaqV8MUGhxaWgaA7AHQjPab+T23FgZF7kvBcizXbwUPxzCHh9/AcFzU0gShjbIiSQhpS0Dsjeo72ra0yz5msGSQloppkCwAO2KxxuWNrrWNXaMzF9bnrQY4LSfWsBy8Vkd8PXE7VWdgQZYE7tGFq0Xv1zN/ZMEJUfFXNOwgpMSg5Gog==
    DB_USER: AgAmVmKm7VNYD9nBs/wtBEkERPxm2jWVX8a2m7IFdm4FvBZagBJkLGzkSYk9sWDKRX9v+BonasC9THWLCLCMls0A0hXmCHNqFpMiVzxGGh37b3AgV86q7K1Ebr2RqYbKBevHLu8ibTd12KqLc3HLZRb8mdP/VMXyfIkW4ib0lCYfJr/tMNfj2MnsslXfF4qL5U1GOEmRAycy/jym8WFSLwaEHTQCQhjWLkDn75hU+q7SGxRgCGLi1YUoCCXcm+YEIwuGEYcMqTGGafUP30ZJ0XR2h7vu9nnbCz81j33HPc4PKtCqYNIORZJJhHU2r3YFpDqWhIeNY71vmqZc7onX1TJCSVsXRMZFGw4pg9rN5NCgFTgvPLq7RB6CULfNQMeKQ4DIAeT/tGZJ6grlPgeL/uszEqTpmjrQdKyx3JH6Y9VKT1kM/DKcsIMbDh6C/+BMUXLJCpQl4NXbzEkxeQAGD0xaHlK2rg4w39F7k6pM+d/Jx5HzLOFIoUu3IM4MBomqmnv/K7xVlRxkmeBV3BjB66JWMCKYU0kBCxvfS0/rUKEbss2JOVA/t4hPQvNkqgiUX+IW1pNh9OtDZ5BK4KC3ENfXwe2K/bMk34BQChi1dh8DeYuKw+7/wrGIXUQz7zepR9XfHoDs6hx092/S4a0CyancV7E8bYpU4ACZxNVOtk6TEn40S65W0XRlpqIIBdfe2snM59ik
  template:
    metadata:
      creationTimestamp: null
      name: product-service-db-credentials
      namespace: qa
    type: Opaque

