apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgAnb2wXK7yxD8TIcrGujzPj7P/CFS6wD4sfzthFKPf5LGq4cpAWYuexzF1141PQmJ8upoJjh7sANEnh44+RPpr1soCffdclGEVnX/fyBaWqi6TE0iK9n9iOO51k390N845W1BK2XSC8kgQHPmHJIrVoYKJsCEhER4hqyDWvbgq3Tr/e5cYRYAJUvcgGnqVmGfOMxyEMrk0ID7CNbV85Mn6xFEkKrU8M5OiEzPv38i3+mBqXXEenPO8BPZU/dAskb4FhYTVnvZ5nXvsQeLgR8md30+uBhL2PLCVCc7MyYOdx5sC9qRoUHlVjXCrDgEYdrdBiz3w99D6vG7A+DbOcowCWPMH6mYGjVIQ8iPh/ep9Ysk4K0RB0LCWmpLXbKvqVyVa8NlhBsKv6FN6qNOptbl0cnRLLl33ZjAaXfVAIq1LH625VZWAX5JkpGaBVjiOIYaMHpyIVOvY8Ta3gDlC7ijIETWoiCO0+b7s6C9eZLhfpoYx3y++4UNVJ5SfOfAt7ykiI+j9vEXEGg1FwrsKAT5TB0CxjHeAB6rQiDP7oOsZGn+Bbu3dqMGZlIpQv0IrUF1EHmzzaA7A1cSwRdhPeYlORdK95MwQ9e+76WEROrYJVTUgd78zptbuGTa2OQ2pg+oYnIbM5anfItgd0yQEqjghHyay+eiAWQtdsIRI+RNFBYgF840nExfNRY3nqjJtoRSffjPefsA==
    DB_USER: AgBJdWKXdVaSyzDfhcFMJYV52bvPWArpr+3a/NG0lOLusqQ+hsI+dS3W9auumrRlgEnWJj/HuoTQXZR6oV5DH8pv1o2IOxb80Y5Y1l2Dxs0/1d8SZtrhE1k4Gxj3/PqyKsRVYGrZuHo+HVe9YYxveQRL/motm0cb59STYudSnlhfCP+rlJEBEEZ60w55aIVLyTkWiWvI8qrAjU/p5w48D9ebNDLVfYmaHl+I1yisIN4EfsDlUdV7XyOMwxEK8aGbSaBN+6yglYm2kE9pC4uo0tl/8fc6aiIUosYwl3EQ/v/fEqO+obbtgxLE6MMlSQ1phzPzWFB3yf4ZfxhC4Uy/XW0lkpKnhtSomfvFQgp3Kp48g8z0ZDOqhnJ7SO4Hk9Chtl4ibo/SBB7C9qV46MWSsAnddDoSW2oXlAU7JE/GipslHiyG3cTeQEqrdXYfm6cBO3m2hs5ki59XgtWmWKMgBdJl2nWrHJ4b88ozhJR2mSxcDvr2R3iMl0DflXoYMHra0n+7AtMI5GEI5/A01bGPoOdT+nyMaeB4yLcbTRtNpqlOKgpKeCU5DMsSwFThvlsVShcm9fFAEJTVTnBFL1Dsvp+SFQB5GQoajAL00oUz5VW6PPuOliVsln4s7voheUDQnm6BBXsZabEPmuvOvfCh9DuFWKVfauXyQ+tegtA86gDik/4MV01feffeeIsrZZ3GoIqo+I3p
  template:
    metadata:
      creationTimestamp: null
      name: product-service-db-credentials
      namespace: qa
    type: Opaque

