apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgASsR5gXEqKD+8yPIj5Q53347+IGF37+axzfPRW01VNN9c2wu7oqk0/0bZFxL+lCy7R+/RPmoDblapXrEUVnWFBkYUdaKVLwLKb9wx8h4jZXjH5uwM1+4vcKthLybTP1eHTtKWdojUulRCpZKZbLu0ctGrLfkkz91qieTPvvO7/tZYOUSnu/4rZn8vxByuUe5p3Ati7hf9e+cS30wFoMOUyxbACoQkxQYpJ4fpc6wtL63sZXWURNdBYr9i5M0hatNhLAWOWuROih0Q6otXk0HE56ld2bUg/DLtbaMpZtYviBjfHMKiAfONrobAYTVb0/cUCUYYj0wJd7D+6/L0rs1NlQc2lY2tnJNBFEhyVG5/B1B+ZHM37k3mV1B0eKRkMNnwcrebctkpCpc1mGXsWi5nNL4+pcm88PUs/TmjNfcSGn2+XWZIB7hq+TOUYeKvi++YDXCZ0mcGzCFG9b67xpzypqn7UY6qt5BzCmdwiExFtfiGhi4ApgdQqf5cbG4NvCOJZfDRCILn1c6qF0JIDpJxMrScSbgoPJf3uD983FzVTPglDR3PWzBhJa8H7eMPpcfdiKAvDFdNWDLSYTFfOlENXe95Z+keCCN0Y99DeifKZKq5OgiGkADK+Csb9Ep3xB1Nh17dwtODAaPbBRgFfjGIHFmLL+L0zeJxdJM/RNueplTJrTNcBf2gth32UTWX7hiJYG+qMjQ==
    DB_USER: AgDJwEyZlTtiwzxLtBjfPOA0TeXmqpftFcLtE8XLhehtJ9/Xq9eY8+uqElyS4w/YlN2+e7yvIraeaGpuDbWXmrKDxkzAqPgWtm1T307VaqmP6XAlVG+lUhDE8kCyCs2J6Xk6sgV9WC/8To4kgdxNMEG1zpU2mdOfKsTPJwIl/85IFcLN9N09Inw8mfSG36veaJVU0gxeJVtAr+4AoWfx9Q2NiuF08KTtOHnJkSIiKUDUsNGstKJJPVbLg3fyaZdL5mACILm+FTi8A9ER15Yjj4We/b5SH+7GegccM2IT3p+lLrlskdY1z1LTb0PkB2mDrXFrqZMh/aVZXk0B9dAeVFVLTW7/Dd3J/pYkxFKInoY7JyoWRYBb5WuksQR6jZnaim9Nb3JGLGSpuxS55apD18VKGXF0/sjksRwjuIFXhRkKAr2T8rLMpJ5TMKNYg4eSAi3e8dSrg8BgJb4/FNpKDXSs3cQEy3J/ubfw+0YNFW7X/gV3bSg0f55cVwtxtjjG3lkQ9ytseXKb6+cHqs9rdQFEm6zI3a2TSTY48OULx8P4BUAShiT3O/tri7Oq8T85Hd2RBZ5y2mV4qkHG+KP4/Ye1Jispm7hL5zSM1R+ehiDTfivKkxs4a+gPIK6H63qZkCJ9H/onm48WAlc8uNw1E/ccXjKKp89MJ0FnUAiBmOO/+mfB7ONHZnc9rGb8W7H53wQXUl9C
  template:
    metadata:
      creationTimestamp: null
      name: product-service-db-credentials
      namespace: qa
    type: Opaque

