apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgBofNJ9NyRa8CUXFrS6H0/3MhspL6GMcCnBjj1B+za3g35QRw5jjDiDAOnziZJ1kKYfgOGLWV4Kou9qYYQ05RWGimE+x2fq2bHmkIYBmZSLb3ksL83eje5rTLaMHAg2cK3MxGB0G9x2Fn+8LzTU03JYHX5AL38vWZ/LBReEMmLFW8ryutcfPUcypVZYPjQLylFTh60AWfYRgKAJn4lCgp3Dd/mtgFRTEAUFsdF7y0LS+m9VINQB+o+vGOaw/gDq2NmF1PRebvIkeniKwfS/w3AHbSkCmx3xXVNjiQBgu60UcSzMDfJ2JpXXgVgY4YsdYWEY5bDPKO/AQDTtaY81wwhtuKWf8mvg9gqaPJlGbz1CLW669KVfSPJfOJiedK8PjtgkF/F448wOokBmRq9q7jGJV/BHaklvjymchv6EkFm58schyrZ1YVC9Fsy91bKjYCaCNcopb6jmFXfnBPM+md6GZj5/PdlJmsE0WQrz9mr37QAqSPa5rpc3deg3caGpAZ+VrVdWx+WdvN1XUMwTI/E2ShEDI8vrLAeydsHHGF04zUsV0BmyTg8PeVS4XtQr8gPbqsc82ma/0h9KRiCLfEvX4KdK93jfFQ2SLmeNPxi5YSTFzg2966Atqknk+x/fQN4oJecFRwlbQE/RPNPH9Ybxlq5mWuZBuSH7ZgzLKqwwIJmc/RDH+I/9sxR2gk9U/ytg5+ZBJQ==
    DB_USER: AgBshJAJ7VSPPbHD7Q6pLV56xHzx+fd9XXbKO2/WXV/Cw/KqB/wr5d3MeUuQ5sNGy84whG7FUBbM38NHqTLlthuKSmB2xtxaQnhHhP7+fWtJD9obuWN8hmmj0BwqvmiGwv93DOkptLUI76N08wTtMqmYb3lLnDpnZqm7I1UWW/YW7h/oohjP8Ovnra8fGmQt9DnXjYmdgSd331gmRTZaswvaURP1FgSI2A2o0IAXG7O6sBk+T055zCKnEA2z4grarRt3zPvC/el5ffZlu5dJeHCqOfqFda54eips56TREtfASLJJlpeRvc6M0srXCHWhcMyiGRSqvAYBMQ2YeW3tu8JQhn62RMSmOeLIdnJ8/aJ2MrmzaTD+JPffBh/ht61+YRkvI0+EKIA/uN9xKjBCRNQrRTTovf95Z+479IxdkQtI8RHDqXfNNwyB2flE83obJujXG0Fg2A05xS0IwmbloZwRlQv+sVOnyHgxuq4SwFQPctH+JpNDRGEW+FriJMSOnQIxX4FeEq6hQz5FbyqVAF0F/OaN5YbxrbZSTDP4Qm480PSVTsw52PsBGOZfwB1dEtt1PbIQrzC+EdwcLvWBWxL/kSSalvatSubaVF9ooOFsciwfoTBJiskEoOHHr0GWSrUlpiJhQ7DNv1A8YrCKD9yXXQ2VWtcKEqEaP4GpjKcAFbzyy1SPH7vSFH3MiYvXy0VkQ87h
  template:
    metadata:
      creationTimestamp: null
      name: product-service-db-credentials
      namespace: qa
    type: Opaque

