apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgCs+6dRrsqFiC9XQoGGniY8FxANGT2nkPhxcKMIXTEqgv0W+6ciihAaJ9ZCxWeQUprRiTD/V885BHRPbmty/IL82S7vK0nmvDeLxLZmehKF6einQ1uoEuGAM0civUb1rWVFqp1dP8iZG/Dc0XGaSUy1GvmiYKGuYU6uJsIB6RATp99sxQ4PHLQ+o+Aw0cXYYTD2a8iz68V3XqvOVS9R12tjRTddBkAx5ls6rDx+1PQayRq/T5AcMlRR1rcGE3G6pYgw2Vn2zJ/D3gX5QUrrmbnAKuO+IABHd01SllWmPpz5+2sCkRWFPXvKStjXidKTRiBfi7LRxPTFNRjmUMyJPZXuXeAnlqQF7eG7zSHho0cxxqfeiutylMecv1hYr1B9qS1Rji4gLuwbvFfdtH0lJ3OFnPgEXMIROicKpVeH85w1JdkpdaerPZ8FGWOyxMV4Z9KVbPGz+bq2ZcMzGIp5XlHLr3le7mtJkhvTUri0gouDKqVbAwnvvfZnSkWH+65G2fbRNRQ7udULW+OB9v5siL5IgLH1Str3xa/R2Bv0cT/VMPoKeWMOYLNvzMS7Z295QHNcuyCQBPF5CgZkY1237Qrwoeqix74Thpaei0SUoTHqAcLZR6e3nFLpy1BLlMhSrFM4pbRjbDHfKuiWOUTn7ZTzX3O7xpjkgb2dUL82HuckZgktS6MWWvEok7yfyAFu19wDIal5WQ==
    DB_USER: AgAPnSY8C40ObTI/z8oq7b6fZ3cMpwnkVwPpAsG1Ngh4xJZrvvAEj6DCyzOY5mVCjoBjk/ZYHpFtD4cJkUPbCGHqLrBIIntsuohGKAXUW5AFtB2alI9tKC2lK2L8TxgwlY0rVEUi0ITez3Ol/fIcvgkoS1YWxDbSeH74+Q0Cczj8zjLkMwoYKEllQKAFYGoFEf22B4BheS2+RxkiFxI6klsHbRXtthxyAvZHUJxeqOZTfSKiQBQeqvJxJyooEknVZ923lkHcTLz9oJeYQMkU3A9Fj/BWrIJyZDjaMoH7uPkYbKfNSxcr59Kd9wtv/Q6Oh7Q+ZXUUCJ9apf9qqvND6u78I5Pw8YRHT8VFUXtMTp1kHth2ru161U0IUxgx96zrs65WEj+dhRzhCkIyBQ9lzHXZItIoSnmiRaefPIYgvEJ6LMHzsr36l59zOL1otcm+NaTiwiuK30B4bnAqclh00s9x3q9gZgtwxvw4ka0bOlNEhFTHLvMaxkRB7Z8qhkxQcs87Lwwfa1VWd9LxkzL8fywCoFqwBBhAD+GFXIxQnsfYlmAXGzpXqW9XQE7i2Dlyf8NcO00oAsHiVMkJIQ+9E9B8jfioAgoAD8lVqXG8+662jj1OwpP4v1E2PbE21szZI0wD7yvkTwJ19E5u6i4I7mYBmxOJJ6bUeeHKmiuKGPd0vRsKruWuO3KQGNR6hu8Td30EIPTG
  template:
    metadata:
      creationTimestamp: null
      name: product-service-db-credentials
      namespace: qa
    type: Opaque

