apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shipping-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgC2kj+2Aa999jUP/VuCb7On3ckI1wxfAWKJTxu+jisgRu6VKoAT+eaC7pOzB4Ckn5TioZKhn4SmdnhFIMM7xB1IGDdvawvsyRNfhHtqasHJCFpTkJJh3Y0QVL/jVKfNhr3QBBjoaXEH40xuNOur608H6ZXSE+Cs56rPUBItwHwYH048ctJruY/LGvPVx+i8c5HTSFRBG5oMCHrzR2Z4qjik2kOQImHh+WqTtBCeIvalw7OKcOz7i+riSlIHQ1XixWeK2rsQ2GUfozFrHcq9oB1/xVv4SlsN9sUh9aRLYUip5nsBckeK8FVOwqlqzulVTf/KoSNPiFF1PwIbgY9ow3iTtazZnII5izcqPKqxaqWXSZoZxENkiTAQhLnaj7ld1MuY/23GmD8OnyjmMh9gui91lq1nHayOAO2zabvrxPkYONgZI8UvX60St8A9zKRs8YhjGRQouTpeVq17jlCJP7rt6RE+pUtCz1RPt/Ga9iJai6rtw0eW+y68LpbB2H96Q4e8bqK1uRbLXAUVThpEN4ZRaANfcWan1XcC5R6MyqmIl/cSYSvyuEKcgKA2/HbWHeoEwfbbdxyo478FoclCeyZhsPU3E3Ph9QuTKLVba3TsU772WZ9A88PKP3AfC9QzqwbgsbjSicmh5fjwE2d0SdX9SfjYnQAdjvXl20v3maceJ1mXBAtHbRVnH3+iMHAWugDR7Mc0/g==
    DB_USER: AgCOUT4nUHDpYayvcPlqKCsNv/nKxdeh7feKzRJUbD42LFCTzmnRqkvlDK9waKlWxolqAFznlGLsRdwdodoGiqEsv2c+J9Wf+l2BL+MFJNIUxezZKwndCzuA8wH4vSQvbUMpDw/hN+jbiOyFZpJlWsgbIFdFKZQdL6v7ag/LQ5wlSYuZMPGgwje269UJgH5p0+DeBtOQ+XqCHy6eUuUppUUN+63HRLRSQkE9rPX9vN8YbmvcIp2/BWKMBpaVPVoL+4dj1bObPmtcgXesH9EvhB8eTNoaifUJ3yIAJu3OCA868VfDr/ZPXSEsdaBENmhP5GIXT2QRfEJYYSDWNf1jOnymNMM6odeCsj/kDy50TMsNd2p3K3tFRU8OlBpY/pXCa4zwJWR9p6j9nmbdejifKSOe1+M4J7Jvvat+KeVVDxpocX6GCDHLVjxT7hrW+ChS5Gw84uHE9BepbqneCGXUXDsa2iufkpqR4xfoiY4c26YonSRD0/0D1EmtNzZDhhEqkmLCMPsb2G3nUosfxqDwaq60+1yAFvBveRhNTskbkNP+z3rNNo/uuVvG79CAaslMO81dgSO4UqnYc7UCDC2IpI1K1lt7VqnwrDbeb1ZllkWDaf1Kz1HozBv6FWJc8F4HEbIWGtBbVkoinljqw/i+OyPEUSMHDvwKhWAq8dVGKIsLjfjJNrJsN4OTG//GVnpZgMQCD3zP
  template:
    metadata:
      creationTimestamp: null
      name: shipping-service-db-credentials
      namespace: qa
    type: Opaque

