apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shipping-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgA9WX3vuHn5blCUw0a/JaUZ9l01p9aNNygiw4u+V0TS5Txyo1nbsKj4se6QUMyHiWoTfovsuUW6DvTqDAz00a/NTXpdmrpLw3vOWsm+t7xDqphBrBfEB6+R7q/KjF/e2RKybxKLWmp/FzaAKRohcRSKsXBrAtEwDwApeAUBSyoi49H6KSMqK5lKP9oaANhN2fi4nYoWtamlHtxq3a+cLj6j/TrzZKatj5Rrr/WxRvCz2dzNcHCmvOtVT9CWvpAcF9zHbaj7+r1O72cBPnzMNqZQzHiIkKgDM/MeWtLHY146YHnit4gIW/U7Bd2NeR+FEHx2yVHb5FM/6OXJYrEHNvb2XxfQfB+9ILKjSIej9R/XhZKT7AHpAgU6fmgpxFCBSHLx+jliBegbuyHOhhF9U6NjJvo2l/c3bKNZtalFXeTutHa0zprzhiNMeDB4rXf6oW5vs1IZPAgsxLh1CZPaIdcM93CEBiylYbZvRen+ZrmePpiXLn7f7AUi9OT4WoWBYiyTH58FTpXCgYCRKazsFLvF9gj4IcFu/JtJB/l+a8pGSZCX3kQAM14Am2fdqAFGmyjTfs1HRF4TmB7cFndtGxiShajKet9XQ6LXGLHW9u5YqDGy9m7+gNukXJHWkiPoVhHbHgzzuzBiF/ZO/X20XBTR95CJwySVWNI4tIJci0kqqDew1TYKcNYviX0QvPvEM43LZJ2udQ==
    DB_USER: AgCJQteJXcaZo0mpUZjyKMGs9I65/kItcQAGzJeUzWaTM09I3zvYgQIa/6ImMb8FwxeFbd5BYGF/5xPh0Pk08i69TylelWt5IuuWaNdXc4CBWZPpeiU0NXBBnzr9HG6vk8URxivsIwhItB9U9FIpCDwlUo3Gk3Oxk+wYl8/b5iJ4bsgKvdEvrh85xGb5J9pgaqC/Zcs5/ma+hJdf6Qrq10mxIFf0n33qfDqiZjdw0P8KRH4TbVRqhWL7yQHxFCYuNNRE8fE8Fhe9aoGBELPqgKsDYxn094tTfEroBeckLPqKsUkii6HAWQ8OyNhRqKfSVOyoZ+sqUkGNHBoot2B6Cg5ALu262KPrXBJujU6hUIdZswNWTgeuL3MUwHo/VNIzeKWDZlFZu3KcF2m2zjamv+BlqlGAf8VC6XYHZiv0yAqw+868yIyDkpeVAhtLDHYOgF+ytpoCX7pvwc9cKIdl6WJpqn22XYOZbheH4Ff29jcjQRN89UcYFo6QflEntokEnswgdzdFa3PdyEf43Y6WdcQhsqkcZpUodEqU2AooLH2bMujJ2cQTht9vhbtmJwHwv5wnklmGGVi2rZ2st/hkbLBjIVHDyWr4YFiipNnk3aIV/K7yi4OLzBh16VNsoZGdWBCpyo1mBItCx3l8++yNLYqR2v2wqwdV75ZfyuWMdiKhFxo//aOW97EaXtd5i+tG3A0WD7+S
  template:
    metadata:
      creationTimestamp: null
      name: shipping-service-db-credentials
      namespace: qa
    type: Opaque

