apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shipping-service-db-credentials
  namespace: qa
spec:
  encryptedData:

    DB_PASSWORD: AgB+Lwx0n7VEYR7aK9Mr0BUpCmsCRYJdYmv41i2VUF9BF6qnCbVW5J7Z8APGYbP+2/lOHd21HBusdI9aBR04OVYiftPT6zTMUIfQLEAvfvN/xmcRlnzImRoIslPfy0Rgppr/x8+vq6SumuOCvA4Dx5O7MMjoAgNpMI36NoGcXnAEnKgdObJiLp8+oqfls9Ya6gRsFPKqjzKHdNdpdFSINYkgz+62B6CUahFlm2zBQW0vWzVem5UpqrZNsiRCl/W07B/4VwTA0PmZ3N6ekESe2cz4msTYNaqOy9I3DOl/li81tJ2UhAq2QMJMi160OCHZNdVF1Q8DWkNty8AH14ZzZjl3zUUrGwxq/qxeKiEvlveo0HekCYvtEdcVuWy2NXmYfovNnJBUFjVM/TB4T9juIwXa+E0iDQ2GBXAMKfKwsJIUuRC6+Cb4qX223BGX/z74k8R8++OGkuu3AxOAgYNkadBQmYQNWp2OFzwfSCClH2lmQduc8CYNwnlXTP2VGe1btrWF3NGIkbJAI4+erpo3SpnT4xtls5pJ6Ve7QHuHmVt2u2sYIYJaS52ZvMUFYWdSvaIQbBj/08sMvMadjefEWoNDcSN1Ow71pG7hhMlJQ6uXQ2eqB7tBngMImLFpaxnyPmDq18UQe79Cr+nBN4w+L5/4t7YG7JbGj7++ouRb226J7zbzO3RAM+eI7YV7d0C6S8jOuiUrQQ==
    DB_USER: AgAIESxc+5gVmjr1v/dzw2w76OByM4KMizZuLYXRrqiub8qtk1KLDhQa5ELeC7whAtc2eUAAWNxlHYxIgGuEUyUnJeWMiPwnUCpo/Ma9TO3IDARNSvcHVWGlpCqeYYIv0fUdR92Ctr8mnTPY6v/Qdq7p68iHLoQ5ASI8qbw9rv4Z9UVAZiMvJBeIPLiR/3JO6GV6ods5pdT07NckJgktwA+Sd9VYgK4M5Di3cnUuRxgTUa9Kj0qaS35p/ymur5oFDIKjgbuaC9ZDIWHK6xXH2dlUQjkHBj6MkO8+Il4nOlqIt8Sq7MljaE+vJyBPocfN12a9dQqtEhdjnqPcUriE/jVOvSa/nt0XSetwZBOVykagPkUmGSJCJR0ZLEkg5LkveFAUGa87JZ7Tcy2Isgxd+RmApIfKrSdUAGkgO3hO/3snyRQS7XEQwoCVZtnosDrEpVtndzV/6y0zJ30abl6JUAl5oCH1C0pKZ0HhtvADqNOeI5bBtaHXGeaJ12idaecrTFJdWjaEsYcdfrywKiHDkl45DwLH7C5oBHvLPC4H2eA1XVR6NaGCpU7tcB5WVN5nzLcEzxVMjRkuZ+zPHD6KYlaX3Q8jFLxTHup+iINQ8x/K1KHTrYGYQy4FQxOveuw1oadJG1hqLbNqNHWNKbSiEetfmnz58rYjw4ieF662ZHx3/67k5og1fYKrqoeXZsNwY21AV7Qg

  template:
    metadata:
      creationTimestamp: null
      name: shipping-service-db-credentials
      namespace: qa
    type: Opaque

