apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shipping-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgCAeFg5z7yZG0jD0x139ZKhp3AwiPhf5CNobThGU7TnHvrQykW6exfL8URTsUCl369knkpRwHIHlB0X9rD1n0bXjPUnJ/HmjyFkT8B1Bytu4eQdGKEfbC+dQPHCRlOYILGIjo4/DdMQIgpIRSHCLQLlZWhYjtCe5+t82O85b1XPJUMBPQUQcFlizUGRuEdZcjFvv9O9dROrvANO3U6M2oVzHLKJCyJdjzZoJ6okx2dQKc/2pzBxbOfvVDqQKKT/tjwM+fX+JKHAdK+1Dxt2jKsCbLnERNtJLZ6X1EuvdrOYjUUqBVsXRwTDDMfjyFwQAdvD2VdvBoSbEhVvemk0eVe387Cmhaf2j2Hyp33Eu37M2sYrTm/+6t3UF6FYOS5+tk6zZ7ly/1mgygWrBMXLYRk+yVTOaXO+b9UwN4yWa498xjqcbDioprdxvzSfBrN5j3N4Pq3hDnPRoSGZzcsVyGXuf76dEaZ9qW8evBsUDQBDXGabTrXxofc9gRYxeYmNZ7JVRKdWTUeg7Fa8KDPwZ8okd8xJazs74ej68rAWtJ6a6m1K+Vl1hegtYQ0m/CssklYqLX0JO0i8WNSveSHp/Rp7GkhSePdkTHkMLw5X8fFztLk2FSm5+VObWFnKVQ3SbSktIwy+OnzsYERqPvOQ4tQrrmNZ8CJi1Hdtq6n5e1r7TP63mm1DFxlxS9TFrfVnDEGA01oFpg==
    DB_USER: AgAyjDZjNUjJgZvrerILf0wbDE4wKEM5EhVWfZxhBtUYsVycSYOquFmOeUjatp/HXGIznLlnx3He4Iuxe3jmIExbYkkAuIAjQDu29OQ7j67zF24DQ9an4q3hPAhsTOPAMf0bm8YFLWwc4Vv1/NQtsEdaPndXTZkFLYkMo3zCuLg0MD/EEJdi+MoSiB9CQTqyXRWle37r6Sar947bWQVoMdaLgieITPnQde2cddRkJGBM2m9QQ1mJdNas6oo0tWQ2NKRWLngueceAcyHh1Yc72JaLTGAKNiJ6Wt3f6uRudFk3JDS3+tcjddvgB0kgIBgfHAawOdwCUIhkHK5EthHEP8l/nLGuQIv3Nz52mTqNAIfxHikTeDJqZjhWNF2Y9fwn7xw86J9ETa2diPaQb7YL2xMNEioQ8DoTBPPNSVPfkHqOnn+K6yh0xdTDPPcylF4E2dh8HESCRMowWhyXN8+r6nsXTp+uYHlhoZphKoAp3sHoxmL0eczG++fVEemL5y/BpxxqpgltXjRzOjU4iY4jnMuzZjXSE44Zp/vDboCtKMgi1v104UDFiZYPbltAo50FwM0ojRpk51IxQozo8bpAnWZKn2QrW7/jkwK/uOD7X5WqAyFaoD49kecksQFCyotjWwSmufMZZiOy1aVrAOFp5//PFYQtZaf+gEXHTDHE74rn7kJGSQNsm93hrY+JCYfy7iW5f3YF
  template:
    metadata:
      creationTimestamp: null
      name: shipping-service-db-credentials
      namespace: qa
    type: Opaque

