apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shipping-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgCEv72AvM+6FtjTxNDaOjOWpxm4gw48U/1v9vHiEk0BjfAkXN9j5cmYzlBD+q+jzbAhEWjixsW9gNiC6mYAictviYOnHKFjFBOt8x4fJ8Ki1y88TincX7u7WxZXCU9Ho4wwpdh4SnPZqAg+EWwztdj2I25WnkcoU/1NC8zTS11w7ftI+gYCRDwhss5Co1WIxP0f2S5DMLPnxk9CNNuV0yw8YACjowtK8AfV//2xBSJTra4F5FbRy4mFzFTdkmp21aOKCkMl9kYds/fmY4CXlMG3NbOnq6FqKxfo8cvGhgwwQ6Wh6kPBcLp10ffpRCpe4fTRxicXOuGbV6SFVCNVyJdjIVWXFs/O1euwRDyY0SmtiySqgoCTGcZP0adzEEW31cjBh1PphvJepr2hBnuItoe7Py84Bgf17M9PKZI2cJGiltj/Nzl5vyO79pkuXZTa72Dg2+qaI3tg5V47YlzBlehZJfBKBgIN0lJMzVrQpqaXReFFVyeD4M9wMyHYQR6H1Jl7q6x3h5FrvfXs2mCKk/PAGfAMpyalnpXGIIRz5xFGj1m4pZivRvN1f48/QLMr2Xqv1nt2/93XImz1z+Dag5ueBUd9e1n10Hz+3PLJ8fjcC8NVH9uhmFxqDItIpWUch/M8rmzrf1JYJC7eriP87EY1pQEtAAF5spN316kFLp+1BDW/s1zaBiom0mxsyj/9Rzf5Wz4q8w==
    DB_USER: AgBLIVcOULtm4fjHE+8OP4supezxf46roIRO706OpVx36nBRc3V6/p0Z+nuW6fpgy+rTiiarHu28SM4OEXG3NSQ5tKy1JgsaqALTPfYavLO8DuC8I1ZBmaMCy56oqTg04oWAnNDyHBLUywwVM6CZBiJlnjVSnWEQ2HXVw/MUzV9GZRnq6RQhWuqUZzU6PDryiTlQQ55RviQoA5DlgRqcbKBvgHQTp8KKCJHYKjU39t8VT+k0UrdzsqexHeXhkUQs4hxtG7p8SQFZlK8k+K60rXI9IKjU7r1taYp3c8F4iu3iiK1uG0ITw2Shkj8titD0ROWz5mTUP6vD8J5H4qRPRCrn0qcrJsHjpkOnRWvlst+DrEZ/655aktR99LA+RzSr2HrTxZ7Thl+/7sxrT6R7uUaVzBrEtGl13mPNtKJZ4hqYPtM3danPEhPhvjxNOOSWZKjlNEMU9rdhBjDLlnfeUBhTmTmfQNKh98MI9u6s2zUWhKtTS0f6ykg7WHedtFgopEo40v2zButyDoahQagnkNLkLhdlerbP9sLh53kXCmqRgYQORBSqRpcJI27CFZQ//6xxiRi5VjDPj9OI3pdffwI9jmj5yJmus1I0kUZCUl1Z1H/ZYllrVJkCRrST7AohBOKUKHMJ6WiV3iigwQDtAA5g0SHoCSuqGelQ4J4QROaa6H2JeCKve8a8a7URCGginA67WIr3
  template:
    metadata:
      creationTimestamp: null
      name: shipping-service-db-credentials
      namespace: qa
    type: Opaque

