apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shipping-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgCsihuTNbOCeX3PFzwkhwT9suQUIS2NFvA4YG0xEaJNxaMUeQu6ZMl9sabWxcEJKJ06oKoObZLN+S3dAnY2SA0TJt6f6o7iRv0cQszgPN2LcllwvnVhw6D26NREghl+edWgQEGwevB4owITQfCLU3PHAComWgWB22Cs6KjwaVTdtSPqo96CPINyyYUdfzilgMLKXm8RhZopgNmgr7umYL9ngAU/FUs6bvHbgOvVnBZ1T03W6zi4F+5ZAoU63zRQEOZbwO54jlvjeI/YGjVUNmmcCu0xtQ5QGADT5zxmafH+hx7GbI4G/PBIRIdGSluvm0QBcgpUzjEyOxFHPHAQKJ1eYszEKRZijzKeuVtsOTO0GHB6Rs+eImecO2PlHn1ZzgxFf0XIc0ibr5BPZDd9ybaA6mJpU2SPA2FfkaIJuRi0BtoghUwTysihWnRPft8v5/ldJyBUxh6ZiuyMrlZ7UobKieKzmAyxlpGaOpxWgcrlrKCOc3f3UXsMFVQyw2sbVnu/XA4JnAqQY4U6CB91BXUU3OyJVPuU2/dnj9MOAYdXZN3xpgWP84C+2Uk1zBzZb2WnjrqYf414ekb3d6rN5lYJVidOSofHIutPKe0NMubh1V/a5CmA4mAMvaz/8ywMhHrnosCsxpZHpNkg0yIUzu2SrQ1dvxLp5pLjorzeiumSAYjHP4L+pGPyG0GNWyQ0DzZ0s3JAjg==
    DB_USER: AgAFgkZoWM/LXFi8Baq3bq7S3fsreptCkMwX51qD8v/Pp+FeAmhHfCdLVuu7g/mMhX42/bUHn226EtpT8xy9wG1rr1PCoTWyG/dhEg6EyaoaYvFBjqW+j76NO+q12SBnE3JVmQz8u7WNwsbLqMHpouoIedyfz9biA5lFiCkpLicT1DLQAjC+QjWlVaT4pFQZmIt33YsXc5vsKtI4KDgnZWtplVySgg+1kxp58pmJXR/j/85pjSvCnvnvB+K2kk/ulQOZmFx3Lzg7LKHmfPoT3Buf9VaDprixkZbBZgDNFl56Ep7NNDnBoYgvhs+f+wt8agaI/b20htqeY14WYzlIR1v8hHMthQ7zeDzr8SIx+7ey4UxmBkPMq0jvV+1WCS67u+2HsWnP4A1iwVRKmlfDDosJHTd/A80PltlZpN1aqEmyV13Sb0UyYWWGPkuUY84FEt4vCmlCRHlyqzh1FP/bbuUkyTqj1nzopJskBiW7o5hOUEgClSqcg+1j6oMPAwugiygsigydvl60BW4qXfxNRNUufLcM551Za7A+Eapq7SXnI4y04j024h2FKAOX9w7nbeAPrjT7wHfdihj5xIqsNmNl5O3LReT7AZz92sTeLO5o+3rVM4H0xai2HG6EQ2kHJXXBmt7h21iI5dTXsdopMIC+/IxnVM9pVqkItYlu28f/J+Ksf3Ba/2jDFSg1eGjzMutLyN9N
  template:
    metadata:
      creationTimestamp: null
      name: shipping-service-db-credentials
      namespace: qa
    type: Opaque

