apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shipping-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgCHPnjdq9bI0w7kf0P7epQHT8I8BqqQTZCuXgIjxjWMXq4TKBRqvgmjRzqICY9nWIQT08KLpsqsT7/04qiAlWK5exXINPMK7VSfJhSd15jaDtN4f1cZOVNJfAz3QVVWgQ7p9NODftRHXqvv3MGYhoKNYiApOL9GUMuOlpvThVol7VpTE5A7GO1WcUD6Nu7VZo/g81ALfXbhg1xzvzpGDPZDPcQrYLT+Zfo3IODq6ncTe9ewkHOiqUqJWrxCaXoSP5DOvgPB9b8jPs2ZH1vlqbq1SmBh8zfg9L2RoZZXbXRT4N9UkWCVZ6y9VIE2nzTo1VYG3JsoymAqYBMniuaysc1yo5eHPevb+ClWsBmmhjswqkYQEKGHbwBugzp8dta69uA+Vx8Gt655Xal4wObE5aIkYkEmpdJpMV92/VKL1CAgejuU5R1ddAXCrIKzzyXPXwS3gQGVrc4QPID7FTvbY06gkT3gH3UaWGJJoo9weJvUayVXzEPUOkLBYq8iTfpzi8GG1F3ayzV5sqQRJp9SkuY+0019j1JXoZQlbFuYoMusab1335Me28FW244+G8u9YEtIGayRmUva9yzA3E2ClbUYeWUjjmKdJ/nBcCh+fTz32c2k/C08EWDt4HCU2stWhXQt0i/3cTJaWPDvats67mgfbWQkt4TjPl324E8CsIghMNiQbTzLENhZz+qdqVsTl3w5ocxpgA==
    DB_USER: AgAK6XOGnEdMyK9PlvfWVNuUzGJgNk5o4gDr00JYQUK4iQtPhT7cnbhdBO0FCHf2mt533UNCJhKx3UoS0x8bNYu6bc0d69yAD4gmbH1Es4kkWtXq9OF3H1d2iXqtU5sCB0DgjGX8dtrT+1OhAGsBaxa741uFCTtbX+tanAM3JTCnktrx1iBCVoSBEOXu9eaT0h49J+X2S522XnNH499BGw4yNJFvf227AOOYOrQHp7OO2zAmyc1W239IcYhLnNpUlC6cP/w/Crx6Nle0IQpT7kTx0zbvLKhH0e+33SBROhNq9u9dgGvNw2KPQRho12lqZ/j5jwCUkKmOIZHKxXGCQcn9vYmdZY5vXN0v5Q3sbqFGs1lVd7FM2aRbtEilA16X4dUy796tbZm9UJOXk9NwKHxiqJ3uZ3NMqy4Oa7+4HrW/hDoshy79ziW5OqEETdOBXYbHRA7OVBxT7h3JU7roazT8k76UvddTEI7L/7cIRtrCB0cefmv1G/bKHVvAz5l7bykaF7Ox+J3MGDw0yS0NGRGxrmzeL8qS+sGkF+MZzh9olfys3+Uw+bpYxZ13/fOQEi9j39M8M0zgl9J1kxo703Umt0eqXGO0hSVWDIFH9FQoBpu5WHRkpgTz7Buue9c7u5CHh5Z4NR+mNrmPFfx/om+v+8VppCW7GRVgzvojEYsvDtSSO9WYlcCxkZuHwQL1mDZq40eO
  template:
    metadata:
      creationTimestamp: null
      name: shipping-service-db-credentials
      namespace: qa
    type: Opaque

