apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgCOH9Ag5ru8b0GNXvlAPc3TihVrHSD6v0eYgX1ji/CGuf5hsrTFaXJyqirW7dOJKF9Nc3ygoDAdBC+2ov1RT5Mv1BywjhlTG0hx3ZjhBizBy3BAB42aPhptPC56r8+HR6ToejO4gBCnnbXH8QbcON7NxNfhja6QhmF1EEMDef3oSBL2+As83JZThwhJlV3Dm3N7iErUxrxNQLP0kyb4MVZvHPMGbROQ77mjWn3+oQOLdxwI7bCvbVQYXdHZGtoyRd1t57QAFV55bwpHNGZfDSBl78sqM5Q3W8A3pGmS3ia7iEjpQAEvUH3VRlz+/iWAhyW6wyWKXhp97noDWbRNFt4+QNB3ZnymelbFBCb52GyZraF2conW7ZqOIrh9ow5W6rKQfBlVx5GH5xgeuFeHljLCbnWdjGwutCaNFxSoGziLYKcffxEYC/bfEunET6uQ2DCuTAalFnnhBIx/KzIfAlpAXG6UZ6beKzyp8zeAfVtxhvab9WAudS8AYiEmH/3TtrK59D2bs6+mSZQDAIAJNuvpLJn69qW9XHFETgEfWuyTnl9eWnRLKH0q0WEBM8ieJ/AFhIDNmG70DBbERLc4TIIt5F7C2bFnoBxCDaoOmCs5CxMqYIilg/1oFIu/DoDS/9Dc6RUJnXPvcGkz2YswQHJmwJqvlKJtTdWqG14zeal2TccyHmB06mOwfxsRRudw3OPcOAYqCw==
    DB_USER: AgBvHOBo254Ix4lwj8MFMCexOrJj0gSZ8jbZCw63v7w4r2WTVUPHI3DM+9YQE9kRc2KqBWHbxVmHuSS6ZZ4SpENK9SQ9gM8wXlzfnxZlR88XfHU60/das/EtefGFQXhkh+46yzBAuXnVV2h/6+8NKTiYHWKFanU+txt5a5Yzby2x9My/fYaTTk0myAz/15b+kUGdzESR1w/NTqs+BFqnhRsUXMjQAlsCuFCRtFLziFa4W4+kytCHLdVBQxtGjge2M8GiVe7ETC3TWk+IiNkSFZIJfkPx2VkJ+LVWBZCVyN3dzxixxmObaQ5jzFNJnjn9TUpi8G7IsXLYckMLIm0vLG0fOGhk15XpDpuau6oJGkIh4ccWlt3ZQyDGqzcza4+70oMttQk4DN09jKFDbe3kxjPzAHjpC+Et+UfDAyxNzCvao2SsZHKmEm5N1fPFv7jbvjsWIcu6k1M8T7CGkWGMls8ziPeXg/aqgY49bpnSs61CWn4S5nXR18Ku9XRy5ShAnw5Mt6WpjOw/aIm6S7M5G/P0zeJtDZUsEw2vNoOyW3DJiMkKkQpgw2TomYGnefDcwJMAroIsxuMGIWoNy+KO6YwibX3aFYyWWNqyyWtRPPtIXJfdQmT0RYyBYovk8sLD5YV25oinjb91dfM4M2PPE1w0pdE2BxRW5LOE8zAxxxi/Bu7iM/ssJfswx67XU0i6+EOhqrVs
  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: qa
    type: Opaque

