apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgB9Wp96bnL/TjQ77dN/WwBrLRrvJJJxkozZ7GKqUpn6D01ODjSgnbd70xPfbuHH7irlclYwVRtwf5C88JNODK6amKNKBfEQkilQR4kLZEHy0+k16F51DsqyjVrp891S8wxKP/Xx4JU/WyiwBs6l8DEQ959FnBAgGxLbexKPIj4bttBNyAZHC+VNeQxozIxQAXOhR6+uGHgDEaU3VApdaq+NGhPgaQj8eXSn/s2w1/oYO6flB2aQOmEsFx/SUcM6ZqnFfEqkTPRoi1z8zN+vTfMk0pzzJVjxwjxr4DChlgeQpG9FidVaulP2VLNTeA/acw34HnN3i0W7ndSWt/0yin43NE9zZIMzqAwo4Da0+lZ+LNXkCMkV2zYmVCXqDWArVfVnaxC4RoeyfhO7P6Q2Nb6e1cZH2ieTXQDxBnm2nvBhlu5JAaUBxqJ+I4XKgESnu+38erWhriy/MiCPewDgiz5K/mE3xI0INP3L3qU13WYjDEDBfQrNbKSz9W4kKZzNTgS46FpxPk/ua18HEjVR2z98j6GBOtXN7qixliTR+RZLbQLZesI5Zm2/8WWyTPIxUeYXFC2/yXjgjRNFAgA61lT2T29Q+s+eClrExs13u/AaPw6Jv0zNkEJzZR/d4hFlYDKOIqDY71upxHGjleuPaTJQx/74X6eZ0NclnYO9ZQ4zyYICIr8KgHu1Op+jfwS+FcdnvgfZuQ==
    DB_USER: AgApYHseoz+/57uuqrMkPwWcl0ygflcTZ5qwjXAt/iDSPXrY4ktqUr4nD3Ypw5EOUv7NBxVAzdp1bH+vxjqiJlZHM3tapZdqf0CTphS1j4Eg8EGAdHOEEeaOgbcjm5xrskw63QfTjF0EAqaM6j77TiYjsobXwkcGWjK7WmtXYgbh4iVhL5lWkgQa2zu2VqWwlBQUvJPQX2d/0cHmocRRch+hiiX/VCBchp5szQ852x7ttESzeA/VoE5W6a12xeDWr5Sk10iU6GvIe6IO8YLImZl5LaUWIRJbcOyDrYG+8Ynp8v8ItLFB873ydfYm6NgrrppYYFZi3fxu9JucNTSlBhsJKwgi5xQCFl+RiimtnGluA5elS3QXuCafN798XxHwPgCxMi9GmVPzvbOyZrm88K0MsFg95j5IaoxiaW0G7tmPPYDxUC0U+GrZSWGitB+LCgH/TnZmkq79eSpRjt0ueRxnkF2k6OFTvHHU/K26XniM3+WpH5pv2jgf/za6CIGbUeyshd3xHipqHJUcW62rtW6LkzFTY8mMhs5hCcm4jSVK7Ckb3pcXbty5Qx1QxjTJzIIu12Mn/Su9deMF/2lgyY6XTH/UpbHry1X9kcDIzqh5y17eA9krtfU/fxpBqwa1mmt5D6C6AfOTGFcUDPfWcTWaUWj1Xa5djgGiT11OA0YKvcnUU0ph75VZ4yZo02BhAjVIoZho
  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: qa
    type: Opaque

