apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgA35MHgVPVUt+cq0inEp9/HxlwJF+l7XefMqKBfXS8fbhaw6rNunUiS40DTXBHcEw+qlAdZqfholOkFexnzeGfjijBonVjtLtKq8KV/OFGIPloZWXcxv1gwKhcPHdQ9ItJFOOfhRpudA9BUI7NMDZyLn9QcOz8XIF7LZ3gIbFVPtpMkYHGwTPOtKTOdjpQQbYGP4PpAeeeW1tL9Ehpm5n4w4a+rQwoWITMvbrNECiU7o0YrPJmOslt5U+HxwyA7ucUtzF8xDE8o2HXV3Zw17VDqlDBpsACBMylQOi7L3VlyL58v7hNSG3nDdXerL79Md7nuTnwJV74+N0eQdc02Sjt4Z47jgSHD7L4bWPnSyR6h5RcA4iiUgfKekE+9JLvo2VqCd3G95NP/GU0xn9a2QxFmU0z9Fat00odh5uzBENijD+8N26Lmzy+DsVDqNmuf3CngOjO2Qg+DQEGYl0U36lSR1GBWnhPpagUe4BsY2WvrdDWiQy+5Xg7gITCd0Y3FAXrq6+CHWQNQPLfUDeP9L7NwOfsJbfuG7+CIQA+dGRrhCycaHrhQrR8tJ8oV1fMdc2F9RIybtdXfveT7IH222P+/3hRx4VcEHRA2EmZFgPNGWUJgImNHBg6COLA3Ej4pTE9+HdokiFVELBziKpaI6c3Av0+415sKgkUVn68J4QODGC5BMz9xM7tkDWWZZabqGXlkRe+Ytg==
    DB_USER: AgAsdwUhFguUdjHTTsqcbWoi3KtBK963JdKX+w/3JEvXW45q49367FGAFMd1EaCijCoGAy4jhXUjG74t/VFcqgZNQ0YmmIkaV5gxtptZAuuJU/Pg/CfBH1r7xA59vBz/GyBVoDz6il72lhowktbv7puvJ7THkG6v0LG3u7vpA0MY7xKvHH53nFQKfrCJmOAYOUqXzqDEaN4PH/kxZPPQ9KJuBHbsx2/NZJ+UxkVRdL8g/g0VuawltKP/cfWJEwn4Am0yFJ0phksICjeoPuAXkLITxJhk049cjXT/QyTquGPPs4rapyCxH/9ZSqg4m3yQvHcRIvLA9WY9xV9jT20Bl9+buZfE9e5+w6NMA6frC/760pyV4INtnZldBGkX+a2WZlOCC0S4Y258dUwjLGS1RsLk0lCZ8zwa+RJRRs5gYXNG8zifWLCdP4SwloHj13gkpnw3Uu2Agxu48EwAhhcLNOStOSjpXrTumxd8uQOOQmSdIBO73pSDP2eG/ITdOe8GDzDx6v4S1wFwUO1jQQe8RD10/ZIsP5gKsRX/7lr6U6St1NI+K+AtvApZtUG41qUg5JNlVF8asmJr0N6sZgetm7LXBUVq5/r2uvPRjxjkM58gFWzWuGcbLFvPcbqJ6mJchh4y+aJN3bniwd0++VYv1X4WTJWduDmC4HX6VHvflU8SN5EYbl2YUqolFPYeqDnwa5gAo3B2
  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: qa
    type: Opaque

