apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgCCcF5b7cue8wZgMqJHE6SuyJCZY63hERLCgvrqla0Y9P0SpqlXQ5wUOl/3Qc+M4f1p42JnUqPE98MUrFMLSZL86CU+y+gRadoyEpF/ljYHh9P4Nt3pgm6u7jkacFRKBHabw88hgUU5lmpunfiNna95rJBM+GfnqR/1JvW8nhdqdyo8RHOTIzHJbnts+p48VL0tx7Y6rtwELAgxu/uqE4CyeLZ1PoUWmuDygL8nzVVLrNIA3LmkNTiWy2iqdWRY4jr3itHTxaowElZPeIlKIiXRqst1gYzKmTHaMIvATgEjXjBRN6AInxAXch4bfhI5oYKYX7V/Q4HNypDX2d1uJmopqbDRySG21U+zC/wIa9pi6/GtpuFHJ35x0zmTu5UMITSrEf/FGo2OkMUXpcCLmYUvQwkWrbm2CDiHkF1PhldJ/qR6Q2CGN3JLxm1Iffn5rpfohk7RtyNpzkh2wBrgfksX0AGsF4LnBleS9a/XUDTf5sCsTeLQv6lnb9lyBqrp5IrCImFjQgkFShZWNa0zOWZjFlOOYqk5RwfPydMJJrBCPcPJdSxfNunuW2P6NKQWMRrtsHLkjXecSGJuX+qhfzg05qL/e9b3wWJRlD58awZi4lmRe9ax225cYjy0LQiZ2Z+FDGylgKyqF+y9dyJ4dKH85iDIMkYXGEWQ92+ql6dq7kBuelPjdGy0UB0pZyUmXDgDeWypAg==
    DB_USER: AgCB6elbBDq6Crd3wxM8PuYNzwOf+YPbsesfmoFdaXp+H7ohbl7ceWceq4jQZxLBBhToY46Dltjg4h6TNmNy5RVRWj+U5yMa7t9yuw+AaewgfGMJNaaffYfS7a/NbCJBdIs4xI6UsB4PRvci9sfa0RwQtxn3XhSxbPsOy72YSRBf70quE/64eyqaLER7jlsUENyvHiq99+DuISqxawzvHrdFCki65cMPrI3rVSXp5KcHIasQZlAO4+RX6AkM0hQQzj4Cq+yRCCZ05JfTDuNlyZclhwnWh3gDGUf10BEa15CXOVHdBdPjcEqDSQXN3GTwTdTrzB50SwmLfMLQEFjCnJfJg8RdECr+TT7PLhtEfXCWtiGPfpZEL+gHPDOaE44WNOkJavyh/uMwpIDjbQXiOQo3MhBoLtiojY1SxAbSmJI8dZZv/TIG+YG2rx7mTcIfN7WWyI25KJQeaWNY5yfpXtLHCn7uNkapdANLJbP4kDSTGTViyb6RJRLxEfnZeB03McdjwjUvJHn9BN+P4obzG2etlQ9at9qJtq1ryBBSVlNAYkniHOnXoGONoRj2Vyxl8/COdv/+n/h51IxKChztHG41tsDh944RCxHf26030/5gp/OI69hHsl/smQHhCpoYUZnzvdRbH/2+5eFkdDi9y9+jGvZJt01XHssTRhQUyxhJoBUSobz9fIZ61iQcHMfGfc3UC7NS
  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: qa
    type: Opaque

