apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgApOIJGudEcFZc1dw1/YKPHWrGoskCuKpuXhua2CMN9UF1OocbE7ZvQVEHeCHxSyi5r0bgjCEFqKQWK1lGi2a1yt4bQD/8br03wphbic8YPeY0Fm8J4IfCR3ydbSqPDNQ8TnkzdF4SqUffcqgGqyFenNdKrDrFFvsZ9XwLq7aclIGtJXPrGfzFJzTlIiGRhahz41fTbymUA2L7FKGGn7GoEBKuWJaSq1wjbTCKca9XPHy7PjhcCRmWdRcEB9/oH+Nulhnak8vj+OazvRjDJb6vyjZSy/xmcbOPTCYR0mQUhQQkjzVGA0b0TyXPtbWYyCOQFFJ0O6PupEvq0rM5HRpI6JFh5VgrE7utsng/RgZepUmt9H/gxFx5mjWi7cn79lrM4Kqm1qrhfrZUPjQlHHMqIUrkDsZvWSIql5hrMTkb5nuMl7pSpIDmOF7cBHA93M9XxQhtLDTHdr6rPvJFsuH371WKNwxaAG1J+iXAmzd52pNl+ZRzg7M0Uf4dCT7PZrfSuMFkmYQzCYPOeWHN/u/KM15FdAKtfF/O6I21h2r4xLQ5Z4hqWVhe7LoKoqQ7lKueDpr4SaaBy+VJeBQDwi5djADYUb/nmqcIDgRjqqMj1lps/UvCi+MLfUWoP8RLsWG9i83ciWwl2gFO9KMQAYVv4KhN6dPVBqCx6XukaHQV5zP2pl5p7UsHgOccU5laMRRdPQK7HIw==
    DB_USER: AgAeGlRetZkwSJS4sqH9x8ysKohGyWS48nseZ4EbYS7ehckr+akLyZTKbt1qqynNj72d5VKsv0UpPRAf6myqXXH6VOWbZZ8u92RrP8NzfJVzFDFzF8ZlEcLA7f3oir8LK0cHxrnNerI/AeEPOMjiSZBiOvbr8HmxTkcAGIZGRE/EmrYW7Me/QLEtOQFKcVH2ssFbRLTeU1ItjQ+a2fS9XPVTbs1eQk9KxOxaD/Q59mnN4XwY/4mamf6sEzoWR5JMHdpfclkASHvOryMdQ4cARNkJ+aoom3brNFihG34Ey5g8wJph31D/0yWkIdPtVIEe80VrQQY0pElrDVcXGNsS4Y9LnL5w5rUQ+VIr6u8aoCS3yuwVQO7IGHcCjFb8Rvsk6MjzxwcZ87g3zpaH/5qwvGCGELXO3xq2ieubjRbkO5hVWBH58m2O0ugfrWP/9ph0/DY/30kcNl1oFIlIyLrGi7qX3G8rbEcN3yPiTb+RfVit7pE/Oj76yVR67SyteIJ11vTYK41FWMTFOAwB6/0RsodlQ5EY0u9L0LH8UFku4Nn1jEsKMl02Yg0S48rX4CFTL33xGXZP8Fds7EdstJuKK+qgu0Ns6eEKPUE7JC6zosZUEsq069QeiU+m+Aues9UbdXpaUd5oSMLLCzd/vz+vyUe3y0VOAjeOdjEoRceHvpgFi9S5Tue6l+BsQ4Rg/w/LBJoSlbNa
  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: qa
    type: Opaque

