apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgAzrihqc4DjULLDt9uj2qq9o4eaHLl1r+pg3dMoJUrlQWyCV2AgLl+/mryPQ3dKnms4SLmAz0Qc/nrgfRblO10R65bFIoQo6eraWxh9D32x+C4Q4Yn4JtAC5lGbaGf5BSfPxFSJ+7QJXawZ68YcwU7V5Wexxmt9nPOVbFckemZseMxhkXxQQeNH5s4SXOYnSFeGMjAKqlqqAM2yNtY6qyVTWcuxyFfkdKPbzdOsNdCiMs7pZMUkV90aJ8S/88N9ZB1FYTzbwAdDIFLP4NAqiODPbT2Ml83qaVT6bIfVO7keuV7l2ssTwGmU7mamTHN2wMq1Hwy2XdHRjie7ik09Ca6dIqPuG/BCyA8y1rKOy/abrwIM9JtzsRS93HWibpuIyXg08n9jsdu+zr6J1hVFa9lMLVwEdlUP6NYyEHytXFV1UctWxrbG7iyPj5WTPk6nOxJwvMCkN2GOaxPSImWLdpEYb6IKn6CAJDoT5mTMXze5y4UuXQYQtKRrnYa6Rc9LswZwkIUbLxFcda5GPg+iA8hVHViW6pLMOYGh6BX0iUuP5SR3FN79eVGPOHza2Gp9IVrsieVUcyCHpcJLz5dEaKF36W/xndsUA5VeqysaX/XBgIWAlfdBlh/4YsOUJepu7lmTP6Kx53Z8tmpi0IB1M0FhL4M5kW+w7KcIPlhvYuE5vEzrWHYaG9pVsZHOBK5TCJH8aTIPkg==
    DB_USER: AgCl8eE/7EGp2sEg+MIVpb2+2Oxh7XkmxkpfLV+x7nlNpdftuIHmaspMJYNVZenA27jSU22/IQ/fKhaMJGr+Uda9iH/QsBaH7jKHVAfLAHCPk43FjuECkPy109R3VZ3HzjBadGwkQJ6aET9d8cW2MKrsYNG/k943THVR9wQDQN6XrvkulKvmT19dMHogLdo4QLJT8Yh2jO2pJHsyNtYe0wcqw84hzfgaUhqfP1xMz6IKhN9BcFufE2748RTp1e/WeFpj9ZgmBmG2m/zSC3/7MAOI0hVkt+bnHiUTWOJMMX5xiMgUhMmrxAcPOT+eGAKrwxoiFyKaQDs3IFzsdB6DInGdd8IsoVc01prgVtlRY/QSq3M2UhUKRvIuAi0niAWAzN2EmzO1pzBwTCq2RP1fb9gRCB2hBdlhPbGBoh6GijHRSlt44R/6BtvVeHZzS0s1V2NogEB1kCd5UswIbYGmqY02sdxyHGA9JIzpVYLZAZu/PFxKhyO8huHyuII1IgjzngsbVIwXPcfsM4tyxcGq/g+dP3eoBdvpfwTpcq4DmKTwvdeeMM1F9rWUnU4fh7ZiritWpPtku7evrlxMeR7LJFm/UtA04HUlajIHYMrchbCJ2aX6auNjCqVBKZSBR2PK7Oi3thzc+bJhUQy9xfdsajUFb/caX41W/1QZ8dBWVSm6lO1DAm7cNo8e1Zn8VKUyHL2f0Yr5
  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: qa
    type: Opaque

