apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: qa
spec:
  encryptedData:
    DB_PASSWORD: AgBncs2MFP25mTuUbaPDxGOcOMMQHC/nw27ogLsyf+mBtff4mX5A2MvCJwdu2cdL0TRxlJa80+mDhcdRJxj0em3iqFy36Y2U4ms1pV2w8xzbwBxKqywYxgUQRWFwxkdSL9vi6KWdOxMoWUX+R0iYNdqBZ7Rw13HVQm68APoaDflbHudUg+hbvDtVOXsxxs0MmKdFjkxWgQOJ2E69ammO/WimeN4aGwoz08KdMnKGSLu7dO8YtVPrz1iWyVeTHgT1lZ+TgmdiU8pI6HVlkT948C+B10/IE2OIs+XNKkTTJ384TLLYx6kowa2JlH3u2cc8kJpjtPgA0BN4i6OjDue44d6K0obpSzeylIydQGEr8nUJlxHdfa9iYOCaOxHaEunCfk9K19UkqY5jXf1lWlmC91sgDgqHCtECVDPLFiUmbLSg/KJkJ/mhy5UgYxp1FQNPIP+ZAcmOgNG559nvggSveuwvxIqDZyNkEhTuaD5RFIu+8RYDJWDTq61thcYcE15/WyNmk4DPGzrYAtThNwaCvym9zLxazAL9qffcPS3KjFbvAfGZjKNmtjnSREy5cTJAc0Z0fkq2G+7sf/gczhOE4DK4WUh5MjLxFaBZZnfRtllbXb+ko3zV2xJeqh7AjHBFTzFiq7k0xhZUbo/YrbQwfxiesXP0ZZtUkjSa/wLLGFxop6mc/gFQZ3J+9JQ5Lmu9dsKzq2+a9A==
    DB_USER: AgADqjQAPDTM3AGZgFKwxGUKdRwj4jeXsPe6WfqzFY1nDf9H4iaA5kZg3OjROd1y5WdHh9SYG0PK6pmJlOW5/LbReeoTEOWtediYbzHuzJ3x+QQuAhC0plXTc68Z0gS9ZHNA2KxcmPtZ2POuMw0i6yb5UWiDGi620CZeMDmwh/mZcoA1axdayEAxMV7ByW2XCC8ApLMZ5RwM2e32i+cBmELj2kICndgCt9uhjZ5WzACbKbEfxUQqhWS0v+JZkHtdA89L8XHaNSfhBDhd09O7e6VwUJk/J45rGkRLk/QNTABFjdBsCIDOM1sPYef/+CJeQF045uzSOcu3fWs1gYD+iLEVkx4laDBBms89vHeFlzSQSsBJhEWKZoVWQRujZLrUUqmyizbCNlewLP60yFxCzA2ABVnHWoOIc5x3Wadxo2UFEtBRpAR/+Quxcf5kZ1HDJ4xCgZlRsp88HHNHIfdLKWiNUIychqAZps4bTP9pWSPjeKBmMOg7Rejbb6u5SIvQZun3nOd2MHLxydKCuIwpN1+y2BUD9/b9/wF8AUas4GGb+qDFmrsRG25GZF9bo6oLhayXEa+1YAM1RMH1x3tZ149W7JW4hHCPNY7w901LuARdDI8lpTMiMMU+fMbcJS/BLCD8NxytzQIaLbFIGWKbzWv2IKfobpv3d51v7OchN7NHStRsOteGthTjm20W2mun7EXgYplb
  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: qa
    type: Opaque

