apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-provisioning
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  datasources.yaml: |
{{ tpl (.Files.Get "provisioning/datasources.yaml") . | indent 4 }}

  dashboard.yaml: |
{{ .Files.Get "provisioning/dashboard.yaml" | indent 4 }}