apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favourite-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgAYJZZg7v4miLbORmuuHXPMAJ0SpbIukJalgkZK4f4CkucahFc3TTAGaZpx/kU0BrZJVvV02eaDvenN1VYl2zfIUNsAPn4cf/v/HcbiTQX78i3dG5plGcmYlI+NzVlGgzZqa4qw7K5pHYW/3iFTco0igyJtWdVS7EBgTFtr/8aa9wd9QNJUSN36JBDBZt7exsPrwVU5yzg2XSxavjkKcT75dcidCCXh2Ron7oE4zc/avQRDG5STsWRQbdRNNqOU+feJE430Cccnyx6KkOEvm3UEpAVwGApdWchyoiN+xrGnVlVpxxG4yOizA20dgV/9HWPF8ngUZ19/CKXIX8YnPZoPZVUy32Mgs8ZC/I22q8UuHNfSGlZxBxbYjJ/jgB4I14JELRMWcy9C8a0HCLaPKXAo2cATfnUWcV82ARVIBe6wHrnhzY68iCDP9t/2Jf7jITpg619FIF9rzsjx5KoRJGBjL1KeG8GVA82vSUui+qZZSaBESafjCxiGFidAz1SsnD9+ca+9uaBQS0ygpv94/hhbyu+pCe8Uk8qeZVUYSFroKJ7a3Zk1YK6DPKM42Pqor0chbSFGSJTlpLw24nmxjoK5+8d6tQ4hQAlZPOHpvj9kAged7iver62cgmLyuV1ybGXiOMMhX9LWk7zsLJJ1Ir1/p0VherV3zwsiWTUnCAHhC6Qq2nib7+d4lDNcOdZWbvapvTpdgQ==
    DB_USER: AgC3xicNRzGVLQzlntwmPIbeBLZMQUPDi+egTxu4fHhmK1gfAr89AqZd4se5/3FXOmzNxl11x6tIl06recl7DYMTK1ZloU6MA3fb/TxozkdiBcbv5cNt41ttgClUW2bi9Em9mOVVN6shZ29DbLylKWtyPrDiwUL2BRwr4UjTpPDyDigYb0zK7kGdOCpgaklfr9NiFE6qq2HP/xvpaG+4G+wO2zMKPLVRucrPS7p1uBkOZ51CMPQlBZeQy4kbUutzdCatvQxQt6Vq2HeerUB1HS+80/KlIOW+KzyQe08GEktsq6wPGQMSZIrnsZyBQa9C1WXt8j10tQYl4OWhT2qQcYyNsToRf0fiBoQyVk5Yqh0ZJrqJg4CBopuhwMWFbUfmJ18IJ4m28XxQowUyn/m5yxkQSkyIdRfc7TFOJhONApPJaibMeAW8B6flSjnhWOFODGcNxoXg0s31myVcfUIv9zbD4zV35C9VQ/hTV9tmZfckckCiXCo7to3k9h5WU3rTLd1nU7EBJqsaLFo+U8B4EjsFpiHr+MuG4CdnK+jGcndP/IzLMJPcaNnjMn6huCDuvS0+00+jnt/uHugdjQSfNG6NhIQ1gQMP7L2ueN00fqY9RB2iD1wMwfzGNtOGCHdLz3XrNcTiRHqrIaPz4ql5xby5NfbngKSHvWmPPOUd7zCbxnv4ix8sTqmID7qKyFcFkNtmtEmc
  template:
    metadata:
      creationTimestamp: null
      name: favourite-service-db-credentials
      namespace: prod
    type: Opaque

