apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favourite-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgBbC3ztWkZyVWlIPNq2zVBNE2UGWxehpKEgKTz9DET+xR7qEy7fCYguzxMcEmAy26lesn7P+M7UAmWbTc8Ye5WwKBW2+prANivzyv+bn6Aph1bMhdzM0iAla0E5cL88xkVE1hrOpvm2AdP6llWR32mh/EetXazhqEl2ADxsG0I7MtQAoqGYCQQ1of/aeEsSEWqn6omAzHs0kO8UhdovXp62TT37aZ3wYMhS1U0mYrdTzNf82SBwedjPLgwOXjelCmOtRpcKI2CMbMWEgoWaO2IFlg98BBr+QOxftY5FHOeABF0kqJFSIJ/M5hrBMcXpV9kwcJN8Dmqyn4xsxPMxUdRZkqby+fxGVR/SinnDFKptW7s2xbOeI/I/IehEVKT/++gy3d+MKlZCqMb45WAGiqyXtJI+GhU2AFd8/jr+NLLRdTrgIoHfA0d9QEqeNV109K/p1xdBp8miNwFz8MKWQIKxN/hLcnMS7JEd2CONlQtzbXQlAUqN3lAhm1PlS7wsIXis+iITC2XODMEJEbiRVWkPJP6ylifs4DqIwJ2oEVedUogrdeXVP530idEmvgqEzPeSi2iaVNNlehHHa1h+naHN7X4t4x2iTqQJ0WHq6nVeERKIHWBN06I4zbVD5xkMw/tET7QWq+ouPv06q+w2D+r3ELLeOqhm8b83gaerhatiwpughuWf3PKL9ngLTjQWEEfIGCzqDQ==
    DB_USER: AgCB3OnLBhSIBeX02BmCrM88231+OuR/xpBkuy49HPGLFyW/w8LoZIeLICbpWOM+PICr7pgpjvyvsuKzXJXqK9AhdnTGp3jaRqb9tE2DW9LzmMPi+rDiRnbzBUt3ZhKbBIhXGNmZ0DA8gTdyvmJzXszdnMuPUDQHkHyHKE7nCOM/P29ruu+AvtrowvI5g5iV7Zxorz+CiVrJVRiK32omoGEFYZceg8gxdseDrkSIL7YRnTPaIaOg0pxWQxYU9t98CVgw4JfQXpa+yvlofHvlPP5L1XbNATh3jtYITX+y+ffCN9bcj0e78V4XqacHWQQ9nIGgxn6OThsZ1JgMNql+xUDmHUBULWq5VQ+iMdHu44uTRefhQB0TuyBSVmyjzXh12ePPi+6VSkCwtxLi1Pqt7sg7CQGj89gwTX/c3TlZFehj9dd0tZbhMIeyH/RcJiKsKDGhrSfVMMZTX7o4+kEQP2HS6K/TGjES8nsK1jZCtSsL1ve7CdBfnz/DwQLNRn/arW5fimEiRYCqMOlAkZDwDZBVyo4sVlKA26j+Tnpf2fqn8DApP+O72SfS1+tPXhP7MwlX7RZLxmRHJFT4BH7A9B7kKKDU5Kb0iseJFy28rd6GVlfkegWRx4vu69MEYNtBlEY0mIyFJP5ba2ilbVp/+E6Z8/Kj1sh8+/sPaa9ynrU4BxzOcPE8rcploBRmeeRepBhAXXK+
  template:
    metadata:
      creationTimestamp: null
      name: favourite-service-db-credentials
      namespace: prod
    type: Opaque

