apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favourite-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgCBOYMriXt4s7XcvRms35j6pTti3DXCTfL+ni4GqKln2foUjYzAoZJmnALOf5kQmhexxvP3h2v6NPuZMWf1HaVzsdijea84vLr6aTmr3cBVHITsrMM+iR4FXRbZMe0mBOMvfioarMyMSexYRmuoRhIxeqJUgdRbINVkO7UgSS9wRK1OjXLqE4lh/LVabEx/2UTfF16ETcQ7FXTv3Up3in51SLw4dAbW0aTYOvb0/S8D5IE2WcXmrPcKSMLGTEjhYQv3NcfdhwnRuUTKYxq/BwEqLFyiNMW6qtEjd8cOUl5M3ZoDUxfanp3/kOAimLDepp9+Egy1yURCq1Om04TJnTK+18c4Ym76Q8CrpjgU/qeR82PGgAuflO4s3IJ0imjIzNYeL9cA8Dut6eRzJ1gUOKjpBbqMHx/WO2z5sXZGbVowFz9MbTrXLjCOkcsSf9Efqblq565Sg5lCVQ1J4/OG4V9ueGhN3cNA+IDV/V51Gn155TtTEKDSeqBLGUeiU5okRDJ5aAM3yJLfOMMyoLoFIvqyI7Y02qY/OwEaNfwQko9JXx//8Kr7g1msG9LIr7/4cLpzjLhA3n82Q6w92lMbBoOwQ/ep9VS4cFqJ7mY309+O99AEdatxc7GuH8vlQx/Yh+m1oTQLVsyFCaIhEb/UH5zB0b/39ASRcugZ6DKySQD1Cbaj9GQ2Po6cZFCL5Pk1LloCfhmyrQ==
    DB_USER: AgBXh6m8sSY7IF88zQO5LmzzA5PEVUDilF9nGBOzqqWsmqsFUw4MGSwhNBmRuYokgLK8wfpkSNttZqKIaGZj8BzhYyfv0hFlEqEnPkScCIC59krlP3LsTfUN5A7w1IywerkJrLvkLvWYJIi62UY2o2fCfGcLclMsFFnmA2qZJdE3bFW8B1tfykwhXnZxayEUUjMgL431WRWngErkCooqECP1kl0YTyEptlx9bSEp78WvPB7afHGMN596J0Q99ah69fehP6ejRxnc9FiGxgNnBSd//RsV2j1It3t9j6K7O2rARPXiWTbr1VSWVFtljYKL15iR2zN3lFFHF6u9oj9FLVa1rVCsrR3xrGkLmgjB5zi/F2awsCmfYDLYsEKS/OJpRG+7zWSVV/fR5JA7giOyupVdI4dnQ6beebmMd0Xvv5k4aVqEYkfDJ8IBNe71/hu/lvj5UWQ9zDgkGaBwzr8z0bI+qPLSWQQycJzA7JE0uxq/F7wxHiTrdajH/b653U1RI9hJSbk66xfGa/S3k2XmLyeXmQL8SpnLSPe51C++BRriPvOgVyDmpyTLPxAbIZuGxxbeL+bySwO4g//HR96dkKnY9MqW1jbq72UeVjFyNxmC3V69w5wCyi8KXM5/C/RCRbIoezy8hH3cx1+m1hChbHSZX0c8rKSBguoteh/CSMQJHMVur1du/VD8whFJLrEG1S6RZsax
  template:
    metadata:
      creationTimestamp: null
      name: favourite-service-db-credentials
      namespace: prod
    type: Opaque

