apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favourite-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgCS0qv8J3ypAY61gRcVnf98E2n6Y36ghfO1s3FaCevsMwaSGcQB+rzA9a9dBwvOSoRhETMon9U1vAHYOEft0kS4Jzypa8JNVCpR5zHBrp/Vi94zo+PNCeLOfQy1X67T2FuPL/kIsP6VtOlbEXwtePtb7Eini0Eq91S6zKfz2buLB0v+2HE2HxSYb/IEGwnMhtbV+TPMhljLuM4PwANgB9i5rqJVAHmxwndrCKzsFiOlga4yq/tRB3jprpNy9S7+ejUHQbdNeCZDQk/P6EbwoWCJajHHaa1WUG5aQHlvYdSS8E+wj/jIK96HuHnMuLBdd2psICbTov0/um4kjyfuqut102JFNkId3A/zDzyQuvWq//ffnCcza24XtpDfdBKs/ERO3FTHe3eDr8hZQEYV50QAUP0t9ARFh9mFXrZb8jp1VwvMuEYrgl9gBnEPOdvBDGboS06RSTeo65Sye0eLayI/PZBlIyxBwpny10CuFxT0aSJu+i1UOpCMOd5n58wG7+HHTqnTpKQgBXIrrCKnCPaUZC6MqRd9HURIjYp4H0GPGNwjMTiTWi5HMtZYAuVE/1GMdh2DxOW6q9qVHZjYVpLe06PhfDBcQ4vhBncojO57ql+3Ta7j2WwDNRF9iMXbliCIqfXbaZI6c77Eos8h92ysQH17t/TJPmNLrAQxMI9YaEO/QC1Ezf3XNMAHJsHW4FJfxAB8Pg==
    DB_USER: AgASSOwchVOqjtsKbEip4FoGwIF7GeY3h3O9dYTLkX+8BVHfKsnfyN3q0sZk3lWl5Eg2Sazcxl/ugNSOUlora4XEZFpKEj0huHQhszvCIKpvLfPd+y0satstZ9nNrZkNsStluUeBr3BIfRmPXZJWzyIq1BDV8ixr5nQm4A0QhGG3A2sTYozOgpoanfVcIjUx0vigvIeOSvbevdvaxf7Vb0480u7gcBJahC3ZLLcJAHz32H4yslgEsYm+JdTTh/Nc0T4hwtvpCpP47PH1XKp4ib6lJX4d9lGs+LuJ83q1XrRVXcBf6iOvzXpyARV5B7vFKXAGei5VVDsJc3QsxmVUkuzF6iLGvyM9kZjUmeDBZE01EfEx5QaOY9F2f7nHwuMCHKCVKBJDjCnvVKIqk9od1xdB5Bq9eauGl76Kxt1Cj6f7VY0I4zjKbjRt+p7ZBZL4g9Mfxoffg1HO6s7ASG7JODo2Cf7ODqaYeZGT16k23lXlsdsQSzpqSh+Lg7A67xztbZ/EI4+ZeLDnLE5lRv8LNWpc+MyhlX2bWQhu0aofzSOirAsVAsMNry3vAAO0UgX63ShzJCBbaP1LezZSpRv3Nu+drB2XBWTJgkeIPQIlBL8/c+O6ha0RZv7/ZMruBYgvB35eAV7xHv8Vduy7sLCVG2lcE7w1tDlzHpNwmH8ZoL/ANTMIIKToZJFhh+idkG74h8MildiR
  template:
    metadata:
      creationTimestamp: null
      name: favourite-service-db-credentials
      namespace: prod
    type: Opaque

