apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favourite-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgB27bggKHEV6sI1/AVtXNEcZohcgXwI4ekomcNx+fYoZK7z4OHnOrFXWKN8n7qgROr5LXrNWXjNO/dxQmDrXaVAJFRlziY8LgNvJQ6tTMui36pynxDr5Zk2NI2/gznbs8z9ao/j2G67NGDZzc11krTV7aow6IQKT1H51TiL+s27Havegzu/8r0EbfqPMUa4yKHN7GPBBRdYr6UeNbK9ke9SC5MQz3FQbvaTx38Hw4fgqTGcD7B6TguizDHGAG/sKdUEk4IxOQlUIzhCRib3FxOZDVOFK1p9YYhgqUWGX/HEajDsDa2O8/fzYEHGcuJBM5nzjzHAgO0SQ51RIykOBKuHFZz+I/kPb3rS0/8GAw6dp8nuPBvUHSBvzTodCq1h2Fp01vMsYo5teed0DiuIEPexLUg8k3CYYS0VxSHnoMQWZ0z5nW17D44EP8R2aLoGaeBN7Wml2i+x8uLH3dz53KnB7aNUYifZSpfwUcqQ5xRpbMyPKderX27ScEyFQTgnb2kBwuf9V/lJj8f6tHH3m3B3dLdLY1BmnzmrCqIz30c1mbLLaKlgzYronlZKzDM0VSRpG8RwbVcQY8RwNDY70ghqI87Kaw+YccFtzEEQMSkJMiJyOqX5XYOKknkZ9fGIyUlXqSkG+RBO9F0ipGZWPoKFrkmGeLzF4pJu12AzFSTwMqAtrbxj8bpeIRas5DjjvHBQDYQDCg==
    DB_USER: AgBBB5Pq4nm9lxzQwrOKYhdIE+G5LkqFkYAW+ay8vgQNY3NgZqASNz5MIehQOLYqzeGolifJ0its5CTK9EqEJMbfawzCqnh1NJ50RQ61rnxEOJIz8oKobcvFiwwoDPxcn7sM5vNk3ZO4NXQeO4JiOjeuidhg1JTzxXX2CbQZegX7l5aAmvkVJec8GUJtL+c01FhEIQU8w5a0ZVfm5pxsiXvAfaJ0bOxktpHSPyZXEy+OFWlRZ5DvrjE7Fc41/lIGFiYYyuExbEmgjCpCQarLTarwB9BEdaKqn80JBzpq9H5A8aNwwy7BSJRbo5WEDYD04RZIOzGuV1LdvbEVP++ptkQ/FyLw3TFz1UvwQqtE7exqzXeSh9DWWSCNfNUqZpPpGZaWm7W6aqsN3YthhJngqzw2OBGwaRZVacbtkHwvdm2zO11JdEjyV9MiKZSsbT4F57p/X0Ygh/xbUQsdQjMUhi58lKC4j9Ma5qnGggbBXa1YSZORhB5QzBXh9BQGSeaM+wa2fb2/BtKaa9yKHdvSjfXmYEsZ/1inGoy0axFRIDCl+uYT17EZgvpMajwtRXr2meivVyILKZ5knysZrpFsL16/c1VbUdsBVtrWhl5bo1bcARJsWPjyZNoUrmu5vnPxXVNme7/YkJrcY1M2JaNYPeeuYNhT3emCe75iEcVsEPGOOuTqyvg4ulhAAVNr+TQKX7T966Bu
  template:
    metadata:
      creationTimestamp: null
      name: favourite-service-db-credentials
      namespace: prod
    type: Opaque

