apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgBOjNH+dw+FfoGD52d5TReyDDvl3LAhZFPW94UCpN2DrJnl7pIxegm92ma2sjMtaI5XGNEvKjb+PbiCstyAiVvbrekoNVJupTRRGwoajpkHekZdDNsqep9HQrnoWZqFcB5gSvkZr1CspZP9L4sHiAv0shir0GftUfkRhjJLVYtyVg1nFTpE8g1FzjYt/B+eUp3rvPcNkJENZRW04UkuaHHgNxmQmmQj9IXHYn2Oro2FfxHWLulwe5SxrL9p9JMtT93ErWtndZ+0LxTa/QpksQSjZRtfgu7VfvGJlCoGewjpSpRcazTO3qhYw4MkDv8QaIa+YmlQPVAPp7/zJhgDbN/5eE6b8DY0wg06WppATi3ZVyayykdc5a/Tv+N6KR5o27HZzr3rs745VnRWasW+yeM7+4H7XLcZIrhB1TsoyYXMbck8ZGNmNpQ9fQYni3AkR2ke8T3w1XFulx8ds0MTieKtYMUv1fKXZIvQ5/2U5fFyIn7kEwh952buthjAGBCjgMw3ZaXi2TICUhypiAe2+ElSnaADbGtN2GlkqRir22mnjhI+xbYUaDyyWaY5E6h+Q1KpJKzMLTAWn3Dak7nMiw4gHkQqA0/tLAnNoEaNycW5VdRkshjJav8jXw9AItZV2Xny2q6yuO2wgyLuq1Ld6PUAzQe3177deJTi318rB6TcWanI9CzMB7zH1x4UjXaKeQ92+KQq9w==
    DB_USER: AgBgI5+jUzWB/iTmj2B9UNBlNuo1EU4bIipbfgq2CyNpS4kFHZsJ+n56hNMr9k7JUO1WaOabLfLCjz5BWTCVHzV0EXKOYyxkUvONxBvHI/Z9xxHC7B2v8uMHX58+yWp0HAzmvPPgXkybc26LSbaWBmmXC24BLu/ODqFXMnBvevTe2pnwnnf7mmkzvSVVetWe/4wPOpbnnyZLnRbesKoTtkr9oKA8VBYr0T2hIiDkAvjZmkoAGW0FXpgsN8P75HlBpuyF+Ru5K0Zfz4XUpgHwK7bJEPefzr5pDJh/dnV5L041Xu8CrcMlkUX7uvik9jtZkRWto2fDIo6h3tJHFdTJT1Hu9EAzR6joBWGYgrqOX3IDXGpTDs5nt0yFeLdSEOpTXcfzzgMdR77ftZz7iLqZzHoA2rEaW/PGXp7SUFurETIsnI+jzqKwDYQVd5ADn/hqPe9P0hp/Aeuu47Ivtbo7s2A1DsHVusYph+PlSJrMCGgqTCpFMh8I+CamlU9oauN108TbUGpTXOvK6Br22Gl60En+PF7UQJAGknqj04tPKygV0eu7dxSyxmqpMyDZIuPEd+MEjKPSEl1BTnskKqz8Hld7uetg5O3EfBj6vrG5+ydkQi2brrF+09pTzJKTJkY0YHp04eLVuTRnZ5p6AX0MXB9sdd9W61DvmmrsLABhf6oDy2+sv37BzEFCwZ+JWz5D3mtmLxW3
  template:
    metadata:
      creationTimestamp: null
      name: order-service-db-credentials
      namespace: prod
    type: Opaque

