apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgAp4wP7J20oAEv7W6hY7hSPSQyVDGVxAarXwHiSJSkdTe8IGgD/9uVltI50Q9JApD9/Ga561Q3PwD3TaTU4G6pRvfeUa35F5qqi8idmcrYP8MwwdeQhBIj5LwF0vbnoR7JlvYe/wPpZUyWWJrvIhbVeTKLKsg+VrOoLdOLH9UXEe6U1x1CcqmlIDmdqwA7TSq54uMmtwIIdNC8/ykblTDoRFZybfJftNcjaCZqOeNjtXnLlkrnjPnwl2ojMRBvgUFzsuiiyj7Jc1KmlySAE6OJPxDUmwiWenYmu6nKjCV3Fne7/lQjhGTeMpmFYMVtbB7LI2QAXmPHkLADyXfdCYaUmYNoKMJZ/uVMI/BUCmlD6eFnH06ujG4U37+4ahbkbFIZymYjKaKimy+os5c9M2qw971+P3yL0Td2ZMJap3Z9TmjY6Ngv8csqKAm2wCzhNe8KfECabHeYtAluUzyXZPu+Img99dBj2+OXTd3NuRTNWP0uLzelCif2iOTcmpXsC4jvd4ORimXrtiBTjOcBAP28dHFPJvirNd/COLXcbkGkxsux7pCvzT4gJbIliJUpzQTJ7xyiwULruKLXW8etSikWf8M9rILVtFOp2xdBhIH7awJ75Y3MjuP6w/JSRONQ+Qun7grgTQTDAuHPSK1NVm0sqgFZtQ3GiJ43/ysLOsmIbMSQwsGpO8Kk0wESOoL4mYM+67ExRnw==
    DB_USER: AgCXG2ugcBbJSZ9o2VVdR41PWPViXbSNWifOkE81JfC0rVrmRpR6o8uO4yTa7ThOIHoAWblKOYBzByKTZ6EeX9NKA07wXR3ql4iHak/JwncI7ROj+3bRBT24SPl4D6fo1LlbYovId8PH+d2szcOxFUPSqDLwQPde8lJithv+9xLYqPA7qzDJtxEJxo1pIWnJ0PJm+UHAb4vTSBJqWUhUB4Zm7goUPOU3Fiq1WjpbMJtCfVr+tsEr8OLwyNaU2a0Ij5W3CNuy4Q0su1FMvuIg7IWZn5pQatgJT1e8UcQ6ZnvrNnazDvtZNQRUVNR+7XEg0xLBWz34qXANpySxkZoh0NmLJCtcDsjveJsFZsjDKslU/NJfRtocrEKD3P2yKfD3QAymSqPrvcftbKqwE4zvPm/+N9rnlS2ieWVWkQqp84azvwz/5/KwmTbh1mC9Cd2npKMqUtdRkzsV/qQvWelOWj5rovIkhLPgbJCAtxbA0VzNlROpDfxfekaLtWhR5r7Qt72B+1XU8IAcG26l3CLdYkfGgdkpOOmO0uwmfsvaE57Opq8dTKsYlB8MPSvLVj/qX3amnIkj3cEdckiTyNx4srE9PQZ2dl2khmYAJwUy7nfXMlbQ55EkQXzOOPz1NxBEFVcS361PgL/sM8aSQ7UAm1cPukAwhuQ80sSJl59fjWAvRHfOVArLPHHqUr7cYz29rul8JNNj
  template:
    metadata:
      creationTimestamp: null
      name: order-service-db-credentials
      namespace: prod
    type: Opaque

