apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgCU2JZE+o/Ix41cEd68dNoCULx4Zl8LpZsPB5n62ewPxDtXYle5AtRh2DYVbqu42hL6PkXN+VviOw/3sfNopb0gE7p+AOWnslKcKJJKIUG05FEGluOiRI4FtaRy4888wzOhfdBi/dUXQoReEvaSnm8qfgtSykvA6eV1g/zC0QFmYHS260RzF/2BMXuBgVzuPR3HjkyW+K7mhhMS5+6fK8cXVt8iBMdjxKUJf8JS5v02VCoJMl1TyviI8nw+d0pwUPZzmCYac+0r6vw5BUpop7w8Pp97hlDqxKv9a4fJshrtfbDHTHBRNvv9/owGKygVENJpxWe24hi7Z/mu7KrxZh8aoSrpPYouzQidpN3cztkWush9TphmoIpV3rVNasHdduYxwsrhP3gy/jL8kOgPoMgofkkjLWW6oxN6R5WrqbqFFcW/aZWLv/TDMydijq44CIfpXZMhAwQ1DB+8gtCS2Y9930fcLBkG2AgoTL71KqNDe8H1A5wTV2uBsgP52PWDE7X2iXcQhE9+n1xvmBMj1dCASTnyHfQ+E9MwEomWJ6dQ+lX7e48dY2Oh/+EcHDxQnlMEcs4F0ef3B04aLExDys7xTpQL+4Snp1lttOqoRDyCmYnn6dycvlo2NE30kJ9SPbWtWmH0YFI+lUWShYU1eJmGUUtfLLBdCfe5oVLMswfZtoC+kFLwrpXwHgoOGy7y77iC7gh08Q==
    DB_USER: AgBYPKY6A8K0gYgB0JOujJ0LoIVZixeVcNcTE7P2yVFYhHuC2hzE13Y0zz2k0EknJNs7Qc6Oic/FKZL1AP8ZTpw+xdsvvHQ/TBm+Ybc+hDDAEmlRIxK+wdulqMxijK/0RwJNbFWIAwsWJxjNx/qvvsX2a1fveEkyAPdD0tlmR3f8Wlye1BtQgj/+GUaLsC987s6V9k2wd4Z0ahE9xhOZqaA28tEkpH7Jj0l4eVIV+tK6URjNPp/3LwbrY8Klq7JqvHYaMTreDP2u+mAGh5XwvFAIPWDEHAn4Zct7tE7NYAVcjX1OYyE56yo/1WA5Fc13wtYSxVQoM4wStfG49Ih6LGjHXpcAKy8sAdMKUqz3g6mr8OSTYszW6k9l6OAQd7kQtK7QVmya4dIcHTMfqvgHL6WdZYbTLkI/WR2lCtiHYFqActpEtSdMOLh+LDdJYdrlS7g/8L5euwCFeqO2zhhRLZupZN9SSEecPLgXNyXorFPwe/bmf4zeovC6HIuDfDNdGytcjnFk0ODdNjH5bZNCJyPlE9IIDGZO36d3e5RdAG6p30HkpnLFYA5tmXYEvEXiJVZcmSOTq+SyMcrfdiRlr1pWIHugY0z3pcICkyVQa/ofSIG4fzFQGfio1Nt6pfvr38sOeZlORV3cixIRsmdpxp2pQUzKBx9tzyjrpvqPmKyoJXjuYqlkL365qutsXNVAg8fIoXaX
  template:
    metadata:
      creationTimestamp: null
      name: order-service-db-credentials
      namespace: prod
    type: Opaque

