apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgA+1ltNE1KmBivEi40pCt6R4L7AbE1oHHt+HGD8EhQo+LQjsk9OuYp+lpV3nhBQnDIIoHWusOpzjjlW6AcWbsGPdqbvNhsSdYLOfA87RoYy83SiJZVDjzhNbF2dfyNMUOzI6GBLvnizceLhLftgofjJjHaXUlomZRtCmr5bcoo9RDk0YnyYuvKh1BttDT2jDva5EjEf2wAqZYUdIVyHB3MFYOWpejRZ+KAtAnyR9TVfjsxDudfJZfw88vgUXCrD1R7W2RLw+0V6A52gpFAmmLmkdWj2pZTjYEi0dK7oLN9dgfq4YtlPURIiOgfPy1CSJBcZEdJL8J7NiN3jum6RLsJ+JQjFtXUwlrHO7e8hHi4YMKG1ETIysCpvc+/Sylr5v78cDprfRJUboxFN6UAd/HJ1IqGkZuLdyzahhPN1RmZMhEaC9G20XH5cDBoiIleONz4abUXiXKaA3tMKEnKovl6wJoWeSfa/td4h80vx4raIFejwlhRMYeTZ0dIUkG6C4zDMih97qT3y2HgW6gtA9n4YCmqtoC1GRAm2YfW3P4hGl3M7C/b5RCpuCnHrEslmqbqa+gGjsMKaQ7aNcouBFghqJKPiu5qC5T/gvPqKi7nLL06IVC+ZnSD3FCGq5jQozYfAjGDajdP/dbw+sgWm0gDkFTEWI7kip9E8MmCWiTL8hfqdQnPX4dgW9zKNOWCKSyDzSMOQVw==
    DB_USER: AgBF/5OC37IMYapqZWglt+hOhfnBlaOXEdxseED7qxA4nlKplSTArSegCwusmq11oH0pwwhWROoigkiOvqOToNiBeI1PX72IAPfWixi+RTDxPqplCei5HIiWWNBkfnJHRgxgMvLxXL3UC8zK6O6nr4qM8SbnoFDImN7kP3sAhAavINwWPaCSJnIFiBlJ3sd+03aNe48snKYdu7Zu3kPOoYrJGbZjbYl3ehfj3jmIqJHVYoNIqN9qKX2qmk8xhqgCo74ppSY/VnbcWiuiScLGeUNeT+ds0s7b41b+gYhsTz7kh0dqc1AUM/13uOHL806FMfvN1yAp4anbLC+eIAkTKjAkTU8G18j4sb9cHOmbYJ6o4ckqLO3qYY00ilLn/BSFq661qo+c0b8hQ/sGWAYHR9s9vKERIXmJZ6pr28vmSXrxDyYNKV5sCd9fQPcGq4uRmYoNW0hE7DYqf5T7abxSY9k4nsH0hrcJSGtOQWjS3eGFT4sVidSCzyJIrN+ISFJ5qQp4b4M6Wt4DtLxP8L8QEJcNZQOqsiSxSI6kE0yAnPzEa/3V00zh+1GtVEJ8aenqLYertseZNXb1JxlXGYjLSXZysHkuMMk8eV/RiBL7giAQ5e+m2hDqsLroJx/k7UQU4efyWknErCFLYLMxM5d7cj9fuAFIaoew/dt2u0uiHov60FAMQan3WTb3WcgJYnTy4j+71+Ci
  template:
    metadata:
      creationTimestamp: null
      name: order-service-db-credentials
      namespace: prod
    type: Opaque

