apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgAzJUxUtJZwAbGJV8XYVXv3TfU6ucKCw/Rq8osAqgkn7kH9cx5s3jpC38L993rqjNikbLx2rMuPBzkiq/PLrlwJVQaGVMHpoBuxq4poLJCT0MWwu1IqrQ7Ocmm0UC3aqJkUNqC6IQiJnWSj1ZWs8Z13dmQFyf+v+6RtQrCRMU4rGc4igZzCZrvPD4UnHmJp9xIeyJ2hyQwHwWt87I99xYBdQq4AA1ZNuPeCril6RYH3RPYT+RXddpEPBU5eZZ0LIw3y8Px7BjK1LQX+nnizuYJtlVNFiT2ZQ7VdElRZgIltvQ51oe3sqlbJJPb/b2++ol04+/c5rqZDumZNgzNKmHK3WvrGF8L7eSruDMA0cPFPyXL2a+l95VD+swl4Zc0qQkzcYaWH5kmEpgcSd/RNGHfIBEcj66C/O5gEFZ5GM8Pfzz3fxKJz+DxFNyrNXGzASzFGH1xQOjE3VmxhZiC96GKs419EtSYPWiyF8Y6TljzcBBFkxGUiVq6Yij578/Lv1V2ZKZxjUmkIJ+qQvbmiqiYaW5mKqOwLdjojDBWnzOfx5OvniIRYXivp2PjWD7O/8s6EHKAGZxG4uc7SuebDyil0XKY8i++RXFhG6eBRR/Bjc3Xh6j2fq6JfQx5TtoxKQinW+1s18LFFaf/s4LWbYonkPcsavvoFHpM2gj511h+RDpxlkATBQw5imeXkD7oUaDAHIXrmvg==
    DB_USER: AgBQ7HEuHLBlp8v22MqblBrkhSkYxw+hYmdPfcwkSC4pfFMmZj3INOcgZ2AOXTE7kyGTKhTJs+2sSErPwaAAXfxa93OArUr3tk2Zn4D9b7AsUNKH20123MpdZe46swQzU8h8MhUKlFddu+1AMeMAI7eMaLRUH71Wpqdn2+xJrssdMY/22QCg1qv82RAdFqhbPTzNuhugi9FdQ2qjcwU8SMqv3CmMT4a4jqQqPPWk4Ftz5wsXUCkKwmxbqJyP8aIGVlPh9kLvRmaTKx2ScH1GYslugtkjyc3rFl6ZqwBSD9HRfpZKLqzXIR9AeY3eP8q4bsJN9ft6lKC5Y/mRIq7TiQfr5Zn0nI15MW5i7cs15gsF9OHR0jcQwbFYOYAx+jFUZJH8Gv+0Y3A+fztrcDPy7Exsf4M1GqiXOi9B6g2/9B9Y/Ht8LL+kvhBEaPjZmGjPIIlgZZXtC85ucn8qhRCB4KVglhVdMMgDA6kTIaexdG3p9SOWDdm1vllPM+4iVMes2McD04FPWBuFBvkmxdwe1PvpL2wN2BkLKwg6tiP2qytPfPAV4x1ofHFpNzn7Ap0z7zxyMTU6zvXc3VLil+UGH3SRQAh6xWixUNSrhHDnQ/K+O8Q57loEYvwyokUIPdTp5DvNA1tA/nWwfibLYqfLl2R8eTKOHQcbbg2TFyhZJiVI5x2Z1/zVRb3orUDSuYUZ6fyqL1Vp
  template:
    metadata:
      creationTimestamp: null
      name: order-service-db-credentials
      namespace: prod
    type: Opaque

