apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgB6u45cmRHRxf3H1k41Hqwn7nB7lm2OAoUNgfS7UF3kBm33Wx6yIUddF8e0lSjUGhn1+UgG6Z48JjbShXwX8McU3YaV6TFgj3XyPhbOTItKg4XXvfT9y7UgSSTM6RUuD0fVmhUdGAdfx+2yBAXH2UpFBffIALzh2/Gi6lP/7Ne+JKeSlw40W/P2kCmmMicn5TG60Ct2KJzYUHHIDJGSoplnOwbht7TT+T1VmT/6lpc+F2db+yzqK7LRcxzL+p9rD1dXqrF9k/6fj+Z6wJP26i+kjWE95NIjblct8qAv/nf36FegE/6m4Z/Kj7GC/OTV0Rsi/RRR8GJ2l3ZhxXXh3xF0ZA8VzASh8Sg66p1UEQNDG8c+bX03HhLjAOg75GGJrEYgNr9mRA681DNsmO7nSbKtRVNpReNF4bZrXttijA3fQgqfPkunQp9I4TSEtdKtcHdJCWBcUL/z63oHdbhJrC7j1hD44pLf9FJmCfMBC3PxibeaN8mGzERF1eZzkgHMb6c4gskg1RSTc15yrrabzMzG0RC5JlFBzRtA1jrGnoXdhBh14VWeUrQurQ9fMyhYw6jMQ/tq5Vlrx4+hNXzULFA5Pd43vkoxESix6p+rPVZfIKUO2lAUYtE6TstVzcwi4eEjtAXU85NzleNA+bKQIYpvN586iKg4UfsB8PWVKPx+Mur5CzM1w0CT8+Bqm++45V3kgnntYA==
    DB_USER: AgA0Z7yABqdxcBg+Ken1Tf/oeC/q1ReSjYnzXlgN4MH/dH0W+LN1xtNF2rPAXs8phplMYgtF6mZ2+PIUwcI+A1mh6p5gepE/LoaLG2FMGCQDwrWu1FmfLuXifAR/WrwPaxZR9gl7jk2dGtYMRWX6seu/jmMQmtEkuDvZ+fwU2/eivZZG0giWCIMvEH1dmNeQjNGIEkJJj8gZLQhI4SyOCWtYlf1LDQ7bjX1U/FPQWjJ/HAk8HPSnwvJYXQb5VmTSV0DhLKyj3sKKSHZxtIQQIEDUVql8CV5QQ6EKTESQ1V53QTGQL0cUNDMNKx2XjXM0bguMMJr6MTZRkaqjjQa4u4FwcxnKhy/OEiJF3ugUWjChkkZ/nzUwjxxnbglqtDTMuwOHXYrUnKGKGrwWugLWUgET0a0MzqqzCvM9/3d6+bLJ3OukLPB2Yi/l1nnb8ZgFgUnFR9a+M5dXG+EUq/jqrKeh80q9GtfeRAtRfkXgpYtRHC8BCT31MrEjUmOJNKeQb0OlClB5J1/9ZHzRvUvkLsujjCgAcTbQTjHdsR6rHzlR1RkgvE18n3HpmgpKvrdI8YjK9Ow2YHuOsoFWf5jX0+ifjRa+q5kETYUtQrrbo1cH2lVWIe+hz0FInbHGGq0bAHYVSXsQgJ1YcGkAkLMP4QafNb0zYUsnm/7eDx0VKUpiMNHau+YA8llpEo77OhELuhhvK/fN
  template:
    metadata:
      creationTimestamp: null
      name: order-service-db-credentials
      namespace: prod
    type: Opaque

