apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgBtSjWu0CXprwVpbyWYSODCiUBuEozetPybkmxVj622k6CCgYibATn5fiHc5C/jkstKwYONfgQspHZzVx2C1KQw97otRant59N3iM1c3B7ypRymV64RV69pzhNsSunb2J7O31Ga7+Ah+TUYKpe3rfKUcs/1ozxJTDMt8+ZMGgmwd+XdOopkihnwuqhuhw/3bJYUGwU8tfHIbxg2fsFeP2dmUXVan2Z71DZUikIQLZW0A3OgwySkeo7vGRdgoYSROokRLaT2CPV/82rtf3tFyZBzEDDTkrAKA9etifdLrALr4Gi3nfBfsX+3CU2OJYEBxM7vNM4c54Nqzsya+uKeQVr6s3O3kLS6X3zRBb4+YJIHBAQF+NH+4ckw1XLKv3D0qq8EHwYy+suDnWPbbY9M+VgnI2E3MYbJFNhyrpRnmnnH7s8gxCI1pZVsD8MecGFPtmKsqQNlpW88iHsm6+b18QV1/bhXcIfzbKSuAdODMY1SZdnwdcXpWGclCPUyRWCr6o2UQRNVPe8I1kAQrZYuZq+uxfJZTDZG0JoYBiqpOp6eKF16A4VWk+HW4ImgbZcSKhOWylsjMewOA10u4IpbJQyia4DJF5PJpiTXkulm7T82S2kBOnjsdu5YIFqNX2ZJ+rIjpKv7CfGaO4YvC/URdO4HZLRRdX+0hS7CMZ0sDah4pDJY0gDYCrBTdQ2LAwxR616Xumd9xg==
    DB_USER: AgCaOZBjKNb+KCcmPg491gTHfp9cEbK9q1iS8i/Q6bNNVcA+1+fDolf+/c6vc7ujuiCLlx4r9nBgii5iilhfh4xAmrHvMqNIFNJ+fsPW7tOB5Z27QInVYAzreJnwOZsi3xtwVq0L8xxR3SZsZvxIlf3KoWP+nTtcQgPG3QzVuuWYkPl3u/LFd1C/u0ZRA1T4P8UOrrutP7+WvB02JgjW8otpphYsuYEI68MDf5+uQvs6vB6FCJF2/GnrpmtoWjGGliEfGHW51e0y2v27aOBx1JRFyYXj28Y2WvL23EFqMj5/oa9wM2Ync1SxioDn0oBlW1KX+KIkz0ckVzbF+gUAFFxP1uavSgHq7zHm87EGurpXkZKXmTZQ8k0SgEGN2/qK+PZQOE8kl4AK1b7GkUHV+l6eeHOfheHUapzG6KQdvAA5en6EShDX/sDticAN9XA+2s9UW+YBa6TVRfsctbI7YcmY5+XXhljJ0bHtoJdkN0oHdPluxBo2Qo0Oo708Nz0R26FCM1P22Cl0zgZS7eEGHJh5tQ2e/rJ42fuhndU6Ck9I/dkryZQctaC02TUn40/00cGLazTTRoXWe4iuuV9zCF8Fjg5QcRqYn4oN/251HflJViXZNLWexEThlnqqKz8+OZ18D7RglabkiPq7pINNmesX0MhTons5CXLfuNLncx/C5iUvdFEHU/or1r5rNHxhmx4SWKwL
  template:
    metadata:
      creationTimestamp: null
      name: order-service-db-credentials
      namespace: prod
    type: Opaque

