apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: prod
spec:
  encryptedData:

    DB_PASSWORD: AgCWRSfea7uZUx8GuWFrNkkGnqnwX7Cv9aQi1ZWXfpfRDPzH33/7sto4I43zL14NR6emCIS90xHTNB329lULUlHxI+LuRCexP4epTgoWkvXTD/8qPqdq52xInXVCEi0AVlAvZp/Jp1QvEjkfC14tjHQcPriiXSBobIzf20e7koBRC+WRsQv0hUjvNJLYQt4KNIcqnhW8hvYALcMEYk1pvx6D9WPld2KWvtx/cO6BXAYD+dp3TZ7BAKprWqxhX2Vy6NBiORWnmr4FUNE2I0jq13WpjD9We7oz1oUkMt0uiQXcwmqOR95UYUSiuQSoo2FAS6/nxTgwvJz7qAs0BtVtvRUyLD7TXN8digRak6hYx3TNCLkK8ZreBshe602WOOKewF6ntnaUKgAtHo7i8NrPHcvS1K5uF4MBQD41hJr5tdgeRuO91DME0sFOXX7yB8p1joRLq7Rk29wJ2jAiu7HTNqqRqXyz6iI3dZ5Cfz2idH6eXSssh7dMLuFFljeQhxZ0zOH5Q55GtDAjosZokZQMpKlL33s9kTKlq791ON8D8ZBStFhx0LhuoQHEGdwZ4XQ3UZqaZpIHE0VEuozOI2UjaJ1mA1+mQzUkhLINMmI8Lwh7IMr1kxzxd0aLWDaqMWBm6dR8YPiPXdsvnMWbIbY9PlxGPATR6AFREHiPBuvwZSII2aEA2uDy/v9wljqK4VsvtG20J4luBw==
    DB_USER: AgASVA35yE9YuuUl66IUNjwd4zte22zPU4m30a1BhzBTGHinyz4e5ZGGZUF12anp1ufxLz+ogyYKC4kaYZ/7HU3Xn1LC+c0rOmpeMuipR2gJhA2gllZsQBuczDECz+jz/rs3hprYQOBkys6xkSFbVn8kh+8D6l7hkpcVHxVWwh2cH4vwRgLRECVPwHC1dNjiLK4gdtjxZjBa8nGbFzpoIJVvwBT0tC9eM1ZYnHqO9yjO1rRmqF19VdLvzyeSdIeED1rNq6Mx6hjohs+PbehX2wOW6wcUU+nMoLqNeHEuqkD0wlB0VxcSF4yUm9n6S1LBUvC9f+FmvOcS3Qd9pYvuyvi9V27wnV9/nI5yw8OCcLn/+4pN7l/3u/e0wBsXiY7hDqSjOij/P4tpxJSLsSuvMgIALlVF70njHzXaBFRg0o1Q5UOvxSOpvgG3uqoM89glGxsjlGaMdU+GISR8eo2PLnIT0pfXhriF/pTKsZ/jF1EnnUhMx/L2zd/3HszjxcjivMQHZJj1S7Lo3cYPEzS2XsNycap9IsIC5LqYq7m73QAW5l4fuYMqZNf11VzUyrh4CpWu/lyVUREE7hr0gO3VRYux/wJQTsQleg/Nphi7O8wp4ALKea6w5o3d0tak+dW2Y/7wR30kML0PbUFjUKBcs6MXmOHVGJKNOKMtOlZlJFFCeEapxDPtLUrEj/7x4Jt2vuOd3FhE

  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: prod
    type: Opaque

