apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgCKSz2EzLtRGYCfwrg+DL2yrGd/zYwI9ZFS3VKijyk6H1cacap5JSCKap7HUWLKdxnDUeJdRtIXeijymTWhDECUD9hiW8f7iWeJLHElsgogo1nElAmnVap2uu4O8FHYH8LD3T/DoDzht+IgkhY8frutDQfLSeepPgmARcWiDzJFCtvixnpCgb/cSW5eZbrrDx7yMWXs1IT49prV0cgz6XVoB0UP3zRJKo70vWh4vW5zSYcE8s8H67oYpfIBIMLv3xpksBYvxcHPEI6pF8jaP3KiHBYKh3b2H4G7Cgb1xeKqQ2g25YDiyMFhIMVZ9xg9+NWgZD85xMkis7krpKiAE4IrrnsrtGwCwQmyV4AQDVj8XNa/SPbbaFJrviKdB3YxZ2auBP0EC6W7B6o6WvAH/GFI0BJxbO2ypvCda5k1pgKSO8fWUzhJnEmScwhElhHgJEWay91FF6v3CoImEAW+m04VWUBQBCNnAsGeE2Y4/ukIKgiEK0Z6YDsX9BBRR8mBqfT6sEgloPxGx37kLm2Fj//LoNLjKZHcTEWJqpfX9CHwGh9HIomO3yrswko5W248OYIs5UNCXdAMRNVRH/f9lFZTm8j35XecZgOaizaNbBFNzYxVaj8rBpc7wmGoumVDv0lwgbYhFCO6TB+bxsf/HfPn8Jslq0E5QszajlzwAgzn/pzpNE/YRZzYPIihz7zwIJhBA898Jw==
    DB_USER: AgB8p0HIxH9nEX3lsKdtjSddhSF2wDCfv+kI7E7ZZhg5IavgfJ77i9UMrYDadQC/w+LBaCkSaIzQFKJhisAwqMNlgcqFng9riTUCwPeRoRA9MTaYppVn7HXt31wYNZFsf9b2QZ2TFRUnMlO9zJHj34xJ1GNjXnInrxK0Ie7Ja/wzNlY2ssD6lqL/GECLxxp+FudqOz5eiVZPJ5fGBnmTGtfmME4WCczeHQPBBUXRDyh9gHAtQ2vJp0uuAMW00/lPjmkSMCV9Y7B8kPx3wzdUhTB6+mQeU2rHmn9vo+2Zf1UwoVU54FjiEt1AifDUkO4lC5ja4evdXkv+PsYsuqOaKO/y4rm2liwWu8Efux6aVVK91GdZB5teCeG3RTPS4J2ksWmURMLWz622hmPcdfqZRBbbe0z/8lgo+jESIGpHR3uZ7D2eUdXZVDYH+ZYgRYVNB7DTTFCdCi+h1hy4gjl4Vr9gW4IqPsR2nRp9+vAgHrGfD76JJKu+CfS+UK8uKEiVmazqbAeJPQETpbG/Wum9jIKGss/pUejL7QUCaHS+EZSNz2V7osqntwp3W92NxCvBZpPh8i0pU+Bb2QKm91d9FgBiJbhGTtI6gpqgIow6BvbMGlZaEt24IIaQ8no59hz6f0G811Jn3IHOv4En8/DK2W9dbjpmzed1xHeeYtFfB59MErvQPc5+fJIp9JII/j1rIIaU8nd+
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: prod
    type: Opaque

