apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgBjDNYLv0N7jbjxziw1pK/Dk/UvTWa10LuoQrLruTl5Arxj6DlY1IQheFbu746y1ERsjgR/mxw3/NPMyjpcNOX7LZulcPYEfslleb18OXTJ15BJ4KHP9fXk6RYoeyjsg5H21P7E4g1WNKRrRmqvaUXKnAnEehq7qcH6vziueufu5GMsm4ifZwGvgubpKVn2LAZ9modnQfTOP5pMdwmHMSBOe1g0+61c4aQZL3mYMJ+SvxxGeppt1rnkaWRI0l366mbzYk6nfXKreeLIpNWL6j96q5pZKDAVt0wKXldVW1T2CFzIyP0YlLmmuE8UCi3TePuM5UsmGGP5ycssO4+hDGcDGnKQ8ZdpkQuHbEGPpR808SP12rk5ooum8cRMU6DyMMjN+H53uk8xgD0sKo7MtG9FMR0dqcypog4ZCmkJVIMBOgSHUKSTI+f1R8a8DXAUbUdlXPio3V9/XCpG8ZoolZaRxDBaZTwCK/BJZf7t1IxsQ+rlIKQeULIcZK90p0c/5XXLtXoxvQ7jWBSmdipAOwN0nL8Itl1aoIuRh5VlGzS/qn3EE371w7RBHPS5+N+KSQ7LLPBKQnOwjMvFRXs90SPwZfW7ryk/DUwRy8Z/stAvr7m2rU8DlclokEB157Z+wdWX1rwwgdRApAeNxr5pQd22Zx9OrRwkTdYUQxm6++iDEOVaROMK8742Hc/hsMDqoTcg5sAmxw==
    DB_USER: AgBnUZpP++D7AVMt+/KappmTYlX0pPJu3YFGMCq5SrigvfplLo9+g9gbt38ITrCFJ0tZz3zd26sny67xi7pONf38cse0MT/14zbC2D1ibEl5eUPW42Ee88sGYLPN+AylGwgsfdKHcgwgnS8Vra4+KO/d8hvgvTkajNTIBBq+5+ZR9I/KqVKUIjsTrnOTiGVQkyZ8yipTmcaywXnx81uqVnrk4p9tUbhIUVKdHQRHgF6xa9PFlL4EBN8j+w88PoB7ctOcLU2fDg7NylAWS5jk+c39md/a9nXV4P1/77rKVQliJzWc45CF4pGN93D+6Lqy1Ea2FBCzzg4V6xPWLb8qOQwM+48FoJUlIH4Iw3dcit7U9+isrYYzAmgAxuzHRCJgeu4X4ORmiCFBprTgKl9vkHQuJjbd0wNaKpmyYf4D08iFWE8jXPzFJ1ymffHwHX6qJSCiPFIGp1KH+lTsWad4azlSOIS1ZE21uma98h5A0dDGWEPvtyfdClYt4AU5J8vz4v0rT01VQLgAkW5bvcnmboQGaP2DAU1ggyqURLrpCra9NQ/lB6MZojZTNy88YnLYKgD3zQyl6JVQ4YNVP7BpDaHrgFub4B6oWFRuhTEbq8N4qQqV5LTjUh98GViOGnDDJQy88O7Dq+Mu+NfajNHxWCtZ2v+m11BgOfrGzNk9DBOIz9c47f2JxYhSQgJPJ7ZEN1JSkmeW
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: prod
    type: Opaque

