apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgA0M0wnu30lAJZiDWaINQ+1WC5Vwg3JGAKjGZWQkrnqm2F9exp945RMc7vm93Lv7Df6GJY+Irxl+Ws/DokiRvhGLl0gtv8KecHp23tQAKfa5FSrXWJnUyjsQB2unEvXlDBeujtxDdZI0qpRid8WIFvjCQ8UhLVQKNXa3GrMxugx2AeuVnIsJA75Px2QqKKe4WhWWsKTq/f1xBUvz8JqdoguKhfLDn8ssMOR/Ki7c5LfTiyO+Cm6Bw+Vg0bpCojG6PZwkY0KfbS6bIwcmwjkW1sk7HVWtpBzciQQwIypgpq8M9EsTqpMnmNfpV57Nk41db81wiHsZq0qqbZoeyz4ksoGdqRcbKFSHOCs+cfFNJJ9SZPsaNtTOKyh6wBRZ6tid9qdcO5qnJn69z+Q+5WHs5CeSEA/mIGyH4BLLdB/cW/fgB05Icimt290ebw4ghvF/PB4IzaDPoMwQA7+jUPFupx9fPil+IJQusiDORhJIPygmdahkEb0YTkVSiOohjhk9d8662lBdyXkzbA+cVrCiaER+LPBdJeiQRXrf1Yw7tWh7+WBkBnFzhttOmGke5Wth+ECMVqPUqz2VN4yL6CU6k/4lv/nTWXobQ8PVnWhbJjXiwtWFgyzrqkR5D3ESJDFGBcEE/iQqDJeTCnVw3GC/1DHeUgrrQV8tOSZ3xDI2JPSup/mJAlFGpbz1oPfVYcHRhFmVEflWg==
    DB_USER: AgBNMfZngesrY61GnL7/fkzwhsMNpAzy2BUneS204rvNm6BBqoc+oiPGXuw7SZa6UFdOJZkUJ5yIUFemtu/KY0uVyfWNbg+Dc+z0/htsP6xvqaUYhUnYv5hwInscrSuEfu2lUiKEUbJGLdBswb/IrkcupVyWeuAqW8FV1PkB73mqCxXvnZWkhwNBbAygr1EnAGkV9Nb05bAvLokMJ67mul0aKTGryHZB9rB0EQFTyCrmaOjfhInRNwz7LchPkvUq4giq/1t/qhrgyHqZppq+yNyRA7Cz9I/tdltMTeBBiNye+NQ8Jt94FHc+WfV1smTzSnNiEW2JVrZnYzthYJyxZGASACaoAkOpcBkXEAYJ6Ejqwj00EbPB3E3doC9cuwdoaVbAW4PmN03upwrKicSXK11TSfWsVMPshJ7w7NoIis4gh2VGM0v0A8u0/MPczNgVq9SOSTYuK2nWYXJNcNmRpCM4HRIyT1kX5RtiUJz/QyYqnmfv8eE+eGvC5XqildL/lALWxnSNpxd5STHbCJ/MLf2cTy0eoeGT+OG3RrkOK5kkGSNmGZWqY4cF8uVahFLwucCRGZiBuQDKSaqu5xEu0zuHtHFBFXBNdOOU5oHsN1TBkoa6W4ZCkRMCfAR7MNmeaYj74laz3vnYuWZA8ZbSzXbFMb8rINNmi5PbqtYfxOtt0yblWC83MmkF4OjevF5Z3Kcp/Cxa
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: prod
    type: Opaque

