apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgCQvPOadWkwkzunJz/21Fg94CIQnYf+ISC3rucVVDnSleMmRIfmRQVF+JZ9a4zHYyStrgS+Kl1etNWV+z3BvU+Syqd5jn36AgR+AUTasfd4mqarTIJr9IYftLY6rwceCzEeO8bcaY28iHyud0rEUYJYP53BvVIlhT9W/Cx4Y2T3EB7ER6MOqS7XgkY8LM/d7eE0+0IMT9HbbsZIT+TQe9LOMC8SG/j8gxvoVGY9Oulrf7Amlad3T8h9dM4QDGA+KyONV9991BBaD5lg/NFi7WmcO7/d23loUYsLUQKn+bbfUW793YOpRJb2V9k0Nmk4StJ7ltwH52ug1Ozi5HyPRxiavv5esN/4BnU6flcLt7v22l60cQl6Q/edkzYIDipch5ot0jUwgn1PThHO7p9izURw3BaNXfE9Hw6n/EtIQHhvoEm5AzALNiZmubGvhnlhpz3zkETjYvTZvM4zhP7ZwMRSGFA43pY9uVKnc6mcwW/kyXaiD+4At+rabfS1G/XsaU0wXf2aKFsi9jC4lr/hcfHSGmYrXAn70oFrNEh90QYa/UY39I+/7uImYCAUs+TVzBYykSKwxzxAapln900wo2BPBIsON/FNWF5u+8OCP4APWr6rtP/G/EPZIInvJL3GuNFNRAAKIT+AzF8bHcns0SSZqBsRi82ybD6csv2P6YidmdmMMrvMKz2FMuNFeyKhIGorAYvLyg==
    DB_USER: AgBVBJTGdj39q5KWNPq6cUIHFMw3lARkLS+Ppuqmsre+e06f6M0UtHJ6zY0Wmg4/pGCznQGv3SHwUEM6IP2UOo804sf7vGAMexYdm6yBXfyEe/1VAVeSC3WYlC2uOLCfEBTwfaLKtFt0kY/iUvm22XlanFtzt+2I8tWcXwnspUFsKkEIf7ptPda/6a6FsTEoZL0bnYvgoMI4wRCnxDL2MCnioQBOO9ik4n7cMW0qlPRt8vRFTlm+wh1jQp9zB65z84G/b47L66vg4ni9Se/hNND5OXy2xVv3nmR5MNTx4lULDB5VHguJPw7iYeZV5z8p7MTinuj0Jf7q8AjtpSEw+bjY2zCwR0TCWsm4YQ5bNsrJXEkmIRooghBwEas8qx8pxbhmh9YpYFs8Mddol3QVDFVAeH6gvhgYp3voIry1pamnLxCPN2W0Zt8eQVvgwSKH1VMiasdUhmAX5WGV9GW8JMb4xpvpsqqNX7EpMPi2eEqEkqlq7svs5xE4/QP/6xEm60EDgnJNf0KpVCYBp11l4W6VVsUF0j6iCcl3kMEo9xLeG+UHFAnb17ZRuZmM4qXv5iuIy8EqIZml0QhxvNGf7c1fAdVSj/WbRy+KnpZa6NguJaaRyqiEdJek4EjFCtk9DzoFxzBCB0QGJgK7UD6S/LnsBzrabchQftadsPUlIltxzdXrLxmXEaorL3ODQQu//KgiSjRR
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: prod
    type: Opaque

