apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgBQx2VxVBI/D5pLRz19CN/G0leNVVFo7H5cBtzm/ayCMAaKAFpEA4rdSLQrIhSz8piGiq1KIxWshpgB6PgQM6lG+APG766ySzSlI+TgPRDjGUF7a788EzlgjTZhu26tdLQcBkrnvB7g9KQR6tNpJlDiJq8UBNYU08H09x1gGzdurGhnDo8pEMn/u4w6XDoZfE67ZMyDQbliyBdeInaE60C6gC9shyGq7guVFCXa54J/0H/hbHOYA6/oTQVkwCOjFqZfE8nFLjfsULTf92PN+CAnJIsUGrnFHTYVjCR3T5kfyuOsWZhjNvbkgIdr7N161f2yovRzqSeybeG570dvwwHqG31K/WgLRR/TYeE/BHu1GbAQS0M+40wqOO5F5PODzbS+Tnn8RHbUp786dTPHw6vQyn3NCdguZ2Tv57a7R+C4zH2uxCVxYgsVY1bXthNlXv/tdwwjzNXBMRcGeucpnFL4ONOyTGaS7JR2REMePiel7vAHtl9qVJtGYy6yuhV/XP2mmUjkEhUC0KgoImJV6hHdfXAf2acXBZHTN7tmahmkrZKEqi1HHBjFYwzRBkKFEmQp5bRAINncWycMZ5ePWS8EwfeS7t2pNc5sH99wS1vu6B57Gq7xVBKZZJXvJqq/7BgLNrRKBtPDLCdeaFEsFnTKFX+EjkI60mg1izSSxxZKPlCZEvvKKc86QpnTM450djrXecXjvQ==
    DB_USER: AgBy9fUtODiwK4qnCkF/Eh4yYDf21b9fnTVQVFUDbe9nYzSTqA+cJDIl+qsbQesOizaEgc1BS27gsZmCoknXdzOLL8Z+cPpV+Bd820h1jeN9Cr0JbdDEw1C/fHZ0CnSKZpA15jxhci/3I0sxQLiCgBxjlKj9Goo5rhyp/dS3JBsisryKUBO98yd3taLC7/ZLDNsgTpdfMrLyUCZHraAdaIZFxA4j737h8ZRPktLpaI+/Zgm4fMVBoICa/cuV8ivD1MckoGMtZvvZ6O238ItdhB8qWMGBy1IadkQZEp82mwVh11gWskFk2i0rw/idfQsXfDfevJ6vu+cRZC7JCrxz776AkUIsetgiOe2syUs9eeXHULOJUNg+mA6CQbsdpKyCOIQ6eiMZjpTjywAm0zg4CgKOWVnbJCP8V+fbiokH+QJ1aAEV10NidVs5MT8+ShM0hMfaGrQK2fuD1NkgdBUxhZ29K1c/qJxv4jY3BlpxwgW1g+ouJnKXaQ1EYAVQnIC5V89k6MVsmB19dbcJXoHdkLPBP8vJX9VYt8wz0gbVGcsjcrs/qxWerCDop57Z2ms8DWRJi6fn4pWWtoTureJ4JcM+Y3w1yEGNB1zC1AUNK0tZJweVdnl7E/BepIj3Zv874skR0HmxwwfG3SLHg0c3ujQa8RblBtqc23W5xdtnNzetxVec/ymspii97AQnoJlQaASoPTm8
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: prod
    type: Opaque

