apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgCQtesmI4E1R/zQyuAgbcfmxUblUU/W43BrbPs0fMLUZ+sc1J52QZxr3f8bg4kJ+Z2U3TPn7ELf7Eo+hNh31WZkgol+DhYwBcgabVYi+iNtFX09L0epLMFEl7V7zD9/ubN3InhwJ+TbYiqOG80+vJB/JN9MsyXHq6XHk/AZpIsaFucrXeUcOOg+9uXrU15USr5JGuHdssNFs+w0TpO+YVKYq4BTAy8R0iaUBGmmboBoyofCY+vHWgw8EZRcLmZ8MEkKbYDOZis/gC/AFkrPOTma4zTDauJ8ULGXgnJaKA2DYf+9PAMbpWvu194XXwp2snoOg8RQ5X6+6C9N3KzPDSpLaCJ/hBEypnwp5JHCMtaNfEI6P1RnSiuTcdBV7v+ErL4GAp2dt2mAEP6HLWrTh8IshIJZM8FfmediLXZV6jXsoBflyJMU5B0dbcWfs7WtrNv3qkeVoJ+U11lsxY7HprfPV7bmL8HC5it0hzOpqGVU/XMaUvN0zcPEmPHo5UKmA6g+E0D/EmgQunOsaCiFldiiCPYuNX9jRtQ5YwBAyf0v+hS8umdI7Is5EJYsrFwUnaOcO66fijBB6umxMTUv60k71GuFMIQbdRR6obnX0IukHg4SyMar7hGwA5HWV+qfvoWtamxM2wV86WC25LTbt8JVVYaXIc12WaEJMttQ85eKyQ5/pABQT/Pfud+sHMbjl9EpzBjl8w==
    DB_USER: AgA5ywaUOzcH/wZrPL4cB6U5Vwxug+txrXsrxUvPbvq8HmdBPVJFzplXOltDtvOyWlm49TSeB/X5xL6pDQ+fXCc/46YlLTBRGRlUmC3DsWh0z0FDnxitT8XRUvmSzpn3S+25stt9wZ3Mvtb9vgNHXgWYpQl2/wOfa6Iyjp+sqI68cqREaMRVM1r57+UP0hSV2zMpdNmR6h2zP602S5RYXFzdClexptdQXNpTeeQyn8WpdhYT2M/83xQTI+yEIKMKpDjOeYBIIgiVcUuTAisHLdlB5SEgYr6neysUKqlgCG9lTh7Q9sZQwD/LBFApIu/WfJnXT1CbECC5xGWxQFPoGQksDbRm4qBlSY5CugwjCuPT3W/JwYwxSJehc5fBc4ovohJW8QrRRTuUpiAShsFitQ1JYGjIV6lkwdUzvC1zveiD2LpP8TvS8gT/LERNqS03RHim6EF3Juu92o4GA+GNXB6qeliITFPstV4Vba2xjLxtj3bboftODDPhi26XxW9PSP9+Msuy4yk9Jq6BH2Ls6WlaYT+O2WG8jV+W+WUf7ALgwvn2/AxZPgeomX+dXnrn8C4Qk7uJREIM2aJuWN8ez4fB8dUimz510Arg/qSgSkVyv9T5Etq3anpkw7oOWbYD4HIa6pbRkOK6M2BHso+676Y+TRtA5I85j1WPkBxJwm5RybfGrlSJfec6B90bqz2spbqOHFM+
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: prod
    type: Opaque

