apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgBkixtkIDVTcK0fX5P3stks2575jDNuFoCYy/XPSeqZ6HCBDuVkW0W4v8svWH1zJs+btVqPG6x2M+LAoxcyrSrJGFK0BG13Rejkb2J373AB6q8h2VSZP+WoAVc48Ltqb2ZLk5aSCKIbbvPnFpydbRt2Bwnwh+3IEo6icNn0QSLVwuIJ0LrlcT5I/MViQ4A+w9cUHufCVmUASQzux4/4kWiAAv0MiDL83VTSyUizMzTwvhrdeP8iy1luLgBY1DUEND05wRf5JeLeLOjtkeDJSPItYxOZSDx9XMEj8NTCZgqvEvTvFtVfndxOaHbYuIAqTG2pYCD/liJ4D+PpOwNnSUN1Wzh/NoV4itGdXls1EecZBDkz3E0YCYIWZz7BujLeSS1JofIfRnPZvlo0vS9Q4vVd10dDJrdWOIClFLz+0hLS3wWvN9LfL6JXdxc2SqR2mcHTre5LwIW7WhI/xLIGJ2xjcK6QTvK8hEfkUhfzi2ayQLeL2ARTBRDHUKqBekRfE8NxGkFQsHI0BBdo9Hal/eD+lrmaiLUJsCHPWce1K05/ViEqfxRzkewCWVI2wOhEh83WrOfKypYm1oZYhKHvUJytQDMdA4hraG+tBvh/QygolS7Ni5I3abQfCmfAKMoPVzhSXlYJDd62As/x6D1ep51yZ2uE6ab6OtyR8U8SBo2VNZKyGtROiO+pjblPST+dD9J9HDFCxQ==
    DB_USER: AgA0KnPP96FpQIk+qjkNk+N1MLW2+PSUcc5x+4fu1xZePA0YTcyzdfkb3ZDc88FnNfEWNfbLsn+wZ1X6EIdRIQ802R3XXw4y5taA4cZ5KrsiAdnhpKkWBi6oiU4/AiRxUr36Y1kkIFZ1WdBp7u4xtqXWN8rroIIk7RjaUk1B5J5051TWAIZB2MI+T3jW/u8OglnCkR8SGUeB+y+3uIdWnkVepQM5Bs42lTxHesSxm9NNxnnsfeoy7jNls8zcRbeviZw6ZIeHtQIrOtneJvfUiAHbMjBXhG+nWcnDeCDKLKfg1PnGOYyFcdohkJOmW6Oy8vJlrLolOpSxL1tTtPSow+ctCEhGJhQUZNkmRXg+0gakzFYTyb4keaoQHx19CXJS18X/5J9SYQPmGTXfd2xTNqGS2ZQeEnTqBaKAf/iPSTWf+j8EOZJbZ9/piU6nMXhcUVjjjKEyrhdWMcv4iOVTSnIL13uK300r6zpZ14Rw0Ehrq9sJSBPjXGSRaRm78ovbV1q7oksxl9TVU1LYXyCumCmIMHEWuY0DTgPDkYZ5lx5Ol7uMNVlAP59mfVLlt8hHkY1sa4vYVVL14y65r3UU0CZ8+opelc3sMNh/VBPUlIg6s577F/MVVv3FO6V0CKtzz6x3vgDtq6kpQ0ZlnhHI2QrtannOkxAI9mxBqbfIV8c9dV/NKzHDtj3Ou066UX4vx1O+pqD/
  template:
    metadata:
      creationTimestamp: null
      name: product-service-db-credentials
      namespace: prod
    type: Opaque

