apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgAY41sZptizHpYCPZvT2y/l9N+sDyCKV1b4fjYpl9ldNhYUJCK9S3kW8y8xSKYAtZuysGD+LDIJbQtTwE+avF+76TSW6KKziKm01GFqr5p9s3GdMotZxkxzBYpdzsh+5oON0KwGBcx3lK1GjO9/+7HbBdnieiZPX2+MRZ/rGDFX4u6X1BxZJXvavluM6odN2oiqGAeL93QhedUSIZU59yyAF4+XrAxp3A67806wrj6FoK4rfDWw13/CggajeuoHICXLBbxO4wS6kl5b0HuR85S8qyzZpQjM7YtPnnIwJvrIdlrv6evoTmgKwfdMSfShN5nECtaAKS66unSRwVVvqOxM0g6f8mNQn+gHugP/7xy9jA61MNVS4aXeSjuXc6Z2MS/FTjXHoU4xyuIaJvmyORIY44CpnfVCvnW3+ayr2qopPuLuBLGrpnyHjk/JMXHv9hZZH5tFfcwWiT92gxjJ4E9tHqF/fIfEW7ORfRgBZBnYK5Tq/RlQYmLcHZVcQeX4L2i+e3b6PRxQudfxk7fGwozo2w2zXuLhpz/RVjnXGFczxmz3k9glxNMc7u9AbuVQTShznfFRayEkKevnVtyxHvs35aoN/cMv2Z/zlUwcvO66YbG5AcoIwm2k9BT5p/JjR8UVTjv1jy8MtonyrRL4Zov3OAIwbhZsp6+rpnh3q39tGz1REO+2qW6joi390jraFvL0Cy5NTA==
    DB_USER: AgCE4u958Rzk+DxXrjeUgQ3RNDcKIN2+ynTEMRfcdSw9Iwcbt/7L2w+ULSWZ2SiA1MB3kb9PLvKf1avTqy9wiB4lRgJVorRje6gHm3//WCqYWS9fYKti30DAaaiJWN4a1U2I3Q2QpeCSAMXgjSGjUx65qGGj50mWAPg1SmE3DWPyKtE0tZFfJOiMwUQbrfTvt5jL4vSvebO5B8GYxfs2SyplFPjHphhrSYDquamZL5YqmdSgEUO7xMhgRogbNBLQWlr37izpQSpw1qvWRha6ev7DegSFK1H3vGLkKi0i+FnaHOy7wVwkbBuYMkGUdMNvUwZ/YZNvN355c3jiMdA0i8Hvm+tfJI0gV6wqP8E7O3iDKq8K3lN7xPfFbBPEE+rDvx/t7lagUc4Tp72iCqKJmGu5tFaOLcIZa+yhdfUrfuVa9gYI6Sf1D34i7FuBNDVBFLHz1H3pgce/cw6VE++gaXSKuJrPrrop9ICDvjzK7HOpdu8OGxvmDrf3IJOg3Hm/dhO0VueXLG9r1YLUBfYk38TmbzW5+Z3qob47Vfcic8wnCLWXsNHCnOiJ2InFQpxBPbKwWyQb+ZzcsUftQFhCbVd+4MYnbwSCKY7cxHQ7dZM9KreWbyLwo8wKgeMA1kbjqLc97tM0ZrJpJXpcXUez6flK4hpXBW7zdfq2Xsp8rNyMeFsyxqyyXQHQh7DypFmdHoSqymmX
  template:
    metadata:
      creationTimestamp: null
      name: product-service-db-credentials
      namespace: prod
    type: Opaque

