apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgBDBstWJGf5MloJB1CHmXInxFpt2RQ8z8o8MfSkeKMstLduPYN2xRtXC14taqmG4KbToCcBPzseey7ZOm+FgTj/cVXsMVLknQZzWvZc3fwN7qEB80Lbk2xrmP6TWz4LGMYiVfy1G5IEWNpI2/RGSkrSIU1NTLFUXv7L3tYuBjgf3U7Cw2FzYm1bEKAx/sbJYFYrZFZP+a3bQE4C/vt4PTeZDjU3jcZOTBYbmDQzCxZ8mEJSGedUWZ0RHVnjA9P1+Svdb1OBQKTj7J2lRwFGNCRaJqtZCOPCGWAHbowSfE8+zbL7sr9dqVuiIx6T/Ubrj/WfvqS5UcOS9PFZEHqDlkOcfCQcx3TJ0E7uKD4nTr9W5fy7HVBAodvbymfLUhXG1+BYVhIXkw2Ae4xc6Rq95OWK8opkW20PBHes4CH8c6enXQedY3Tcjxu4K0bwJ45A1WBbmwu3Q8VW8VkUPsrlhvd37PHC/IjY5I5I/on9wzYfUN/BLLMvy0Qk4AR2Gpdtr6KP4WJcSj0bDbbLatr49BgPab48Ly5vPFdjoy7xMwdgyFLbBkYSbPwdGQHpYi75dGqLELpDn1kpEgHoLmrzfkFj3/ZVFohJTkgcDD05Kvkeoq/w0/8JQuH0iWe8hTltm4YJ9dbTAlsAhgRqXYy0//YvRuUvEm7Ond6gNMPyRiHxpbAc3yy5ymzWaHc1RCFTzsdZYxdVVg==
    DB_USER: AgBs8aQJUI9uAHvF/0dhHPZEdGNkLaisTWb9oMIIycNIlIKh1SogCgoJcz9R0r6U6I0GXeJBzunNAbkbujYotWV/V5NvV3INxEfz771gwITmHKUtec64nGQiP2Ls7dSvSw6VsVG50xvBpWemkU3S37gyjf8qdHIEhoIqkZpQIT6wYxFdqZ18uWgwx19Wf4QWwcP/oekF/8ogrqTVLjfg2dR2uw7ITAvZZUVqYCqDxsUAZLCCoe5vAT/mXt87+R2Bj4dxeWu8FipXg1YbkOGAVPAKDlAtQpwN2vEKViWIFaPGakPVZHDlXtUEkl1AOFw0snCtNMbX0UOO6p1pUReN1WwPRssom31GWfkwYbui1vKoCcXqphZepusymfNYlyB8nzDtg3F6hyOaWDUZahb2a7oPqGx33Q+wRticadfcfXbtJIsaStjb8RuM0xQCllTV9T1/YPfEy+nnb292U2Jr0IjCUqaPaIW6GrhyPpx5DeIUYtVb54Z4m9kVHqri54O70S/nNY4R9Ec4cp3vnzpWxtLJqpk4wMKgQ9fdfeAMDv5D6ZLGFd827NCvXxbyoEwm8r3WrvDCJwGAcssTgCyDsnFPRVyy8Oh8ulPFee2S4VtjZGrekEH+q5I/ZRu7xmNEerw10w/BWP2JSL+tJBvPZebUJ5OwOA+SKxxlWy02FwMEHfAr4UnvEI5cpGVZtcsvcWmhIrHT
  template:
    metadata:
      creationTimestamp: null
      name: product-service-db-credentials
      namespace: prod
    type: Opaque

