apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgCJTbmndjGAu+x4KX8TuAhsmdgZZJQqQA1aqpjhDMCfN46AuqaK6GCvZ3k+xh7lx2XpUGMxcZTiYkVT+NTZyjwea9ZHicQjsMv7VoWTtIE0k+ACkMrHLf+hzLhCRGN8W6ACZSM+pQQvh2SSLhkRGuglt1h0kE2ctqwvwG2UKXC9YltGBCv+rwnMxxriBs8LRfNNHcKpklqgLsPnrDVbz2h/E7RulzSmBf/Ct+mYp6X3dMsYjpcFKaEEyX2QYy/XUG6S5nxzxhiOzZCJHWGEE6ay8NRI3kire+bsCeRIs7HINKtgaykKUu6LAfXpiJZYAeAi//ueiq4reMc/eHJsV1gy2ZA8yQeF9D0YwntIVeN4pRS0BYCo/cmB4xNqopVfOglHugGyUzpeDEb8oIJV95zQ8nGaPad8qXll6ZG0tlOfH28GZ3QBRfRE5dfGyncb1XzhfsuoGXLxth3YzGLo8aq0ZheaA+HWbEAMLlC3ku1Ry5dTtuOwE0ryjgbi9DXZZVjbKwIklmowPCNHyvj+ZxeFHD5lE9NP/cbH4wxeUG8b4P/yqT0BVDiJAgkYucfACisToap4mnsZBPbCfN4ssqxMimTIswBMirfjAYuh+DP9TA/7HC0XYm+AwTNq8M8BCWk3MQRg2mWkqavZi5wKdqhZgo5mUVHKVXLOpEcBebdWzvTmsvV6C33Gg3IfgyZsCUsSqmet4w==
    DB_USER: AgA9VPrBo5o1agH1Ffq4yogeprfFLB/fpy3/Yk8olzqrEzSpEF+3DXVZmIe3yRFc21OpV2RF5w4jjX44EGfMPmNiAgi52uRwfupYeS5T5uOodIRwKmekLyrd8+V+sipM2pdJw7cwXKHLAt55eG/dvyCMQz89w8W2QsjLGdmKfoT22p9cf6i9sCDIpHeEeS/TksLITrB9lNfL+s3amQyXkKT0LyYGA5INfVmoK23Aa9XozI+j7X770lesFwi3SixrjjH0cxduGEfYMOtXKWIbQWamRc2Ef2msWAiap3CnDRte5rsZOQBqxbI0/lKEuXnl02gxELrxs7pnc2c5qrwyb1jdLAO0pEtoLL0XPftQacaX7Zz7EZEdSEcJfV7/x6I2gJEnVm6/auvTATVi40SsqIFrMYkX2rov1374ZrZuDFoNBY///dPpOLDGcnNyBXyfIPXXBl0ygag4IYO0uiUeKvyGBpX0G/JNmbPUyvooBrBMUvE3EgSwPWu0K4LhhXwhbFSSDVNBnlwoKyWV+KUv7ZaMgv2y3QV8+mtNX9uDfm58AExn4evkXsGG4gqvmNwSexVZm32oB3yk1EpHvevL089ZmYeFdvdipkvWqTzmKBlcABDzhZZ8+Fzqd3cYHce6I34435b9SVHUed7iyg6mPwbAbe2K1P/4dCszXGbmvEWYEvqXlF/avGNgUn7fQTSUYKOIz11h
  template:
    metadata:
      creationTimestamp: null
      name: product-service-db-credentials
      namespace: prod
    type: Opaque

