apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgAGaQUtHh0ph2zuKjUD3B1MzanhQC0hyuiNL64FiHo1aNhptlm5a/+juNJRbn7gNKFFKCD/7dPfHobfNyTuHbMVhqcdnLae628ghvPfc0HBUWYFk1+u76tdl7bI9ZGp7aeFFmnSm133VlE+4UL/UXwUJLGjljQ5811pojgdRlLO/NYOut0XaUUSxP04Veg9ONy5iqjzgSInbHl5VJ8Kc2KB6oN0hn4IIO9QK1jBHHH+bfTr1mMw8KBQyYtcgvGaLUTugDKD53kn8VD+uQYXVqHoYVmneoxW5fPSKgI5bGaGHURDJFibo1iYtNLkHqwVbyYBcy+g2Gw5GN5JTz0H4BW9as7PcJWRNzay+BJbJAaticiWLqKlkGmxvpw9HNdO+ieaEumkvU+kJ3iFDJyNmL1xTibmQ3Q6+E8wJWdEYceUSdgGjyBJ4KvMSjLAUyGA5m6Xt8PygyeQ5aMuD+LOCQ9QCXjP5AMCmMpd9cQ1LjmHgr8dXXN83tumkz8g+qMKvFPCKDrmf2RNRlu15EGhtDJscUiG42NvbUuLaW++fpI21DHvjt0an5XTM0O5LP7Crbo/VJJeeHtxEBrqhEoyNV+U9zF/EWDb7T/EBV3guzl5jdfQPo6W9hGxTKWdHsqkVSVHbetIgYLfdPin9MJtIp7pBW+EL+kVAbsZ+pNfFsONWpTvjX5FaqirVw+MgKoLAAO3k4SsHQ==
    DB_USER: AgBKxvijDSR1btAgGS+d6sCF0XErEO8Af0xOJZOhEPjLgqSWj9fi2WMkhpuj0ThVH2nTqsJ6OpX1r2g9pcqn1nC4eKLHOJp0KuVAziDV9cNChfw57zetRorJ58wC8i9tXTb1ja1UPFREqK1LvcXU0iPZHGLrXFYX9X0QO7t7/eWeBUVZ+OKOFvfuKx1WcUcAihFpWFYz5GLGyf4hOCDwhGFaketd83kUrGvMsjlx8Koac7XZc7QJNtgySIIralYUfgBCNZSrSoLD0dXEXhanlLydGPPmkjHhT7FAbVnZdp+OyCru3EMILSUh8G6TmrS88LWdUIZJe2utsRAL9SiO76ifY44Du0pYM4Yn1H036vjo29J11b/X6KqMAtZx+K2LzBUJah58l+FUPI7RII+GiYP4+B+SIhcKUyaMlha/Z0qXFXeatWC8/IGLuWQ0UgMY5rqQdO9fj2PQyDLMZJ79lHRfd1Dt+ZNsUNp9qDDVXWWYQwqA6+OrZ/4qb/2BjQ7nDm/PcO2kkqJ6cc+lxu2yDK8hseW9EIxAj9s62K+1SEIpprbCKyLfdBmQWqWaBOBcEI0T9QW94rEISAxm5+I1mapwgkK+S7Q4LPtxLjpT31k6oI1gJ0jdhC5X8oBd/WRBqgsjjzpw9Ub2Ab2F7RGJXHshxKY09xsGIedOaLLFeLF2pNivdShdmBkdde7kqu8szJkmi7qH
  template:
    metadata:
      creationTimestamp: null
      name: product-service-db-credentials
      namespace: prod
    type: Opaque

