apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgCSGCem0Vf2I1UGFJP+ZTrc5wtirvtQnke71B2vRLgKxQDxk2Rws+Wyw6OlaQFqzyHUlmqaEh3zRKLRY9JegPEHRgbherL+f0eqh8vhI3aao48W3UCr//qVzXJ0d653RHjt+MrqSXItrc3sZlQCjFWntw2dR0oJhnO/FBhbKuDWBpPfSrIa2KcLdQxFJjOCmYKbdktbYFaPkElHmsRdn7Sqj0wkrHNvXADrHD3ucUrOyZFeW+kW8Ay+WHMUOZ33mReSA4PMp9uH6tBxl8QbasVZzIp9xUuuUqOcSv0pXsj8JWc9PdokxRnVTsrJUFBhai/HbtNEIN3k1IKbfTKSmaZtbdxL8rhVD+U32woBOCQEXH5lo4TzbCDsEJBMYCOWSqXwwnMdvUcAklq6Wv4vHDn8gSIz2NxZFn9p93lv84/RGm01hBfIP/Eo08Td7ex3n7C8m2etKclQUlQ0GeLGp4LLuJyYcSR/fupXlKWvYfC8ZG1WMpgNNGn6ksrk3lVyV3Xm5lNY+KHcg5YVBrEB7EUJsqBrw5D90yXkBhiTDs24bJo6rIpgWY5xir+FAjrJqahFtgF8RfMF/oRNWUuuRyeKd/HLfycSM7stLR1Lacg0gxPHSEysVCwdKRHybGPOlvbo5H1cyHqCt2DptyRtg2AoJdAn88PKmPdyhPE9BT25GM95jJ+xjfEBCFM+SrP+TQAtXZhtpQ==
    DB_USER: AgBEK7rhRjmNxi1+ClHyc57tk6cukt17fuef783DyEW3NBtatW8GdfYjSuMToHIq/V0eZ3vwtIq6bJ+Rz/BWQCDALEfUoHj314+79WBOQxgU6/guE0cUQXZt+eWsYDmTm4//t+5pTSXo+QbHEiz1SZ33TWGper4WtLThizdcNwFTWLl9NlrinTjqzMqzGuVCoa0Jx0pG2OJbKi7F4D99QdDx5DRqcXLoaMcQbdOjbFevXpmJjoJ/akM22Xdp5UTVOGe5WRIGxELlEvrYzKbHB4RwQbDvt4Wq2CUpMTZ4AUTc0ytknMyX+C27DAKrNoovtad1oGTJye5YEi55yiPj91Gfu3jZpfvIhYSN7kX1CGtLDnyblOszz3Sqo+ytu1O0+AWHZzDA0aAXMphbZefGNY6+fKZqmT/zF8maPgM92DylZW0s4Yts3ADyTeGrnlf5lRv+OJvIUyDiKaVlQuqTipfp2IEevLsOFWodu8evfx3ZVt5b2HBSCqTUrNOd481PM/V3pOf+Y8qK5cPfO159VxdpsxzkMNa3/LhcGy0fP5Ud3XG/hwYUS+fdVe5ocfLb9ZcFDTxJmE9LHx88RCcfGwJ8ubZ4vsUQCDoeo1zeT23+khC6x6cOv15IAeOkRWjdBhXYSCYvpYenmvltsUzGN4lokfR5Ozy+ncy8W1K8OWwTxOj+73xT4qzINU0nGnpk56ba7mko
  template:
    metadata:
      creationTimestamp: null
      name: product-service-db-credentials
      namespace: prod
    type: Opaque

