apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shipping-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgAlJcc3abil0NC2f3681xnowrTiGCBtNjAoKjVkThH/gdktCSoGNfroBesoV508ZvfWnGpEkdvHUBIxDGf5S+tbiW4KlspUqPPRte0eSjtxCT3oKmEbWx/CuyGaLUuV5Svy0fbRgXrsEapnpVrz8l5RSds4Qo/1vwhM5Bp/AvPDU4Iet2B8EssIN2wRGPzZ2n9fy/AaJDTa8h+nj2aPbVgD7tNNsh/mDH+HAcw65YhgFSWgxFPQ+rlDjKGAp9VUj9YZCwC12YFlLTq7A1MFcnzJIgnU0DUKXmWXepTiBSojzevp6g2Plb+ZQqtAqXsPfAONxYWGLle7ds8fkSgrGaVFYIccoc2WQ5fP3Jn2Gymyk+N7Q8uE11i+891bRCYim+OsImsRrSPIxDuX4xAN1XaWvuRk/hsIvOMI0mWZD2F1Xq6HFM0opfBFxQRfQwrFVec53E9LHZc/A9nbWdLSoUWrSLVSDIv1x2LEXFOb8/KMbALn7pXi0d+jhsl6QS7AVgCGLL6Zh5oFOEC8DUoUP8vI1kdbylDshOF877j6HBzOI9uklCnfS6Qm7Vvkz9YOKXzghWh9MofflAMemdtku0r79faXP+pl7CJFRHvWyd4DLiKwJ2uI3HhhPgix3RxYk5D4nbyLIqnpcgPXKGHpKiCzZ94cTA7pmfkQnUZmfN12JX2N6AkQ0MMnZKgUDLDmN2sx+0c+Iw==
    DB_USER: AgCbyW1LWIu5vcnWxTNeVESh1KLc4fj6NEOToWMAfXOqkCZp1BwFvdUAqB3dSDPIpdEmObxesw9m4LdbeITr9nJbtNEVdl5dz++kmT3+rArFxP2H810BTVk2IL54adV8R4oKohWIz1yGWN/+JagYj1B6bLV6YQkWuoaZ4TrUjnyc8Xyi1jjoIR2Nrvkcs38z+6rjbSet6hJogeAL6M7f6Yg/YFmFRN2og3XP4C1UkIiveh8X6VNaCBCzFv6apV8KPI5+NRhDK/A6o9WH0IE2GB/0uOKyFQyDhrMpmPuspSSZGHWCOGyW4XSdZsLNZCKiibdUAt4srDuouAnngsMsnK8GDbPC3h1IyDlZme4PkrUEtBtODhjx/dLjcvA/Z2jMALrN36snKhV16Q1mwARt2/t0VuNQMTvxGv4uaF7Q05kFsU1WV6Ra241XHNm6yuQy2krYA33KDatSxNcTYAPr56pLIx+4UQqjS7AKKzUnc7mJBshKcUjv9QkwnhoqCgMK9ZJoKwsnLDIivHUHWr0/PexlNMsp0SVH9iAJHa40cxBRU0tCh1vLYJQBueV19rgVq7CPw4X+/EH4VDmJSQO3yGDe96XfNHHG51qJ3v7oHD/u7bT5Pj0avCmfCfEIxk96bUkfq00Xhl+7EQsp1i2jGqXOhNyUtiej6SIR0iCnt/cud0sbNgCebtNKLEqMQ1V7eQKwzumK
  template:
    metadata:
      creationTimestamp: null
      name: shipping-service-db-credentials
      namespace: prod
    type: Opaque

