apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shipping-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgA9HQ93pxwFG9lJ5QxdKe/WSpucZyo53oF4qCQ9+2786eW7VU2P23UpwxYnFpFGJKMLtZojc00q/shZ9FACjGb8k/Z9s+9AjmybJGU3hWEUfpO6xlenMaTES7H8h6Ow5/0dRpTSTmomdwFQZ8g5KbQzrJM4KMiU2M+pu432vMciAPx2iZmuzDQORH+s2w3SKUGQPkfh9/9q3yf7dii4rlrY/3YOtHD8lr4q+ZL396g7k+8jpbxyousM5VPMo/iXB4WGyokHXAuRsJeAYJwOJI3W62AqFK0Wtb2sHm0ch9UARoH5naBrJcErrEkQjLpQ8gLWPa5838/98PAnk+esnTGOjIXaTfh5uTeK9NES0/lpzwM6MKuiIfjWLIFq7vZSHw2cx2o0Zj/84qHW78iSAz7XZN9fBsd2TPcPaGQb1hDqKGuv2OJFC0sriPKMGAs4QwJzLwTw0Ul6N3B4EGq+2fpOqZJ/UcwhuHzl5ujD89EBwlNbopRstgCFtmebmYa1whqxig4dXSaS6EWXf3YxPLi9SVPbyKsVwLjdCAGIQ9PQbX4TebyOUYG1dvMYZCdA/jAG9nrxwcHKVM5PTzgum7wi0TzZYTVz28cIQkhuH2N4GSslrPfx4cApIFVS8zTXxc1i309dNEfZ1NiUw3ZasSliLc9aKIBf2dP//GsyZyZrueMTDKhyB5p2I2b34F18W9GlBH7Nuw==
    DB_USER: AgCkOyccZtRuwx/hJvLJd7zjnWPu/GP+rNoOcG1LZpLoLMUyez95fBgptAendka4IZaK9Y4D/Fimausu5XwTIlytCFHshbcBgq02jP5QYx8x//YF9a9895DTR+xj5PtXzjfQCjMJJGc4gRufv1aVpsYCij2RuRdhiXxItPWFWoq+qaftYHdA3+pS5UEXL2h5uAbXs4wDqnztw4M0BEWX+tVrm21OwdRdYW/62FGn0wejtV/VWYgtNIkfMe9TImSriH437WQOEs25uOSSqr1IWdMuDh2WBFdMaErMZC5h06IsYf133SluN+kUUqs1nromS2VZTRawlgMPWRoHdEdKjXD5+mtGcskJCP9Mbz1ZiV3PTjgyJQU+Ub+de6hF+AIXozCrwBIKmMRfRI3uXCQwt0JAQ9YHC0OoGqdo3hXnPm0Nmjqu0pa0hMXdStnfOXoKzUmpXkRHex/SxgoqKcnOw6dA/MAIxty5GJ5VfDfRiUrkWPwvVQ/LV2C/RvPKxPvxDM7pQruTPrOVhsYG4HzgQuRM3qg20IbnZv3h+wvx9oCAO0w5k+RvCSwImgV7FJiq5g4UFcLilPjQlRjYGgZfyzVH3FPJv+lDhSnyQg1iZExBHlWEIkSIwI+1B6hj6tP1Wy2q8jHHnpTjodD2zlXZDHMcp0hHcKGtbPkLTiLJA3X/sdNdEP0Nd0GTiBrW1zw1n62ZoYRx
  template:
    metadata:
      creationTimestamp: null
      name: shipping-service-db-credentials
      namespace: prod
    type: Opaque

