apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shipping-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgB4Om0VskBTS1xbtAgWfW5C+9qM5m60HyNq5xrG2YO8fwckjVkM1Vy/q91BBtRYavIUz/TuwAOkpn+F3ES8OoFf139IjWO+vqzARG0dAkOsip/W+zk1iiKti4lDPRS3SpQrmpBOVa10PKR6p13J9KViqFPiq3uMZBUiZpttfZAMg8vGZ1l0d8Rm6g6smbzdlcub72XEHXEGW/Qi7nRToVGoGthyNuatxgOkZoc9Yl455UPfcyZUZFItDVk+RULCrwwOB5wgLpNovp0lmt/8Qw+dzxD0tUL0U+8WHUaPAxJ8AEOK5aL3oRpS86KU/KhmRGJGDLrlOF/IK1+QE3Aj5ql1aBgCbIyrihg8F9zwEmSz0EPNW95t+IH7IYm27VYTDfVTjTc4U4k9yXc7EznHAptUJxaf151kNG5HOKgc14aybdGSzVFn/EjSXIgTCnFYmr3OSMSbQKtoi4Yi86RafwoRuHwEvtKaBrt7/SjOCcmsZ/D5krtEf3xJrcckk2OUYHo0oShlCRtuvDMrQEwr22IiXFUxbJEF4ar1OpY/MqOBEULOQLX78VXIJvryXxDJRWSB+MBRnBDmF5Lvky8CtJ0YggZayWR0Hb4ZbJXI8kXcdkvMoG0aPCFkh3bFw+T98+rY+DVzVRrmx1ftuKKffhUDMw/MxQnOk1X/PkXEt2uEMqr2pMXeWWYp+pLhqPsWGhRDqQQeMA==
    DB_USER: AgAYqFgAe7IU4C4KtnfhHH4o7QAEPcN15jhN7uqXV+Qb2ujzDDIakLi/vc7acTUvGZoU03/50In4WJ6II/GRN28BffsIUhmr7ZlXTbX8ks8L7rdiR1/3il+u8muWGIziuyooyEZiqlS2m18Xsq67h1hd9HbnAkBv0MOJT0jXjFJI4jhfeAu0AD73msojSCyy2e4lPX8AdZs5rFTbPwNba3od6NMOoU6lpdtauCVtSNm0UlSZGILGEF5ZY2jMpFwSYW5+DatOLQTbD/Odrye++cgOx2Z14+Au9dI8WR8H13NB7Z4Y65JsLSh3+Qhkw0qeJ0/5XM+BgsfSCrgwZYNOzCZEH3EYEeZZT/5ZHlvjOxRV8k39J35TUAPcpLWtRNIHXoZcxrwCxL3ap7QdGhVkaSuEe7P9fVixrhL/Q1c9Tqw7q9PS+cOMfHCFmsN0yhEzvhpXOZxNucmQjRQZdkdPdAiKi07fqDHWJ1Dq1o/h+Gk6tGtOEGHBTNG4s6GU9bKlh8er/r7bFvFQW5uq2GTk5g53hgMkUE7dQDPliBMPa5FfyfKYECNI9TFDNpfL9bgG4LBeOhy06EcOdEoVeq8hHcS9IN1Xs6VR7RzmqBFnWKWF32aF0hl0j1ip8bhpNZ+/hLryp5b28g2s5A2AgL865sj//z1TWMyangQYKYwGjcVPX+WBtIkWW9J8RVMoc+c61Cw1DHlz
  template:
    metadata:
      creationTimestamp: null
      name: shipping-service-db-credentials
      namespace: prod
    type: Opaque

