apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shipping-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgAw/mRm2wFcHPXwLQ5U3HWXX1c+LGnwf68CXxjWZ4FBA7baBtk3+/uqMGO/bsQZ+B45czGy8vDTTX5VwqHN5yH9mGKatG49MCIr2zff13kYYy4rFkJJX6Nx9yBX7MlLRdCA/q2cwNHXXR9QC3Y75qtf2vDA1YiEERJP0u0Yhf1wnch7ewio51JR2wxipxD5Ym0bttH7YLHbEh0T8B9ybXXcOCPj5dh9G5qsvYy3zRTzSI/ZLDuQObLdgcEN3SPGaXfjPSxT2//bpvm++ilYw7Ll/gtCLSESN8vCQX+iMWYD13ijIFbKxjZVWEBst1/nXlmDTRj65kCrXIGA62SwckT3QX4GuOjs2IrqIvxBB5H8Gw28kZTyB7cQ1vI4pdWl+CHPDpCbk0TTTCtSbXNWol0WYmijP+PBxvlzOt4Cr7JVLC1fwQu63FaZJ9PiqCrUFnLF0e+VRasdlMWDhYZACYY5N/WizytVU+UqnYs5dz4XeJuL0eNJjgo8rNyhEsaDqGf7WeJgAH1fO5jQXlnLohiwGKR38y2BhNhIrk8xC4pjr5nRvpg50N5bwHy7UbabZ/D9YoL5mvlGfX9FhfXzq3ZsaqSCFiEGQGMZlNDCjmKtgYIKkc00kLSmsUhVT2ufT5ExEpkjasMFZXvU8EtYctEnM/pTKlq6Rg9x1GXzYoCR27SmhsiM7HDFfLBYg23GBiZt7rZXYQ==
    DB_USER: AgBHsrW2+NA4Snbw6azxOiQ/wiSuVRjI981ObXJkafT/jSLuxH3ToBLqbtq/LCQDVtEfT1OmpvY3MwpPf2koHvzK7VohemPD+sLWKfhRW8+jgaoYaLb7Cm6OfhBRH5E0Pm1XMRsY1I7TVaN94ntRGmnT2Xh02EROLkpPAV2QisOJGWaEJlL9IfNt7Oa5JAgilIULX5MFf5KrS6o+hTnUEgSAZbO7ruirMl1iOO3w3VtU59KKtd4pvWurTrlaY60MMiibNhQ0I+caZIOZ5lbXTsTtFKA+1pklKrZZp222I23M1GPeePbYThZKXobg23z4viAuTAR30iylBqP0k8nqSi0So8WWDTKWD7ugwde61u7Ao+Zd8TsGQFBZRrUiHr3E3PlBsHcaryLtjjePLZqgBe0dKq0CT5qSp7AktzIqTKaLtl8W/JFFo9WqB44w8/4m8X0rLEE611nSnyqFLPqzItshyqVbuvktT/jMn4o6sBsPW/x5NdcYK0ChFdtm1T+Fj7+nnl4iIYCGBbgSLBwJ3myS4i1jKz1ldj2qVCFGpJIsr4zADFv/oNshdJyhYyTrSqX5YbGVajIAoqgysmm6do3ZLNTXVuODXV19Z3zwRAwxW2DjUFHn4GtIAIvwsl2jrvk94A//h/9zgVTt9jo4lovZJPhvN74bAbRleZR9rU49uTajRfQ98stS2LDlnmaSCNn7PF3t
  template:
    metadata:
      creationTimestamp: null
      name: shipping-service-db-credentials
      namespace: prod
    type: Opaque

