apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shipping-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgBmcLe0O2n8T5hReVER0yolZJJ/f3ETSK56mfR64KNzWSQJwDs6uKPooVae9u4pew2meoRMjk5QxkcGGZdZCuX9a2nCDDDDJ0dAbsYcLTEVdjD5sD6JtpfMVBvD0hLeJbwxFhKE6LCUPG84rZbw2YYvXuk987dzzx6ytjsGINRzVzeDEiC1EwBk9Vi5676SveUYVnqRSF/JFObZDlkrZw6eLUPqCCzkLp6GDmhM8yBvLmVSFohNnUN+Jnkh7NdyZE3ymLm16w/V3uJOYRiEuLig7jwgWBju+rOqeanrHSeq1tnBHXyo5g5z6qrZY39jmxNYEVzU41vubA6G3PGeYAUB3C4lEfvQFpLVBmmY2djJyvzA1aIngbb2OU/5lWbgcQHmg3/6gtrAfQ0diJ8cXre5afz5igEUs0WZtV3C61YEU8xSNVni/6tKjdX0+15SMk0pDjnLl2kdcbltci5Hkxx5CQtHut2k44qVtCooGa9raYdBKaxFAL7VVmTMDgWqJScIsB7sEybBeCaKYyAj/HSUSfC8/eTszS47cE6dslN7bQjOB/VxJ4JxXAARmlbuKPEa2BPBZ/toPVEZ/aGPWzOMhA0KwWkVgX+LU/faBOtX+pRm5oKVb9x8ijnreX/MbzmvDsAfeC1pxQ7DDlrm5AnSseu1tMGcl0mEi1DTTwc6vn8OmntHcyGcKsaip447Qw703Um0KQ==
    DB_USER: AgClky17SeGbAQZMBG6WQ9bazDbF6teOtuljGK85JuRM0S+xVxNzpCyQsPSOxgaRFtVTacAOqHdnWSxNDJJ6jLAtvWGVn33V9M8TBJ2pqeE3YkTidRaI4lzwPLuYWOq8VhzMkCZ0UQe1eWzDbjTxkbLUVz4G166+tl+u6qG3i8DiOt1v8Gk/ykDTQ4qyRArG8JE2Ibj5VwNsWXdCcm+Ky47w0tQiBPH9mnPA+YWtjMijUyBJDknNgEClee3URVytQ1ed4WRFOJo7Ah7LygW0gnB9DzUE36PaZjehGybOzV6uH3jKh6pc2Kf87quxS84y6bgOx4eYfcbXifVvBhZbXMafAIxjp8kTrLpx30sQ+gM4+P1Xinrwxa6dh8Cqn8NMrK5m2pXlMN1RaeVeNjbfcd2UxYARoC6dF+zDIquYeUd0d5Qw1w7mHA47416Zb38werclUDEqPTEOnqjtlEftz8yud4t+t9y44fos/W0yjbfvEJsUDcKvgCDZyryeBxC/6kImgBUdJ/JXdJpjw/okRgm3j+clzy76+fGDgHKyFeYiW+MZuF36eUG9rwgYyA42n+gQ/aL0EMfJ/0TDSywBoSqcbxioDPaj4/IFzXGnpwYEVLWhrBwVU9EtgVBgYjbH+AQwNwMLQ0uIPK3a1yoOJnHFt8KfAlR+aKYiqc9YNVCxLakBTayu7gCS5N1Sc7uDFR/XbnFN
  template:
    metadata:
      creationTimestamp: null
      name: shipping-service-db-credentials
      namespace: prod
    type: Opaque

