apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shipping-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgClU2K2O4gEYSxHKG1XKxCPHdjIBh8uKJLUzptJQIiuvaJ5o3zvWQjMCAzM/doYT+BqBGXJslnFle7OPUJXVFTiDJpozY5jp/p5v7EJafOFhXeqL/ipoGqAKVDcWsk0fcfMJNHAErHDiRwphqkwvw2XhwmiasoCf5MDTvS0Z4AQFgRxBS9oWGbcq/K8pLrDEgx63Bn2zmvdGpjZ4M4DgWNzQX6sh/ympWgQVQTZDAMGCFj01MDfgNMs6k3HbE55z7xq0ChJk459KGYIITPcJ4wNH37DIcE7lB+phmBPM7sxcSMVgIgiVTcba9wkV3YTMYYal5S6E/axMF8INqcpznBfubY3t+gYV6xkIJEU02kox/TPfWWUHWLkjE2OrjqTcpLpTb4+BeNJTT8gOj4+t6gy/h0ugoGuYJueBJIbRfdXkwzJNkdkLiPAFGkcwP66YaFJ56TXThjVcBs04GETJ1vzvjOKv2dAn4iFbMICyPgztN5BquQAhUBn0Ew6ple6OznqOGBmiu5AI9VTlwS+V4sQCrSufKD7nepkTxOyiOJ5TMHCVQ+7uIKuHKDiUytHl2XbYClJrNhyeJHBsXBbDobbi/Rt6Wd5gNgL0UyCO0dfXJiV6UTf/F5dtOwEqeznqdpBM/OO6zKjWX1G2CPnKV5trBuNQlTCjy4CEwEaVsuu/s5kNFvKrLAVuEd/WuAilG9AwJyNHw==
    DB_USER: AgB4vQ3MnLQE7nr1snuGcsUTwfBK857VeskbVsIAyrB31wY5AqLe1Qfy64455rGtk9mgQhNghC6Eqlyp6jOHGr6T3JpbiCeSId85YksaK71Bu98qU62hBUG/lk4rVELwZdk4zS/KAfnNoZEyu0ayo8TFwscvxVFDDShgrhlgQ4nRACYUYZF/QgO6AiP6O8GOc/8s3sVnGxHogwve/l69AwGTy5NlFzaXBZAYGLiNplsbgGZJzXdDkXE62nXbP041B7C651Z6fq8Wq3dKcJVPjLccSJLp9xVr4gB58NM8h3e7Lkyp5oSXHWgoBkTr1zeBZ63kPtjA4o648sb2SXqgk9HIORldZxGbnFnS9OsC5vBlzVcPoWJBkjmGbLIMmnlQsXAwTw8vICy7FpnK8vWz3uY5PjCnCQ2t0xLV3ZtSittQeJsU6Uis200+rhPrWBlm6gyIyVLceDFzxaMTrhp7Q5tV7Ef4xbddcW0LgyEG3ckBPevNyrgw2n8P4zK6pHeIUoqXuThEIOyGeqN8nglwzWIzjjrElEHMgLTWXk0Zgfo4zEmIOtr6s+zb1lqVEquaI+JkgLdj0U3mIkwCVUKDdo2HnGQVNcwx+b/YTwdtzhdD2EKl0uS8AGjrag60pukpVQilw/SYGS2+C1kCWNgj1EIUNGpgs0AVH3SPc0dBrF8Qn9dNXvgosAVJSQAo2401iTsKSYP4
  template:
    metadata:
      creationTimestamp: null
      name: shipping-service-db-credentials
      namespace: prod
    type: Opaque

