apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shipping-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgCSE5a563s3QKpz9BqEQEwF69WPjy2bEEwD3/Z9ZyzplY/9yK6PSkTnMTcL4Dhx2sbsoiGZ26RDFR3wqjyDrzbphbDZ6EcpaHdp6w4shG/XygAzCWySVD2KHxYcUrrcozqBYMAsk08xpPVZptPqn1ZRuUw93IW8wN0mpEV5ARf8NTZsD+oHBfTjWoptiMZXGqpMHMKm7MWQg5bK5KZfP+2M7z2fAzGnOiHy4AXsAbxDK520GrGXSrnhiytKaR2kfgOxjo2pJmttWYeeROhZE1AAHFE/ZJV9h3BX/8ICOcjq4+yrkRkTZirAsR1UpBOUHktgHjRjcRbzbDkLKPCgiQ+dDswcLCPVWY+X98wdDCMuJpbEt0PzQWC3yq3HQRWK4G7di1bWnJfRbPo6O46dY5HG/CHc4lrTxNk0QOv3yKZvYWSEm+pcrv/bwzEsLkVTfJ5LsetWhikSmdeEj98pHac9kL6rmfP1mBS7xewf2b+/qxkPo700FVIFaM6ZTj+nEV3Rd5Ij5FzOJ1bJ2n6rIcKp3koVk/EA3R5z+PFiVUYNuKeQZuxPFbc/WUmSXMA1/Yn2zL+6yM8dvQ8GRxsRg7v13esODnhdmBVhutkktzQ87S/E5QZWmjPnfdlyQMery06/EVHo8sc19hNBVNcxFZwZ3bNWbb2WBNIjszgfNyJVK8zh1RkppYqW0cQjAdzjgT846jNQ2Q==
    DB_USER: AgByOLeL9rjDE55ntAgr9waA/CiOjhf4iKCbOjjzO4Pf1gBA11vfNou7ErZTYwJpjrmr+iAZpZj7ujgEI4AC772wh0KU1bsbi3BHOgm/zd2jPvUPh0i9C7zFPo1mHPK+K8HtWbw6jhX6Eu+nMWOfjp8ecyV1boeCL2pbiqmu7Cq3aG46o81P+mjT12BsgUbXzyjGpxA0m7tWDiPgsh3b1Cbhkc+t5SPP2EN4udHU9405r/YH5h5/TTT8XmjacnnFuZYpnVoGJmrvNEViSL5SzPt5uftHTSKXXT4H8rcSqjxJwp6Jp6hgZp/wgKdKyQIfM1+OTDKlpxAqgIjxJMCNz4V8FD+z6LNfFYzLiwj+zkO05X4j8m5plVv2Sj4cGo7Mfb1MxujU/1KECQZONdoqhoD0TskrPfuWyyVnbl+ZQAuYTmDSzXQea8EQwD4Fjl5JUOuQKPtn5LzMOnDDKSOSwqW36fGr6eK3wM9MyXo6MK8t7bfje/+y+/No7u1bgAUc/mXPM1lLw5Ayf200SbH0a04DhLmT5+wSXdMRrlZ3kK3WW95SvkhTPmgLM0iyNHlmkfdi4AvvQgHg5EuqK0GUC/CaMWFk8nb9gxwEbo90TS1wyTSXC5wNAhBj3gvZeG4MXw4uof8divABfrie/0NLPhJiIOBoKOefaz6NRNXWNsnMeLQdiJpyOxA25d21gH+uAtVO7rZj
  template:
    metadata:
      creationTimestamp: null
      name: shipping-service-db-credentials
      namespace: prod
    type: Opaque

