apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgAL1EAp1ORBEphl73u3GTPcxTLRItEso5ch+KiIT3Q1Ziwn8cYZ45O7eg3bl0B1a5sbuvy5R+SrIDu8WvcVToyIH0JQiAceewXD20S/vGSRv89479drPEPMYR9LVG5NLAsQhVMkuVbLrV2wuC+7kVqeyfcW3YTXqLGBYv29RPyxKvK/Fm/lElrCmXxyI2LYoXJ5bqVZGaYUP8Td5e0U6FGVugG+samh3wawOTeUBsyYi7lN4Q5ivhQLb6p4TIaaZaGwcvq/G26MxsWUCuMAE94IRQzBneLSMflDHJyfd+O+FBFhYwOZJnawiun3D2sspPVmYNAgtJCOMKQh7GO5BJubRtt1F48uhzECnKYZIj8+bStj8hNXKqVZ3DpzhkGbGe6wAUCh6AnxNSue1jAfgYxc9m4wbKNGD4BRFSLD8tvjaJicXBUi98SAHK2hKSTHYc+T1tTUHODMWv3rD+ojgO3JMwxL8/YpB67Id8tnqPagRmMMf9ZS4o36xTaFQnt3wJhm0mlOxc5nEAidUQp1uBdn2+EpvF/PvBt92gbX9rV3cacB0LMxA5FWLzfTFUTmdgGwbXFd3TaCuR8qjnqAkMaDd8W4B3/H3pd9YFnBnu9Ddp3Ico8o01/v2KHyqINB3lPQmoWNqJHdces6OIU3Bh0NATY2OobODTUwc4jSCxSGNDtug7yrWhZ/bmHKSF0GRjsWmzuvsQ==
    DB_USER: AgBokojGWn6ssM+VfMulXni37MEFNjw1XXLN8NAD5fxRKLKIW3EaXD8Uz81HlM2UvWLtA26HzSK+9PYf+r5UawRP1WkjttVDXKVgFLJEa9YlayM5lBOAn4JUU+TjeUAguQmbyWQxjkluxxp+eqRMDNGbNithh9jtb+Y6xI0hQkON/kaEfTYw+2WgnrLBLthTX5AuQOWYoF9oSSYw/Ru6ndr9DaSLBGuWaDY8oNk1mlsZnF0RL38u34kCU21pBbsoMOtr8gp/4uEFbXPyjdfmoydElilQh+JMGuEuB4H7asXn0k62RvAGGbFZqYrlVc8siblzBM7Bv+vy8FFUweAC6EiQaxVZKf49Jxlbf4zVl+cwdpfIAlcOF6WDc9A2Ft/ftYcy3pCDuJjMcZJbt8I74PppxljKY4KVfLCzsNmMQ8ROmD15MOUrm7uTximel3hdWEIrB18uLaL+SgcVWJ4RwmH5trh1ClTSEfpv8VTAWJh1CeJTwb63/7Mibn+HybpfyI7oKuQCnL9AunlKuKiFJd51m5Auxa0PiG91IFXeBoQEjWT0UiuTm2P+/y6slcHrsKd1KtwGuXgWJ+C/W88/3WztGxCywkCE3PqQpdoe5lcueqI487p8O11r202zPMyiTlCfkbxHZMyILD8eHDetEXRotvMIQ1DL3jSFuDnuHLA3FKJwuoA5BQUnNdQU4yT+ca2Qmklq
  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: prod
    type: Opaque

