apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgB/zUrWzPNXih4/twqKAhIJ80ApAy+PeO2T7gzMYzXQq5Ab4xzZjy7/rBz5vqKbj0EZs36A5TVzcQe1Tfgrm0uIWzPIWzYA9egLN4IqZe3xb18ygDJnzop2y2fRDQ6nU+TB0Rq6qIL4jhsdadKi+1aZpsQtU0saEVuluTUEEf/RvMEV0IphCc56B2KZAmHIGessrxlOhIjlcJDp7aoVihaiCaqWvLykMOG51dRViYxJS8EmVw681jxdQMo5ckjyX/99yOsajF6XvJ1gj9Q7bbMDqoGGf435jUC0ubtt+Og2rOafB/c7XqzVM6a9GtO9J5kXR7u9KN4QSF1bSFvf/Y8sY80Vr/RuDw/SakDmGwb77WHefkSpigjkPHWbWDGT6UPgb4nkVGouJ9BcOX3EQSkGU9ijAe8HKeicxeo2X/nrzNNCqGfHiaVZpEkkwtiOMwMznpRCTN6GlIHx56zoRudAVlh3TadSRrWyzD6nJmt9IG4e8n1ji4F9k6VodtS96kyYEBgB8khCoGEVspw50DCs9WexSZDVFrw4h4YhI/buL/1AjFzNuRq3zEZkfjY5uFmhYvoE0R5OG1SLw7jQi4dYBy7MsaFhbxAvxkMmhzlHkqIefIkjlxnQyUAOvsh9QzLRjon8uP2wf1hggEnrf4EpFBG0J1JxwR1nlyqW9wHXGSPvCWyjuAj8peae9+AbNvTbFsTA5g==
    DB_USER: AgCP02NsRWVJYQd6Qvd1uZzqQ5Pqjacz+dv6Fv/kfeFxhu9hoshSnetydv8n9OLhIujdtJA5g1LILqMgRxKw21jOifQKVgKcGykl6PB1+P+Ph4z1c9iGF6KCUZVBoOtorWmbhjS8EMC6MhdPq0Vd3cUhmqW+10btRtFqAUh6u0yyMsSOMiIoWm1ba/36BX35vjS1SgqvqDJ4R5dR3DXjM9BTpXbPqp2Uh5yhVwGIZx5lYCKcysCwlnJmg5YA8fFcIPTzPa7RIPITSZ6vsY/1sLM/ZbLllv0xfx4YFNOI9uhXj4PxdhSqeilQMriSGQg/scP5pDFSBRlsWWqSQvQ8d/D5Gd8JLc2jRiGxrME8h77RuO9mT0f/xbi1h1OqUopHVIKSq5o/pVvGKmpRbd+UwknZPlIUvIHH1VL3y5ujWs6OX5rPerDrWF6sFxgVLQ+prAawFCE0rr3WTyh3YhoQqId3vUjjDUwq2GQSaATcvBZOWxClivv3D55f+BmzkfiEbQUqmM03AdPzmc8G5B3lTDUvs4xH2ZaFO1IPmbe9H+RMM+AJZFjOJk0OjTUJqgDin6fSckNbU9LLoRa5GuZFQqyb9fon4GGzyXptcgsRj5abOmtNuwULC4Ed+lOrA0JOxWzIJbvZCWb5ymwR+kTVQ30Aa3rzK19feeyAq3FQodDU6W3shsht1W7Z57IYDfgHvDHIhCTh
  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: prod
    type: Opaque

