apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgCUEvmFyBTmv6HcRFiEpyuvCJQ1GWc2/XDRAlre83Cwygr4kRJh6vLwjtvMLYHdlSPf4O/GOCl4iRLjoe4gVZ4XVTVqkIdpNv+J/J8nbdZts3howpOPWn0O02Dyk9wium4VsXEgqDFgwlhGBJW0OaAFxBC2hJInmBj2VOixbAqMvjPTlX2033biYa7PGxpm1xTk5vv09d7/g7egMW713FDHgtwVnCO6yZ+mOljGGG7jwk5nEWWcCCVWxLI6iMtnVXN4jqBGlziA0yoSO2PIDfPXNTJ5tT3d7oNSUeBUPQsSXdzxzzwmA/1aKo03ZZTP39g53aATBaZdG5u2TaewghnQSX6UOoV/dOYEeBmoxDcMGZ7Hek8Y1fUCZo4OeJsaLIC+OU7LKSBpCDpgyeQWM1H7sKyUZYGNxtYOTgdRgXAirP0hQWKjnE/rn8bUnGCCEYLiZ2RPD7ABpWj3yneRl3fQyDXpDjyYJWr2amI1+n3TS/onWPQ3mjukMY8DHeg1hGr3VM9xDL0jKC1k3rUlkcp0h5qcyOtCfyfGc/jj+fMjxHORkM1XYmwybwTqpHriGXLmPQ0tDtrwAHtHUvIo8ZRfe1WX0QULQ/GwXGLi6xxWJDpts8OC0tpLB3mEh9+mWvwPzW209MUUyALNh1VZ7pS+tXYllAtthE1ISc4YRDcqWTb6hkaf4l8emGrzUCoJ8H6yj2LrHA==
    DB_USER: AgADDugvkAp3rBwrvPDy8BCtIpHgbZeCi1QFiIPMD5QJYQXUsihVpJ3jmuxbcrHcfrALBmfdmeDKPFryzUI4l7fgsGKejhwSSSck4epUq3jM5KCN++qTFi82eVNoXdJ2ntnbCc/bkddLoOtrzwON30IMm0rho8uGNs2QRgF7fZImBn2SNjjMxaxMV5TihXN7AEwG71L/OOt++JXkS8jfF6yRnLriivylXbrSWL5DdYz7M7WN5R8BZv+S1TFCJi3T6sFyH9LgCi1SW58bfHFzzQp9gFuuavp4Tcb/g0Q065KgPOrNiVRO0bETnVGtD7PE4V5oU/gD6MJjOCRAy9flSqVVjq36EfnKzphZTFfReRhov8jBHM9SaEmj2BHQH4Alvf2NOydJ1L/k4+qOZQ3k0Xj6nh5JSpkJFVdNS8sT5+ldeHhWGvxc8U/fWPFTDLQ5D/pxAyUOiQ38FWqrOpP5UiWawTcsS42BAfnTl3COucTR5qy9wEkpm7imsaGCRoFBbb9ADl+GptA3x+x+YkC+j9SrcW/Alc8lofQ5WOql/rw0Kgx25oFs7theg4oTqFJE9s/G4CsjYywQgX4bcAKvHVIt4PXzBIZOycOfEG9w2GU6BhuMdd7CcEmyGL+t/K0KbYV4arDVOgTuioOrkfL2bavS+5O6lLmeyjNcDe8J4CHWTQ75JPdMeZTLAV+Cp2zNwwth8lnC
  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: prod
    type: Opaque

