apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgCsIFxcnuECADtmoa6hW1FJdPvak7dDikEDHFliUT50TG0z3BCVhHmPw48p9MC/IeIfsipS8JqGtOjX8BjjUwZKn+Nulo71vp6j4O3JU9Pr6kwjAbpm7eOlSP5tfCh7HgG19jQJZCHiGc2vyR8tpe6ZpGsHqk7Xb/PsCvyUDu1Qhgono869L3EKPE9FG3NY7avMJIFkdqwOh2V83+3eOAxiDWylLYDS8HN6MJCpFKF4KVtFElbowlYuQHzA6AhZXTX/5v5kS93BGc0EEIl79J/pIImzL57TGteA5HxntwWGw+tAGEMYWPcuX6bxJV55qszv4QOz/d7tD18pTxYENw7Yu/rorvdGdJZT6KiDErDBpzwofC3rvoC8CQfZ5V7U6/VnuVIpoeWtQOZ6SjwN5AY84B5qCzLbJtfk0pXHhrD9csivZb2hUIfWP2hxAs2tmGfzYGN+aEfe4iPpmW2fpjGoNR7n+Yf/C8bOt6gLs5u9NhBtXpq/JxmJitQHonqDC+t2Lm+/XMxgX8ziFMEBQaX3hn8VF1vgl+Vag+SJBbPdsEGOOquPmxdzhc35sQUbtNUOxmXACmuotsaNp4J//GvMthEk3dXvN6yOBmehNgpldNvzdgkqooigo9VDxPMidI9wZKFXf+bTJhWYI+4Y9YNvAR4HKkyPjxR+JQfT8LBb3V8OCDe7+zKoRMKv7vzcAyFBK6MM5A==
    DB_USER: AgAwMXktUoRhWZkQV9Ha6LJw54jfNTUmKvNqJY8vOMgbAXfDmihVV08kGtTfa276ETShpRRJuRUcEF0dERRyqgrQGNEGDmUuz8TquNcEDYk4iYRbk/30oI+ebS8HbUOcNYbxzqO+IdEJJFaa/KqXUdUIOaS4GYa7kbPjBHGpAbvkqX74PxJ6ktl5tKaSuF6oO1hQeeSiT9PZDoZoWHGwPe+PwrmBJ8en2TXHvZLFYpim87hMr+I2oT59sIlsBL5fuLo/ivSKw/KrBu+XvxLRCSnF6a9qvc2/Eqtx20uTFvF/uxlvrn82Ws1Wa8t8M57bjelYBIX92VCcAdzxgd0PKJge0B7XhJVhUBrRSR4kdLaH7ZMf7lF9NMMcCZV28Ux8aH+wS6DKbyc/J06utAdwO0NjBgvJjhV2AVW9LjIBaFEmcR8lRsRv5bE78vcuJrwvj2AVsHdThuNXPLSV02WTNdSWXy2YH2wtUwfEZrTIBsvPD7jpUDMHY9P38XkeTjARU3W+oUhGLamFAqgSl65DrE/cZ8kQ42Lh2QlhH6HhGdSln+tqbpa0FA2cD5VGcaGt7DOu288Fw/8MyAGVHrEXKTFNf+IXhOWWzxumDoEIqHr4IzchjNYSjWyRATGgP2K+/ZTUlxGn5Dj9bdis2x064pa2x11dFywU3IACDRgZV9XDrZSlIYqk310diwA2TDQCbOBU2VEg
  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: prod
    type: Opaque

