apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgCTAhkEPHeXDFGbiccXXUMgED3JZvlFULagPDqLkKf8NtRYbcwIhCDxxULl+bwQ7R7K2CO/Xq+JXsFuFtDNJuIfM7RzVwYveqUPNB+0N807ow6iLSvzGBFBC6Nj/ZhHlJjSWifoPEKIOY5uLDpoVdi3pAtxvlpsbk7lCxY7fPQxFfZEbIilL6F1fVu7S/vAujXjliuVIAAzjjWN376ToJbfB7JQaybVTtkAeJmnO7pl5Zy8qq7O6rUHi6jOC6zWOWDqBdqu98MeulhI2CRe5ev1j69K7gWcHUy7huze4loUsfSCTnR1Yd2s0fLPeqbDPnLHjDCS4PCYMtzXtwn9MD1JF6qixxPua+Uk7YjgWXV6ujvp+t434OkMR43tRed1mAMzdGsrjE0J0PBoO7khRDhqrnhRcHDby4o6oUZoa9Y/2POzddxkxmEpLFOEF0TQ7sjnuxUYpbgdJtY0pFUppVCJs5tnzghZsNzY/+ZiCUz+mpm06jy9/AFiQoEGuWTbaCD2WDUnzXOXjSU+K4YBGbaLmrC61PHyPVFiFRwE7uxG3mBzVnEfm/SkP9Kd3T60snh7CZ6081lMz6mOW0C+0G3MHhBAVcQwc77WXhMGwYEeaj5RZXJhvOa7sBCOTyADdD3XNvVprmx182qjxbxYR3aVGA4r91AnuNN9ppZxFZfculD43lF5siNjky8RNzscthnmentMYQ==
    DB_USER: AgAu4LrDvPA5tQEsdExdwM7GyAAVr5kA76vbaERxUm/A3sdMW3oTIglhDM/DNU8Z88/UQOY9g3cjPHQNhtUCXlF7yhMVDk0ciPKAH2pGqqIRwJVwNHeTdFBs3eN4e5MBBHU95uATCq+Hvjz8gv3TKKR/tmg++rJqPlGNTG710vV8afa79o3bthE2O9A/HLtQx4hKTIdX6VbV8/LFV1DHiaRSSFKLG7EVHboWL1QtErpPB8Jgs6ntFAm0jKZgSeptx7gduYkmXON7Mxihxi0EWmn0KXZCzTYcMbjdk/Fgm9V4embGiBRnx43KGMoZRsJn+pUfkAKbL7KbMpEkmGBkCQB1Ngv41AMdS28Ay7jx77S7yhI/vGucN/69VbwFGBJhEGyqLpl1773xJBVRh3ugUiMRcBoemAeg7ncCDok1PdoQdikBGS3zbIyK+BNmoo4BFLocMV8lAySX70+Xzgbz8Xk5P4WjeSuaN4Gx/3kRtnBa3eNWzJeV5Ahe2RKfZu90zXSUKt+gAn4I08HSHEM8+xXweUUa+mQ7rlvq0xmy1VHc9btvoBUnZm7Ic6GIGjnewNIcCD72GtrSF1unBvXVvcuf+kInL5JDOfZ7Df4ZGkh4lMaK2A+eUK4jjSsoQ3o6B8eMO1qRP8SPm4jhipogrqSrsYTpOvh748IAyhcMeT1LgjRdi9EycHpXUpaqjFwKQLqh8dH1
  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: prod
    type: Opaque

