apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgAjZeZeVZGsn3yeDFYDJkWLgmesX3VBwDNbF0k78skLPDZKIKQ0ev/Kve0rUxbgpb1uQzQ/FI4pE/dAuHHcoVtnNQKjRKKwmV8hQrYsIIQ91MpFXWO8iFgQVkmO5D8FNGvZWJJ/lu//yfMf3Ukb2wbp/y+y8ImwO6RprQKZ/ufA7PGFufW+Ahmc7YFdgfFLDK82ZFxKIWolVk0IEJzrh99JvdSMPMBR6BFJ6w/0QcJXdiXnP9Dw3UHpfRph90CDbZV5wbv+o8vYUabfl2NoFmJZY7/BCwJlJ1RLt3Xh1/cVJUxEJou+Lg/2Qq0KVd3QXeInUZyWQdBSisRJIk2gexnLRnJq7ey4EqFMdCEUFT6ENiEHp4EIly3F3SwR+gUBWcAZteCJPoLalyivnmLQ9KGX5V+A0E9dBuXQqwgBOu+EwXwFpw6qAddd2V6UxLReSsBaDE0TBO2qcep+GhRds8084YhLNRnp49KrO4nWZRksJjTchaFdZuV+jz+KYxhUdPxjrROznUw24MErdrS4EiQQgQ4Z/rVUNchzIDuvwngWNfFXfnnhAe+GMFprd/wKaPP2vsBRhhLMarm54QPZcghDXtThGxGMi+975BE4W876m5a6TSlsVs3QDGsenZ/ucJvIx+eLTbcKZrGZwtvMkVlBuWm0GlSO7sFds0qnbDz73cg5AbiO2SIdOPSTw2PspEw/63PH3g==
    DB_USER: AgA4Cg37P0PHPi/r1fWwDnuExMAWkuSi4bXGeRHLOWSTkWPe3NPXWGAJWBdr6kn0TqDY46qUZ44BjMU5AlJ8VcuLpJrELj3y5xgLs6TZGn2inqHTD4BCmzSM+EG9DEdjUPvKdxOqFy4ltNfYla7oImqm4MV8j8URMwW0ZVh3ShDleVMr3/lY6YbuPToEam25A8R2PBItfGHi1HISvotCzA8nn6sftty4M6v4e6Fzo/2bgIM1ku/roucx/J/+VG+gIuzl4cbw23H343KX1GojQS8QyYmOtTy5Uv4s0N5MUtZx64YfP1B/nGt7Qm0+QXCJ3CXQIMMMig7DVOLBnhGWL2lS98/0xKTLqerxJBxRxy1t/TctBpz1X58c1ZeA/0vXVqCA97FMEMKOscU2hyutyMq29O4J4sgvaN1+5PSyV1d5sipo9gZKcZpHk4OaO/HdzlJzqOXBwKcN/ucigWSPgZkoPg4szAeTKSCMvRoVot4Kb8ko6sUz8TMyp7j1eEWgg1z4bKHa4OiKSrlZsvcarJgDCMM9HiwB3YosV1YveEk0gicUEewutvkx+pGOvlJzfBgp9qIV//wJw5doLRX0HlXIjb+RljiFmem+aw2xoiulW6iSo42ecVi2A69OTDjjPcxYJJG3Q1BwPaIVfVn+c1uV/4MtkT7xr1cDK1z40YT6r3jTg6uGx1yo2Qnb3Sc5YoUVFZOm
  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: prod
    type: Opaque

