apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: prod
spec:
  encryptedData:

    DB_PASSWORD: AgAGP0MaUEitmxzGrgA4U88MFp2ZWFSGikClRfBcoztWt4iJvH/ao1CL5IND8LjwSaf9v3rqmb7pgKCpLoMFR6e5/xvWOvx+ST6Bo+23i88aVvfzQnbqeK0re55JPGpR9W4HJfy+j3UGNH+XouibcrnJIYXFq6EO0+DGSNdNlvRc9t1kq/gZw0l0/TT1kog3iHPbEQPkyVndc7oUeuS4zqDAiJ6Ig7kUuJ4fPuP0SaQi0xQD2CyKDsruz0a8lia/J60XvV2H7NvYAcKSuUAWgqyzXOKsF83q2Xif723bQjPGXDGprfvcaElDVaW5GV/OnxKqMjFxvPgSkGSXDMXvBYL3DdpdM0LgL6OL2B5BqFsAA+tungeu6/4dMVujGvdli4QZrrBIcq/W0vRnpr6DkYdgdO5igDBVAwsu7D5sEJAlRctUOOz2eUq57L3Mziq/a2au12I1VWObzIL0qvsG2EeV7dlQetywRiB/d6qFRwr2QX/EmodVh9B/uiIhPEHDYB1tYWbXU4otpbTWO2b8ELGJMBuWX1Bj08aqBXZGdVUW7wBQ1j9FtYgPv6fYA1fDIcQpFdFeFZWU6VHiUCeFXMG3yx+pjvofpvGrgfkMRd2opcTOq9qzXMJjKphYcwcTTTjO+h0N8lalM55rRSJ0TjLemETFMZXyGf0lY2jYkMqenuXxX8VjKOaHPA8uZOaOfexkL+th3w==
    DB_USER: AgA2jkzb28JEeCu+0HgymZzbxfl5nWqwi3/bPSh2Y9tUziAjymKxqvxGQxH0JB67L1djbkIkFPu+GdL0bI9fUnyJXjvan5ZwmwO3Qy+VZDPtDp73kMc7gl4cP07OWmfkd0Q1b79bKUzYf9sVWimDG4n1dc/y2vs3hpzSpEHrl0bqqGM19T4MVb8MW1XHMMhWngqsfKDNNKistOUaMXO8HHLKZcHj4y7nlHgFNA+jn2Ri+yFFhGW4DCo8eE3W+8/9rYhtrVHn62e96iA9f4EufA5RmzW/M+By0bLAWANoOzEDHsTXd4w8zn773F8aBa9GhqjlR4QO1Zfa+2/Yfds3xWIiUwz1IlcW5mOjV0//AcjMQ9lEIpB4KNoNQk2eeieEn6w/V8rARrWxMUz81LCqKeutyRCPfH4pHa5b+BMrzaLBVwyvjPK8R7WrD6Q7hdU5A/Ofg0sOIq7MhsDQv/d6e/TCwzDMQmR+olFH3MQ3YCOJt9NoPZ5Fjve7qyqz6vJUZVKmpH+o3SdQfPDPeSjAu0dtEh78mXGqYgIXsFYtyhYUZisvfNlGHVk2apRPlC+MjHnMHSWenH7dLpVHpNAYBFwYRCiVIIwzGZCLPjOWAmVQS8SqVDiqTcyOex6LlwrfXCx1YQctqDjWmPyJveMOTPumYnk8Gz4YBL1fg90w3lgOMkx6Hpg327NM41w5Q27PHDzY2pgY

  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: prod
    type: Opaque

