serviceAccount:
  create: true
  automount: false
  annotations: {}
service:
  type: ClusterIP
  port: 8800

# Configuraci√≥n no sensible
config:
  springZipkinBaseUrl: "http://my-ecommerce-zipkin:9411"
  springConfigImport: "configserver:http://my-ecommerce-cloud-config:9296/"
  eurekaClientRegion: default
  eurekaClientAvailabilityZonesDefault: myzone
  eurekaClientServiceUrlMyZone: "http://my-ecommerce-service-discovery:8761/eureka"
  eurekaClientServiceUrlDefaultZone: "http://my-ecommerce-service-discovery:8761/eureka"
  eurekaInstancePreferIpAddress: "true"

podSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault 

stable:
  image:
    repository: "barcino/favourite-service"
    tag: "0.1.0"
  replicaCount: 1
  
canary:
  image:
    repository: "barcino/favourite-service"
    tag: "0.1.0"
  replicaCount: 0  
