blue:
  image:
    repository: "barcino/cloud-config"
    tag: "centralized-confi"  # ← CAMBIAR

green:
  image:
    repository: "barcino/cloud-config"
    tag: "centralized-confi"
    
service:
  type: ClusterIP
  port: 9296

# Configuración no sensible
config:
  springZipkinBaseUrl: "http://my-ecommerce-zipkin:9411"
  eurekaClientRegion: default
  eurekaClientAvailabilityZonesDefault: myzone
  eurekaClientServiceUrlMyZone: "http://my-ecommerce-service-discovery:8761/eureka"
  eurekaClientServiceUrlDefaultZone: "http://my-ecommerce-service-discovery:8761/eureka"

deploymentStrategy:
  type: blue-green
  active: blue 
