blue:
  image:
    repository: "barcino/cloud-config"
    tag: "feature-monitoring"

green:
  image:
    repository: "barcino/cloud-config"
    tag: "feature-monitoring"
serviceAccount:
  create: true
  automount: false
  annotations: {}    
service:
  type: ClusterIP
  port: 9296

# Configuraci√≥n no sensible
config:
  springZipkinBaseUrl: "http://my-ecommerce-zipkin:9411"
  eurekaClientRegion: default
  eurekaClientAvailabilityZonesDefault: myzone
  eurekaClientServiceUrlMyZone: "http://my-ecommerce-service-discovery:8761/eureka"
  eurekaClientServiceUrlDefaultZone: "http://my-ecommerce-service-discovery:8761/eureka"

deploymentStrategy:
  type: blue-green
  active: blue 

podSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

prometheus:
  enabled: true
  scrape: "true"
  port: 9296
  path: "/actuator/prometheus"