{{- if or (eq .Values.global.namespace "stage") (eq .Values.global.namespace "prod") }}

apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: order-db
  ports:
  - port: 3306
{{- end }}