serviceAccount:
  create: true
  automount: false
  annotations: {}
service:
  type: ClusterIP
  port: 8500

# Configuraci√≥n no sensible
config:
  springZipkinBaseUrl: "http://my-ecommerce-zipkin:9411"
  springConfigImport: "optional:configserver:http://my-ecommerce-cloud-config:9296/"
  eurekaClientServiceUrlDefaultZone: "http://my-ecommerce-service-discovery:8761/eureka/"
  eurekaInstancePreferIpAddress: "true"
  
podSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
stable:
  image:
    repository: "barcino/product-service"
    tag: "feature-hpa"
  replicaCount: 1
  
canary:
  image:
    repository: "barcino/product-service"
    tag: "feature-hpa"
  replicaCount: 0

resources:
  requests:
    cpu: "500m"
    memory: "1700Mi"
  limits:
    cpu: "750m"
    memory: "1900Mi"

hpa:
  stable:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    cpuAverage: 60
    memoryAverage: 80

  canary:
    enabled: false 
prometheus:
  enabled: true
  scrape: "true"
  port: 8500
  path: "/actuator/prometheus"
