replicaCount: 1
image:
  repository: "selimhorri/product-service-ecommerce-boot"
  tag: "0.1.0"
  imagePullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8500

# Configuraci√≥n no sensible
config:
  springProfilesActive: dev
  springZipkinBaseUrl: "http://my-ecommerce-zipkin:9411"
  springConfigImport: "optional:configserver:http://my-ecommerce-cloud-config:9296/"
  eurekaClientServiceUrlDefaultZone: "http://my-ecommerce-service-discovery:8761/eureka/"
  eurekaInstancePreferIpAddress: "true"

