serviceAccount:
  create: true
  automount: false
  annotations: {}
service:
  type: ClusterIP
  port: 8500

# Configuraci√≥n no sensible
config:
  springZipkinBaseUrl: "http://my-ecommerce-zipkin:9411"
  springConfigImport: "optional:configserver:http://my-ecommerce-cloud-config:9296/"
  eurekaClientServiceUrlDefaultZone: "http://my-ecommerce-service-discovery:8761/eureka/"
  eurekaInstancePreferIpAddress: "true"
  
podSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
stable:
  image:
    repository: "barcino/product-service"
    tag: "feature-db"
  replicaCount: 1
  
canary:
  image:
    repository: "barcino/product-service"
    tag: "feature-db"
  replicaCount: 0

prometheus:
  enabled: true
  scrape: "true"
  port: 8080
  path: "/actuator/prometheus"