{{- if or (eq .Values.global.namespace "stage") (eq .Values.global.namespace "prod") }}
apiVersion: v1
kind: Service
metadata:
  name: favourite-db
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: favourite-db
  ports:
  - port: 3306
  
  {{- end }}
