image:
  repository: "barcino/service-discovery"
  tag: "latest"

service:
  type: LoadBalancer
  port: 8761
  targetPort: 8761

config:
  springProfilesActive: dev
  springZipkinBaseUrl: "http://my-ecommerce-zipkin:9411"
  springConfigImport: "optional:configserver:http://my-ecommerce-cloud-config:9296/"
