blue:
  image:
    repository: "barcino/service-discovery"
    tag:  "feature-netpol"

green:
  image:
    repository: "barcino/service-discovery"
    tag: "feature-netpol"
serviceAccount:
  create: true
  automount: false
  annotations: {}
service:
  type: LoadBalancer
  port: 8761
  targetPort: 8761

config:
  springZipkinBaseUrl: "http://my-ecommerce-zipkin:9411"
  springConfigImport: "optional:configserver:http://my-ecommerce-cloud-config:9296/"

podSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault  

deploymentStrategy:
  type: blue-green
  active: blue 

prometheus:
  enabled: true
  scrape: "true"
  port: 8761
  path: "/actuator/prometheus"
