apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

stable:
  image:
    repository: "barcino/favourite-service"
    tag: "latest"
  replicaCount: 2
  
canary:
  image:
    repository: "barcino/favourite-service"
    tag: "latest"
  replicaCount: 1  

