{{- if eq .Values.global.namespace "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favourite-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgAybWSxAK6GnxPGbIU1Q3WtFmqjmeCtEGTVwU0WnrLchguVx57Ks3CP6lF4IjPROdxTVCQTycqxQ5p/St01iEp90nIgktGjgcTMZBjmChIhEkIfPOpj2Ep3ZiHk0t2Uj/U8FWKbWg5553V7SYUMqSdQ3O2Qg6m+IodzWme6WpDRXFqS7C5/i4lhVwz0a6rDGYbHM1lc/5nJNGn7HhdsyJGYWYgkIdwyPCe6NFi8SBp3FLu9tt+JKgRQ9BdTGIzPW3q4IpL4btdHeZGBPG4IopZQUjHi9K/YLCQNlVnFNh4ZCFge0P8Qmnqf9guetEVnc7ONZ5rH5DjPwdEI3in+5cv3W7TrRLTdEtHcS/rjmrpE1ZQnkfrK/r8JGt2WEUbcmpPoe1tU3YHYh9GzphCzNE14diV7IsFM6pXcdINLXoCkokk1ZLtaNsHB41O4b6fiBA5Y/W8BYFUq43nenZLA9zWHqBKaTrl+fEKXRShKxhi6Y9baE5kGUawYyiPwuj4Olbt3uDOIU5IGo86qJk5NyHOagiu7Etp5a1927MJBPrp72Uky4y/W7zWHu/AuH6oFQOrKim8cWGK9bUSD5MFN6FqpYipYhpj5xxdyJCitaEB4PZmSMI7rc1GTP8P6/d99bvKYSndhVcD0nCBKCU5XY9Md5f5dKUZXklcSabZnCIGsPPs8VIHV55emFskV5ag4UgmoLFoo3A==
    DB_USER: AgAAv41m8yl5PGm1iR57T6PJjkf6TWHkND3zLtugkpXSm8B2hyczjaBTP50XDDuTEumU7t3INZzVEyUty3iwosy3Z69H0FLTOtggscBwAj1ckzynDI+0Z51dlpeoWubCUQ7jTg3tKiZIj0qpoB9P93Z5kBWXO35tOLGeQ4Tqv+KPZrRJRDDV4zHy2ZW5XYfsen+U9yvbeRUogFiFELv+RYFEJp4V6X7Wvfw9nioRsXwEb3kak9Fod6n7LvW7ORUYzlsoywb1QsdUeNR/ne4OU/aR2CrXZhb2jmZZs+zCoh11Z8gZrwzOXxvvhqgBciutqSWT5Dz87Vd3abLW/d5D4BPeF2QXoqhOChFlJpPh/loaDLCpmPgK7lQP0PD12AlomIVJmMsHdvHRupvWDdOK67e+P7UFVU/M/lso4M2oKxpm5CGvjB0L4kb9rw/krljzc4TwCVIBSTfVAV5wDRi+9Fx/u3hku2BQ8lrHzuWJ56+A2yrPluig4FmYFK7LrtYBfcAQMn6SpXubnZ8/wKzyX+qbm1HgfoFxwlgbe96tvaN0n80yJEyO3hDf+s7/H2PN3YnFk7t7jImg/cqZA7K+50vpYkJpLxYS4+sTY2ZcOn3U+CEGlhkpBWPm2ZK88tiTmJ607SfNw31cWoEx8lq/ymTBvRWGzrSVEtTrmcnWdzCZBBXjRoZTuw2RsL9H9lPNk4wsY5qD
  template:
    metadata:
      creationTimestamp: null
      name: favourite-service-db-credentials
      namespace: prod
    type: Opaque
{{- end }}
