{{- if eq .Values.global.namespace "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgB9DkUEh44R9TmvbepFdjJs03VlxmzGRTK/khyRR8+KY1HoLPW91UHSfkHT8BdkoEuYV/XrlINHy0tEOznzXZY50YmtJwmPn6jL7bJHljM96JannT63Itiw+wxWYxY8FN/3QPFQ3R92/UGyAUbETvVkxxU9QktQc69kSHJ0EFEqAF0JCghKIjn8cqjwWbt4M1pEu5CcsvMEXNU474M7BwlynhOHPl30D8tUZKhmc8Hsaj9JbDWQWfGREivbob5OY7fANjLz6yPmw/c5MfHWcp7VRDzzmcTFOdOcztggidcUffXdCRSNMuJMHS7N5Xrts+Xqm6aw3j4LYQhqzxcNjpQToHZiyx0deP2bhipFMd8A5Kd72mAvxcjML5aYryBqGg098YHcq4B5TrGrxS0ebnVltA43TBybCidOjtaaDu6QjObg9HiFEevb/BBqk6qmD6jouS7K3RKzjnCQwUtlcKxHf84ckq70jBGRslpliJs5uG/z5VuSOz1kwS3yOh6oH+2/PWerfkq2PcabLrZ0nvHAMts/Op8wf2T3n6HbPK69xaxxA1p64PO2tFGvHNlSrUTm0alE+QVcfpy/nt1gBxCt5Is+alhu+Kbzx5vZMj9TMB+5PvC5LdcgKYxlR7dpQmxh2mC/sh2B379wz9VGLg/Ds1A3BvdnidoLBeNTRWXLZ8mRR5zpfpqbI9huWFN1Dy7NnL2MFQ==
    DB_USER: AgDVWPWSh2LSWKpqCYEDD7runheNmTqnAibvTHFZPKG6K2hrCKhtSugxW3/KeGG8PHxBJqjY0b7ZpvFJ6jOc+2t7bMwxmfSKWMwZD/TnrV6T+jnzH/I5AyhgcEwpQqH5dc5ERHIOtR5aQZQh0sGHu8pcB+GgsfiCIOSx9lTGXqS0WZ757fznjpExuAHLAqtLAlvFL24EekJEMmR4Qzd+8FHSkup0etgvBQpXb7lhGczkn5dpzBZLiFTCtx1H16n9Dd7CHzEcG95v9XTV3a8k9NjZZbLEgbcgEr2RBlvNRzMb7ADfLSxYlgjAjEb4E6PPsbeX+4xSFnXz4CgQ5i1tuEAlYr6hE4sYV04nQ62e6gjB9Y0LK0KWgDF3GIDDzgAQd98y2DqJGLI1II6o7j5SD9dU86Edjp8zUdcJXZ5iTNq+DGDRbWDCYWxhNZogHoJ5mmjchloyl/dic5UUSkCkk3pZkwVKTOEBc7XFQB7HTnY4RhY1ZR26shRU7KksssLJMTGF2JNemqdX5AvtO6zGKCSc0oxCSRR9KrAwrFAe1SNxrmMqvwJhwvrTEHM2WkpLySa7ew5XZ5XsbsyWD+692E9G4jTULB7E7DQAF+jxCNDuR+b9ZWMgMhpPPhQyS1qjYRAQs31aiuStCWwdi2YtwSX8XeLGAx6UxWWdJSRBtj5LwYl6ZK7iotoKHlCaqkaM3tJYQwpR
  template:
    metadata:
      creationTimestamp: null
      name: order-service-db-credentials
      namespace: prod
    type: Opaque
{{- end}}

