{{- if eq .Values.global.namespace "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgBtEfJMh9bl/Ra57Yeu0Zu4388n7oyJaTV19jQ6btsp/+G4bN9E6jZljltSR3pruu4a42SAdn6ZeQ0/cYjJvQ5oHMtBqYZscMqDcGNaJ3Ti6AfYWaaglso8sbyNVwWwb7vsYbaz4JPnryE4+n1VRjv+XtJgKM7Unyhmbl/yGn4/OREJR7Hi3i039fTDmwOaBtypnEOk3uLsGvUnLVrTJrXx/wyBlahm17Vw1iof4rHRiobgJ56QXu4/rOGUEsdB6zwow24wqCxg1KHPW6RgBEyUqxynPdVz8569D+Hq7QEzL9o+KB4ctdSVjzaB5invnDLHrNC8/ggo/mJT320H+c6h7kfQflUv6i0Px6utFPP1wcUZUfllcI4wpk5cK+2wHZoXICv98DdTLJVZlFOfT/Z5l5t/s2ctkwaVkx3SOXz0Pz75+mhQysDgMDrS1kx4UTpnCDvJM3XNch7f7szME1afzBJEdos7EROoey7jQ1gj1PPGQ6jNze/g3tKbqdK71eFvDK/twOzx/PwyZZdcBt2DupLRPmXM/Btg75BVyTjJcOfDMzUcRCyjwEKI6fqtj8rU+KqWz7qy3c2ebFnZIkaG6vfiuqKiKA614I6m1FrG6eK5lZF6ieWY5HPkt+ntSmv7FNJY8rIZS1Z4lCyD2bPBfPX+EnbcEy8/zylrIREAZolvUNrJsvKNs1DfXDgkU4jFjElIHQ==
    DB_USER: AgCY75Twu0RzC8Uy54JcbmAFZS9nCsGgULzvNi0LEUWFX9tA0VcTBUt68nLD0U5SYQCT8DdQ0YpnVvSWwEU3PVcqAlTofLeCGWRwZlhcCPi4TZcLEo9RlPe3lBfGeSGwT7UYDIemCFN95HNX3JzlPUlvjl/n5dsBnOmJ6hjpUgKApu1bM5ll4Dp7ejD80mHg4R3ghcqJDx0n7PSl3F70fBPGtr5Cfz9cpClPR9SppQY9qt982k28CNi3arL+C/Syb184+HBV+6ag1NCzrE4/ZnVgi9NPkjDFu1oFh47wPy6/S93phusWBUjEw9/4A2YiRnFEwygwxWCNmKQSWPxHFZudGsenARfLaHdUZkHV/TwB22v3/HQG6s3XOO3XUAPpx9wpwTCprV/LGrzqfjj8UCpwsme1fDg1o20SQIb0b/58dbl4ZruLTrHeBwHRGdaz4TEodkz9yJJHDw+59W6IxyKJCZOUEOUJCk8E/fIOjlEOZJmqEDyDCgj8HfMHhkQgqBddlIVTHMr+GFpP6SGdXrcztp2pN1g9GqNgpZNpELILi2TQtWoxn7/yGlLn8t+6QJMBnvLpyb9gLyD+SuUpzrJbYbX1nhyZFAWH5DNUESTgdSV2t1YFGC7i9hF81ULA3RNK0oXOqTbhWOIWOjMD9ntTAxs1m+fjFJCJhA7uY9Q59YwWY2lQ6zZ7Vtdi0mLqW3hy+xvb
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: prod
    type: Opaque
{{- end }}
