{{- if eq .Values.global.namespace "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgAHdegRzFWsuGlEcOK0G6+7shYdqqLM8+0xkoZG+geyt6gK2kRn9+H4bLSdCtnJF6SEDgYGdcM60+fScsx5aYcdDBfzZldLJ+bMmaA+tc6ep8B96X4ga8ZEwLVyqCWBklRycZMgW7McJIpNlBeNXQmImZyEuS3XI8HuoBDt45qq9Dn5KwbFkNAL6ExTcRxqOGTpsqTv4ZulqYrcvRCNRPOueHKjvUCJun113DhIfiWd8YXdSzF0F8Y2mG5a7mRCFag+yTVFoy6+G9FBs8TxJ6eBaAGqaStuPgFbQfndVMQBM6XtPqml9shx/pxSrv8JyQ/O9PokmN/cBSAwn08zMeFlsrGE+YjCYFETPqIh/k9ihjMgV9aIbV3iwp9bYmMgUcEM5Jp3ov2RPF1LSzzZKeE4o9E2i7OVo2DpXwczIAWoDiCeAVPBj89TOoHFSHYGCoYOMqXewM6e5En6D2tHluaWx0/3lFAcL6syxp3TYZJaloCDLP5yTys5kDhgHRLyi2lJhyji6KWVLEejiGsQpoRo2TY3R+4zD17m/vWRCN3a/NSfmjJtqPccC7Livgl4sNcrT+cqG6ucXqUDY0DhPqxi+JStV8llRc4SKfvsPMO1yxHgB2MhXn55v3yari6QKBDRIQpwreosuY41YzbjUofSFin2dGCmaEd/Z9V/lDMcZRGoHlkKx0UIfb1MB57B767IaFLM9Q==
    DB_USER: AgBYnokNKT8kCN7T7nuUjIIHaKb9/leUVzLYD5JloSf3mk7t7nMOcZZaITszdWiDvUCRUTmrTENvkYcNDEyBkUP8YiEKeF43JC8smkPd7z4QoUEUWK9VTx/LZ4XeaC1UacnjoHWLhRHtoK1RqtYY8I+w2njSzCszDpzkx+kK8vecGW6IFIcGNtvHZgbKSlceeP7ivcW0rKs7GIzVU8SV2CtjaLPKdhXHOu0xHKRLCTLj650bcWQTyGALxaexc9PaPuGu9o4ENNuf6kgZoHlwJNUXdaPQq0iid2B/18w7XhyB7B41pD9J2zzc3h/aXW884SMUpYbKgreXkJqRDFHgiyevhlO+r51pNTNs/0Y15pHgBrC34EQDukSJzyEt/CXTAceBwILRjSPhVZS4AaHOGTyX4/zAuOGSsOYeyNXpaQ6eGnvX7gCCpVGirkKUorxXa43wMF9Q8p669820ko8JxD2BAJ4qUU1MbEfIBcgohDW8nlQtTxXsnULqBKQipMI7L9zuI8dnoTNe2r2hoI3SqmhzR29V79+jlJbR33Z8m8zdWIWrptTQt31VcOpulT4ZVdcfiujMyVEjuLnhCVbDFj+LWfuEYo+Heez7cm4u27stpzqboJnfZnZBf8GuCe2r5iGfIky0Z0cfHnRkGZqGgV5/fDgS0KXvRkYph/euDw699YK+xlQk2Cachh336DpSLiYOiPsU
  template:
    metadata:
      creationTimestamp: null
      name: product-service-db-credentials
      namespace: prod
    type: Opaque
{{- end}}

