{{- if eq .Values.global.namespace "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shipping-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgBUBbfagOsRSFvbKqPLOYSVRQE8PjFS6/ilJhQL8c6LhCFXFohdsxCKroN1bOPnlxIDUHzU+R7N4vfkMkTNcw3/FtEekf1spCTESghLFVde9HMZpuihQVWdQ7znutyBm5JY+ycgUb153BMpsCJNnZ2NSmt9gv1bSAF54D8y+cHdtsQ+T2/ZxBv8ZOFjkHr4A4Dxnze/DxluLUCQ1Z4cEsK9wzHwB/gAQzUYz7eRaJ+mxDZNtM7qsTsFEFcmBTJqt/D8OkPeMcHqC/6s6/lLUDSuhx7e2ZURDpF1jGRXgtVP0zMVvNe2/Pwjueb5n+SncErEUrjRArjJF9ATL/32UlqtDcHaCRZfn3n21m9SmmlrZZXIqpC+zmgUoXo0yCYH5+yS34xNSDcQXNGfB4uPBxgHCyPvyWXrG5X5011PPbx+jRdLPXlWVxVgzz03rRy+QegL7SUKDiDPAIKec6AlAZKlBKmzPA3oN4tz64am4kZDkBZPrszz+HroiX1/B47dpoJmhbGU9NZgFV70Pc5Udrj6mCZ5gI//L8nPlr7W3ytxxdkZxgDybPK894cuys7BZX6/b0PwZp2vNGDDujF95j0Apx7rFxS6uEy7Wv7I2FaaLqED+wXrKoFcdzn7q8/Xry9ROxF/gsYlFFAkr3lLf+97J9k24n2DjRdEdx06jyFcewljbtzxzGiMoqsDuAjS2h7lKRPpMg==
    DB_USER: AgDKMzNlJyiXdjWyiiUD9Y5nEN7LKM3frXLGEDtS7oIhc08eDHtAPTFKepfb5nt2vGLzbkEfmSHW3BgqD8VEn/dvpdhpY8R0G3UwFRVWrlA3kwvC2molpfLpdjEiJ58AMbO9R7IrQIpR+pXKjDA8A7UCq90m3FE6sUbHrgs3N3nuTRrXvu3BYPIAxi39l7LacGe/A3BivLMdekT2joB4rmVIl4yJWTk5rfzICsKOn7Qrn6GYU4s2v7Lrs2MkDlFmXGstuwIFcdVgQ6wpbx361kOM3TLrdZ4QDPRQhIKLaR/95XWypp1JQpXcrUk+DO76zi+AAUu0ayO3l0Ewhlsze/NZDiDaDO8jvLjE+N4ayWJbX+mZAfI1YkS5v8shodPr9lbKexU5VH6ty56hT1rRCnEoouxxm/uXnrY4PcchaLnZH5Lj1gmNFVaC0BPG0NdtxQDocKZtSFu7jjy8Oc+meU1diht5UdLj8UjKd2p1j6WMK4oHt0wb3l4t0pkmNsocH4sQYGo0fsSzqi8Vy0b+Hk6QGokSqPErm4Hq99PtYkZH7jfll35tb+Mn+AoLoevmfGh5oKOPfq2GK4/1r/eZSbClh/xgAkt0IogCOm5elIa3DPzDe7a/7BwkAoMLBmlAFqy0130LXqG13tieppu9AzWCV1yfJR01Z+VhJv5i2jTzoEk8FkuNBwXdmpb4zUsswllqb7LX
  template:
    metadata:
      creationTimestamp: null
      name: shipping-service-db-credentials
      namespace: prod
    type: Opaque
{{- end}}

