{{- if eq .Values.global.namespace "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgB07iwQul0kQaeGkhxv34FwuHENn+YIxCo2bYSVr6MD+d8iIrC13IeXmHEx/sVEWWRse+tDngaUOtOmh/79i8l9JKJFGlCeI31nC7ZRCSms8cGhpkQc3R4JYAvoxLoID0rt6igk1PLzebqpPS+n42IoRiq2ysVCcZS7axYZHzDawC58/fypE4IYcLJdQE0fpWW+jrcrsn3v9tjwNPWf6mZpsCw0xqGz9AJcKZ5JZhjsoxMM/FNc1HQ6rjr5rDCvFPowV5rPwxtogRIU7I9gFY5hUzr5Nsr2rBX8z/ts554JOZqA2W1Mb+zLC1XTC1yNMp24nM8XS7Fr8NsMf+au091/bWzTz6SwFWfjJv28TKanoEbOZozisfxT3j8wim+k/97bFIcrcfaK33TfFJOtSdgEOwXvWqdjoUaBwR3eqBWO9icpWQqD5XiUGOhpdp6YzDs7PuaTAupvC+3OTELG7mY4KLptLG9Zni3CzSUNo+6hUDY8SwP8WKgXiDoLI2rfyd4pc3JOoR/Tu6tQZlrVHg+JZSZd1Yh6gjqHcn3kdxn+4NZWHxYwJ2sMsZ/h3QgokG4i66yhsO7m9Z3bq89cBQIo+tA9AzZwDCtEgq62HnCGCQwLOTwv+lWpjGvF3Yl79qo19w5jGOLGdLXDN6AMj5YoeGdTzJDdEjXBbxwVzmlrHkXB6etC//Y1eU3IE/xmhLN6LnbBDg==
    DB_USER: AgA+vp9I7pqBZvoMbFJ1XV+emkvngfREHbDK3F6EJBMdrZ/9ht7FNW+VUAHrwBIOUC5tLRC4aZuzrYx+rsoHH/QOjDuoKNN/1jxsGKlETONQdToXpBTWgvBIghrdv6h7iXROgvlCEvlGY6MohQB7QwCmNlIklwowo/CAh4C6rajn99NudmGdoHGyi5gvsLofthSlSu2LCg4YXBi2s1gXdHY91brQPz3NiePVow+iJwTG28vdpJxvmaJld+tFg2aAvMyDYxoHH0sJn3xV3l6NPFxY5KL1Re/GIWoIE7izl7frmb49MGMarNxzMhjn5cOTVFhG6ihsoW4B14zLj/2BlvfK5wUvJmBBumKUFz43HTiPGcx5HunWQMNwZbT7+UflCalWnnctr4t7bN9JxR5hhFgGZFgHASpHPXe7uRrNGKNiWQYcjzPN0l0bR0umvXSxWPfHtoK2u2lKGyQ6GY/YwusJ3LFcCF2DVFtg3kPnTR5KG/aMvx+MZIrJaXnVhss4VGDXZ/uBpe3QXu0Qlb8eBHhfWDN3SkCmd+Wodr09rIoYNct7A0xEPycEySZV1RtnpI28fUZgUKz2S5Bcqc5DlA8qAb7/kpd12E0KuZN3X79TfHIgkEDBZn2JXS0sOSQ6d4Mqn6te/vm1IHR4jkbIgdsWDuYNx2g8hlKQ84uschUKw3EjQPehXu3Alp8hcwR8cTwIhRTQ
  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: prod
    type: Opaque
{{- end}}
