serviceAccount:
  create: true
  automount: false
  annotations: {}
service:
  type: ClusterIP
  port: 8400

# Configuraci√≥n no sensible
config:
  springZipkinBaseUrl: "http://my-ecommerce-zipkin:9411"
  springConfigImport: "configserver:http://my-ecommerce-cloud-config:9296/"
  eurekaClientServiceUrlDefaultZone: "http://my-ecommerce-service-discovery:8761/eureka/"
  eurekaInstancePreferIpAddress: "true"

stable:
  image:
    repository: "barcino/payment-service"
    tag: "0.1.0"
  replicaCount: 1
  
canary:
  image:
    repository: "barcino/payment-service"
    tag: "0.1.0"
  replicaCount: 0