service:
  type: ClusterIP
  port: 8400

# Configuraci√≥n no sensible
config:
  springZipkinBaseUrl: "http://my-ecommerce-zipkin:9411"
  springConfigImport: "optional:configserver:http://my-ecommerce-cloud-config:9296/"
  eurekaClientServiceUrlDefaultZone: "http://my-ecommerce-service-discovery:8761/eureka/"
  eurekaInstancePreferIpAddress: "true"

stable:
  image:
    repository: "barcino/payment-service"
    tag: "feature-deploystrategies"
  replicaCount: 1
  
canary:
  image:
    repository: "barcino/payment-service"
    tag: "feature-deploystrategies"
  replicaCount: 0