service:
  type: ClusterIP
  port: 8900

config:
  springZipkinBaseUrl: "http://my-ecommerce-zipkin:9411"
  springConfigImport: "optional:configserver:http://my-ecommerce-cloud-config:9296/"
  eurekaClientServiceUrlDefaultZone: "http://my-ecommerce-service-discovery:8761/eureka/"
  eurekaInstancePreferIpAddress: "true"

stable:
  image:
    repository: "barcino/proxy-client"
    tag: "0.1.0"
  replicaCount: 1
  
canary:
  image:
    repository: "barcino/proxy-client"
    tag: "0.1.0"
  replicaCount: 0 