serviceAccount:
  create: true
  automount: false
  annotations: {}
service:
  type: ClusterIP
  port: 8900

config:
  springZipkinBaseUrl: "http://my-ecommerce-zipkin:9411"
  springConfigImport: "optional:configserver:http://my-ecommerce-cloud-config:9296/"
  eurekaClientServiceUrlDefaultZone: "http://my-ecommerce-service-discovery:8761/eureka/"
  eurekaInstancePreferIpAddress: "true"

podSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

stable:
  image:
    repository: "barcino/proxy-client"
    tag: "feature-monitoring"
  replicaCount: 1
  
canary:
  image:
    repository: "barcino/proxy-client"
<<<<<<< HEAD
    tag: "0.1.0"
  replicaCount: 0 

resources:
  requests:
    cpu: "500m"
    memory: "1500Mi"
  limits:
    cpu: "750m"
    memory: "1800Mi"

hpa:
  stable:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    cpuAverage: 60
    memoryAverage: 80

  canary:
    enabled: false 
=======
    tag: "feature-monitoring"
  replicaCount: 0 

prometheus:
  enabled: true
  scrape: "true"
  port: 8900
  path: "/app/actuator/prometheus"
>>>>>>> 45e408f8b12cf296a6fa6dcd52d01a8b83c1882e
