replicaCount: 1
image:
  repository: "openzipkin/zipkin"
  tag: "latest"
  imagePullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 9411

# Configuraci√≥n no sensible
config:
  springProfilesActive: dev
  springZipkinBaseUrl: "http://my-ecommerce-zipkin:9411"
  springConfigImport: "optional:configserver:http://my-ecommerce-cloud-config:9296/"
