  global:
    namespace: monitoring
    springProfilesActive: monitoring
    replicaCount: 1
    metadata:
      name: monitoring
      labels:
        environment: monitoring
        managed-by: helm
        pod-security.kubernetes.io/enforce: "baseline"
        pod-security.kubernetes.io/enforce-version: "latest"
        pod-security.kubernetes.io/audit: "baseline"
        pod-security.kubernetes.io/warn: "baseline"
      annotations:
        description: "Monitoring environment for ecommerce microservices"